#include <stdint.h>
int main() {
printf("%d\n", 1 / 41);;
printf("%d\n", -41);;
printf("%d\n", 26 + -23);;
printf("%d\n", 9);;
int32_t a = 59 - ((-11 + (-2 - 28)) + 8);
printf("%d\n", a);;
printf("%d\n", -9);;
printf("%d\n", a * (4 - -25));;
printf("%d\n", 27);;
printf("%d\n", 4);;
printf("%d\n", 14);;
printf("%d\n", a - a);;
printf("%d\n", a);;
printf("%d\n", a + (a + 26));;
printf("%d\n", -107);;
printf("%d\n", a);;
printf("%d\n", a + ((((a * ((123 / 37) - a)) / a) + 2) - ((((-9 - a) / a) * (-12 - (-37 - a))) - a)));;
printf("%d\n", a);;
int32_t b = a;
printf("%d\n", a);;
printf("%d\n", -7);;
printf("%d\n", -4);;
printf("%d\n", 17);;
int32_t c = b;
int32_t d = 20;
printf("%d\n", c);;
printf("%d\n", 67);;
int32_t e = d;
int32_t f = -17;
printf("%d\n", 38);;
int32_t g = 32;
int32_t h = 17;
printf("%d\n", g);;
int32_t i = (h / (b + -25)) + (((f + f) - -90) / 56);
int32_t j = -18;
int32_t k = -51 / 27;
printf("%d\n", -8);;
printf("%d\n", 77);;
printf("%d\n", k / k);;
printf("%d\n", (76 - i) - j);;
printf("%d\n", 66 / 14);;
int32_t l = k;
printf("%d\n", a);;
printf("%d\n", -16);;
printf("%d\n", e);;
printf("%d\n", -11);;
return 0;}