#include <stdint.h>
int main() {
int32_t a = 13 + (31 * -4);
printf("%d\n", a);;
int32_t b = 80 - 84;
printf("%d\n", 65);;
printf("%d\n", -49);;
printf("%d\n", a);;
printf("%d\n", 74);;
printf("%d\n", -37);;
printf("%d\n", b);;
int32_t c = 9;
printf("%d\n", 28);;
printf("%d\n", b - -41);;
printf("%d\n", -18);;
printf("%d\n", -1);;
printf("%d\n", 95 * -33);;
printf("%d\n", 23);;
printf("%d\n", -61);;
printf("%d\n", a);;
int32_t d = a;
int32_t e = a + (-19 + b);
printf("%d\n", e * 4);;
printf("%d\n", b + a);;
printf("%d\n", 50);;
int32_t f = 3;
printf("%d\n", (8 * -56) + ((3 + e) * (-44 - -29)));;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", -58 + (((e / -10) * c) * (11 / 19)));;
printf("%d\n", -52 + c);;
int32_t g = e;
printf("%d\n", g);;
printf("%d\n", ((-3 - (18 + b)) / (21 - c)) - ((12 + e) + (61 + b)));;
printf("%d\n", -62);;
int32_t h = -43 * g;
printf("%d\n", 34 - g);;
printf("%d\n", -44);;
printf("%d\n", ((((-16 + e) / 9) * 4) + -13) * ((d / c) * (f - (-19 + -33))));;
int32_t i = 16;
printf("%d\n", -6);;
printf("%d\n", 44 - 2);;
printf("%d\n", f);;
printf("%d\n", 61);;
printf("%d\n", b);;
int32_t j = 31 + (2 - (-36 * g));
int32_t k = c * 18;
printf("%d\n", -33 / h);;
printf("%d\n", -8 / ((-59 * (e - i)) * g));;
printf("%d\n", b);;
printf("%d\n", h);;
printf("%d\n", 44);;
printf("%d\n", 2 * (b / 82));;
int32_t l = -22;
printf("%d\n", (i / (-38 - (d + k))) * ((-31 * 0) + 32));;
printf("%d\n", l);;
int32_t m = -2;
int32_t n = 33;
printf("%d\n", -36);;
printf("%d\n", f);;
printf("%d\n", (26 * i) / b);;
printf("%d\n", g - (i / -15));;
printf("%d\n", 11);;
printf("%d\n", (-5 + 36) - 19);;
printf("%d\n", m);;
printf("%d\n", l);;
printf("%d\n", ((((6 - (c * j)) / (-13 - -20)) / -21) + -38) - h);;
printf("%d\n", f);;
printf("%d\n", m);;
int32_t o = 78;
printf("%d\n", j);;
printf("%d\n", a / ((-4 / b) + d));;
printf("%d\n", -24);;
printf("%d\n", 19);;
printf("%d\n", 32 / (4 - n));;
int32_t p = b;
printf("%d\n", d + ((p * -24) / (((k * ((i + 12) * (21 / -5))) * p) / -8)));;
printf("%d\n", 9 / d);;
int32_t q = -18;
int32_t r = h + ((-52 - ((k - (-46 - (h + (k - l)))) * a)) * (b / 52));
int32_t s = -43;
printf("%d\n", 3);;
printf("%d\n", c);;
int32_t t = -49 + (20 / 7);
printf("%d\n", -3);;
printf("%d\n", g - -9);;
printf("%d\n", (r - 38) * -88);;
int32_t u = 76 * 75;
printf("%d\n", -35);;
return 0;}