#include <stdint.h>
int main() {
int32_t a = 4;
int32_t b = -52;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", -51 - (a / a));;
printf("%d\n", b - b);;
printf("%d\n", (a - ((a * (a / 11)) * -48)) + (136 / ((48 + (59 * (a - a))) + b)));;
printf("%d\n", a / 23);;
printf("%d\n", a);;
printf("%d\n", -37);;
printf("%d\n", b * 30);;
printf("%d\n", 53);;
printf("%d\n", 31);;
printf("%d\n", a);;
printf("%d\n", -29);;
printf("%d\n", a + 8);;
printf("%d\n", -2);;
printf("%d\n", (a * b) / -20);;
printf("%d\n", a);;
printf("%d\n", b);;
int32_t c = 22 + a;
printf("%d\n", b - a);;
int32_t d = -79;
printf("%d\n", d);;
printf("%d\n", 6 / 85);;
printf("%d\n", 57);;
printf("%d\n", b + (40 / 37));;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", c);;
int32_t e = -8;
printf("%d\n", e);;
int32_t f = 47;
printf("%d\n", -38);;
printf("%d\n", (-21 / f) + d);;
int32_t g = -61;
int32_t h = 68;
printf("%d\n", b);;
printf("%d\n", -39);;
printf("%d\n", -29 + (58 * e));;
printf("%d\n", 6);;
printf("%d\n", h);;
printf("%d\n", (10 - (-39 / e)) / (-3 - a));;
int32_t i = d;
printf("%d\n", h * (-32 + -40));;
printf("%d\n", c);;
printf("%d\n", b + e);;
printf("%d\n", -22);;
printf("%d\n", c);;
printf("%d\n", i);;
int32_t j = (22 - i) / i;
printf("%d\n", 10);;
printf("%d\n", 67);;
printf("%d\n", 39);;
printf("%d\n", -3);;
int32_t k = 10;
printf("%d\n", -37 * c);;
printf("%d\n", c + f);;
printf("%d\n", 39);;
printf("%d\n", 20);;
printf("%d\n", (a / c) - (44 - (b * -35)));;
int32_t l = -28 + k;
printf("%d\n", f);;
printf("%d\n", i);;
printf("%d\n", d + b);;
printf("%d\n", b);;
int32_t m = l;
printf("%d\n", m + -33);;
printf("%d\n", (a * f) / 14);;
printf("%d\n", 24);;
printf("%d\n", m);;
int32_t n = 3;
printf("%d\n", j);;
printf("%d\n", -23 / 12);;
printf("%d\n", g);;
printf("%d\n", d);;
printf("%d\n", 12);;
printf("%d\n", -59 / -8);;
int32_t o = a;
printf("%d\n", d);;
printf("%d\n", -5);;
printf("%d\n", (g / ((42 * m) + (-18 - 5))) - (((d / c) - -40) - m));;
printf("%d\n", e / (c + 0));;
printf("%d\n", k);;
printf("%d\n", -42);;
printf("%d\n", -57);;
printf("%d\n", m - 11);;
int32_t p = e;
printf("%d\n", h);;
printf("%d\n", -8);;
printf("%d\n", l);;
printf("%d\n", -16);;
printf("%d\n", -4);;
printf("%d\n", 17);;
printf("%d\n", 27);;
printf("%d\n", (d - (8 / -19)) * 35);;
printf("%d\n", (c / 11) / ((-73 - -39) + (f / ((30 / p) + (0 + -9)))));;
int32_t q = m;
int32_t r = -44;
printf("%d\n", 48);;
int32_t s = k;
printf("%d\n", -59);;
printf("%d\n", p);;
printf("%d\n", f + ((57 * h) / (e + (90 - -26))));;
printf("%d\n", (-59 + d) + -62);;
int32_t t = s - j;
printf("%d\n", o * (56 * 46));;
printf("%d\n", l);;
printf("%d\n", g);;
int32_t u = c;
printf("%d\n", 3 - (m / (-21 - l)));;
int32_t v = -18;
printf("%d\n", s);;
int32_t w = a * (p - (-13 / ((-29 / -49) + (v * 38))));
printf("%d\n", v);;
printf("%d\n", i);;
printf("%d\n", a);;
printf("%d\n", p);;
int32_t x = 12;
printf("%d\n", 24);;
int32_t y = 53;
int32_t z = o + (c / -47);
int32_t aa = j;
int32_t ab = k / 23;
printf("%d\n", t + i);;
int32_t ac = o + -60;
printf("%d\n", t);;
printf("%d\n", 10);;
printf("%d\n", r * d);;
printf("%d\n", -15);;
printf("%d\n", -33 / j);;
printf("%d\n", ac);;
printf("%d\n", 110);;
printf("%d\n", 33 - 24);;
printf("%d\n", g);;
printf("%d\n", z);;
printf("%d\n", ac);;
printf("%d\n", 44);;
printf("%d\n", -3);;
int32_t ad = -33;
printf("%d\n", -29);;
return 0;}