#include <stdint.h>
int main() {
printf("%d\n", -11 + -20);;
int32_t a = 155;
printf("%d\n", -50);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 11 - (15 / a));;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t b = a;
printf("%d\n", 34);;
int32_t c = b;
printf("%d\n", 16 * a);;
printf("%d\n", a - (a - c));;
printf("%d\n", -26);;
printf("%d\n", -15);;
printf("%d\n", -43);;
printf("%d\n", 25 / a);;
printf("%d\n", (b + b) - -6);;
int32_t d = 29;
printf("%d\n", 7 + c);;
int32_t e = a;
int32_t f = c;
printf("%d\n", e);;
printf("%d\n", d / e);;
printf("%d\n", 67 * (c + 3));;
printf("%d\n", f / ((d / (39 - b)) + f));;
int32_t g = 74 - (18 - (-2 / e));
int32_t h = b / 7;
printf("%d\n", h);;
int32_t i = ((-10 * ((f + -2) / a)) + 52) * 72;
printf("%d\n", d);;
printf("%d\n", -51);;
printf("%d\n", -8);;
printf("%d\n", e);;
printf("%d\n", d);;
printf("%d\n", -55 + h);;
printf("%d\n", -4);;
printf("%d\n", b);;
printf("%d\n", 78);;
printf("%d\n", (-33 + (i / b)) * 20);;
printf("%d\n", i * (-1 + (-27 / e)));;
printf("%d\n", c - d);;
printf("%d\n", 21);;
printf("%d\n", a);;
printf("%d\n", 35);;
printf("%d\n", f + -22);;
printf("%d\n", e);;
printf("%d\n", (a + a) / h);;
printf("%d\n", -44);;
int32_t j = e - i;
printf("%d\n", h);;
int32_t k = -34;
printf("%d\n", b);;
printf("%d\n", -12 + ((f - (44 + 6)) / -79));;
printf("%d\n", g);;
printf("%d\n", f + ((-17 / j) - a));;
printf("%d\n", k);;
printf("%d\n", 12);;
printf("%d\n", 8);;
printf("%d\n", 11);;
printf("%d\n", f);;
printf("%d\n", (d - -43) + (-10 * (14 * 38)));;
int32_t l = -32 * -7;
int32_t m = a;
printf("%d\n", j * f);;
printf("%d\n", -30);;
return 0;}