#include <stdint.h>
int main() {
int32_t a = -34;
printf("%d\n", 20);;
printf("%d\n", a * a);;
int32_t b = 13;
int32_t c = a - -36;
printf("%d\n", 12 + (c / c));;
printf("%d\n", -21);;
printf("%d\n", -60);;
printf("%d\n", a + 51);;
printf("%d\n", -42);;
printf("%d\n", b * (30 + b));;
printf("%d\n", a / ((a + a) / b));;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 47);;
int32_t d = -4 + (c * a);
printf("%d\n", -28);;
printf("%d\n", c);;
int32_t e = (-106 - 17) - a;
printf("%d\n", -18);;
int32_t f = a;
printf("%d\n", f / (d + (36 * ((-113 - a) * b))));;
printf("%d\n", (c + 4) * a);;
int32_t g = ((-26 * c) / 10) / a;
int32_t h = f;
int32_t i = h;
printf("%d\n", 24 * h);;
printf("%d\n", 19);;
printf("%d\n", 53);;
printf("%d\n", c);;
int32_t j = 35;
int32_t k = (e * -51) / f;
printf("%d\n", -18);;
printf("%d\n", 22);;
printf("%d\n", h);;
printf("%d\n", b);;
printf("%d\n", d / -12);;
printf("%d\n", g + (c / i));;
printf("%d\n", e);;
printf("%d\n", 44);;
int32_t l = g;
printf("%d\n", 84);;
return 0;}