#include <stdint.h>
int main() {
printf("%d\n", 13);;
printf("%d\n", 49 / ((((-11 + -61) / -27) - 42) + (6 * ((58 / (-17 - -15)) / -30))));;
printf("%d\n", 3 / 14);;
printf("%d\n", 24);;
printf("%d\n", ((-6 - (25 + -11)) - -40) + 22);;
printf("%d\n", (10 - (-10 + -22)) * 49);;
printf("%d\n", (-27 - 8) / 38);;
int32_t a = -39 * 23;
printf("%d\n", -3);;
printf("%d\n", a / a);;
printf("%d\n", 25);;
printf("%d\n", 33);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 14);;
printf("%d\n", a);;
int32_t b = (a + -1) + (a + 16);
int32_t c = (-20 + a) / -52;
printf("%d\n", 28);;
printf("%d\n", (((a * (c - 45)) - 65) + a) / ((c * c) * 22));;
printf("%d\n", -31);;
printf("%d\n", c);;
printf("%d\n", b);;
printf("%d\n", 18);;
printf("%d\n", (c + 44) + a);;
printf("%d\n", 12);;
int32_t d = b;
printf("%d\n", d * 6);;
int32_t e = (c - (c / 67)) / d;
printf("%d\n", d + ((a - -3) * -34));;
printf("%d\n", 7);;
printf("%d\n", 25);;
printf("%d\n", b);;
printf("%d\n", -8);;
printf("%d\n", c - 60);;
int32_t f = 34;
printf("%d\n", 4);;
printf("%d\n", (-10 - (d / c)) - ((c - c) * 3));;
printf("%d\n", c);;
printf("%d\n", f);;
printf("%d\n", 34);;
printf("%d\n", c);;
int32_t g = -10 * f;
printf("%d\n", c * 42);;
printf("%d\n", 22);;
printf("%d\n", b);;
printf("%d\n", -55);;
printf("%d\n", 108);;
printf("%d\n", 2);;
printf("%d\n", 29);;
printf("%d\n", 28);;
int32_t h = b;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", -22);;
printf("%d\n", b);;
printf("%d\n", e - (16 + (b + -24)));;
printf("%d\n", -45);;
int32_t i = ((g - f) / d) - (16 * ((c * -29) * (b / 1)));
int32_t j = f;
printf("%d\n", -38);;
printf("%d\n", (-18 * 11) + c);;
printf("%d\n", b);;
printf("%d\n", -9);;
int32_t k = j;
int32_t l = c;
printf("%d\n", 63);;
printf("%d\n", -39);;
int32_t m = 0;
int32_t n = j;
printf("%d\n", 5 + (((h / -79) * i) + 31));;
int32_t o = g;
printf("%d\n", 3 + (a - (48 * b)));;
int32_t p = 61 + ((-18 - (e + -54)) * (-26 * (((((i + i) + -12) / -11) + -14) * c)));
printf("%d\n", 19);;
printf("%d\n", 11);;
printf("%d\n", 86);;
printf("%d\n", 2);;
printf("%d\n", -27 + k);;
printf("%d\n", 5);;
printf("%d\n", 2 / (o * -2));;
int32_t q = j;
printf("%d\n", a);;
int32_t r = b;
printf("%d\n", -61);;
int32_t s = 21 - (b - q);
printf("%d\n", b);;
printf("%d\n", a + b);;
printf("%d\n", j);;
printf("%d\n", q);;
printf("%d\n", (k - -31) + b);;
int32_t t = (((-15 - e) / q) - (c * 31)) * 14;
int32_t u = -11;
int32_t v = ((-48 + 34) - -53) - ((-12 + h) + m);
int32_t w = p;
printf("%d\n", a);;
printf("%d\n", -3);;
printf("%d\n", ((g + m) + 38) / -69);;
int32_t x = g;
int32_t y = h;
int32_t z = 14;
printf("%d\n", -5);;
printf("%d\n", z);;
printf("%d\n", j);;
printf("%d\n", t);;
printf("%d\n", x);;
int32_t aa = (-64 / 30) * -30;
printf("%d\n", -19);;
int32_t ab = 14;
printf("%d\n", (46 / (-7 + (v / l))) - r);;
int32_t ac = d;
return 0;}