#include <stdint.h>
int main() {
int32_t a = (17 + ((-31 / 71) - (-22 / -46))) + 15;
int32_t b = -27;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 73);;
printf("%d\n", b);;
printf("%d\n", 26 / b);;
printf("%d\n", b);;
printf("%d\n", -4);;
printf("%d\n", 3 + -59);;
printf("%d\n", 12);;
int32_t c = a;
printf("%d\n", 15);;
printf("%d\n", a * b);;
int32_t d = -25 + 4;
printf("%d\n", 55);;
int32_t e = -60;
printf("%d\n", (((5 * a) - (49 - (((c - (b + e)) + d) * a))) - d) * 2);;
int32_t f = e;
printf("%d\n", a);;
int32_t g = 31;
printf("%d\n", e);;
printf("%d\n", 48);;
printf("%d\n", -46);;
printf("%d\n", f);;
int32_t h = b;
printf("%d\n", -46);;
printf("%d\n", -21);;
printf("%d\n", g - c);;
printf("%d\n", (-19 / -45) / 26);;
int32_t i = -20;
int32_t j = a - (a / -19);
printf("%d\n", b);;
printf("%d\n", g * (j - 16));;
printf("%d\n", c);;
printf("%d\n", i);;
int32_t k = d;
printf("%d\n", g);;
printf("%d\n", e);;
printf("%d\n", a);;
int32_t l = (f / g) / -44;
printf("%d\n", -12);;
printf("%d\n", c);;
printf("%d\n", -17 / f);;
int32_t m = e + (((g * -9) * i) + d);
int32_t n = -38;
printf("%d\n", -12);;
printf("%d\n", -9);;
printf("%d\n", k);;
printf("%d\n", 4);;
printf("%d\n", 21);;
printf("%d\n", 4);;
printf("%d\n", 15);;
printf("%d\n", d);;
int32_t o = a - d;
int32_t p = 4;
int32_t q = 63;
printf("%d\n", 6);;
printf("%d\n", (p / j) + 60);;
int32_t r = 120 - p;
printf("%d\n", f);;
printf("%d\n", 27);;
printf("%d\n", n);;
printf("%d\n", 4 * b);;
int32_t s = f;
printf("%d\n", i);;
printf("%d\n", 58);;
printf("%d\n", -13);;
int32_t t = q - -27;
int32_t u = -26 + e;
printf("%d\n", 4 * (-11 - 82));;
int32_t v = q;
printf("%d\n", k);;
printf("%d\n", 20);;
printf("%d\n", -1);;
printf("%d\n", 35);;
printf("%d\n", -8 * k);;
int32_t w = h;
printf("%d\n", u);;
printf("%d\n", t);;
printf("%d\n", m);;
printf("%d\n", f / ((35 / s) + -3));;
printf("%d\n", 46 * (p / 35));;
printf("%d\n", (8 * j) - (b * (-1 + m)));;
printf("%d\n", f);;
int32_t x = 80;
printf("%d\n", s);;
printf("%d\n", -16);;
int32_t y = -92;
printf("%d\n", -12 + r);;
printf("%d\n", e);;
printf("%d\n", 16);;
printf("%d\n", r - t);;
printf("%d\n", p);;
int32_t z = 46;
printf("%d\n", o * (m / (12 * (-8 - i))));;
printf("%d\n", (g * -64) + ((l * y) - z));;
int32_t aa = 16;
printf("%d\n", u);;
printf("%d\n", e);;
printf("%d\n", -17);;
int32_t ab = 57;
printf("%d\n", r);;
printf("%d\n", 54);;
printf("%d\n", l);;
printf("%d\n", -89 - (r / 19));;
printf("%d\n", 44);;
printf("%d\n", 32);;
int32_t ac = k;
printf("%d\n", k);;
printf("%d\n", s * 3);;
int32_t ad = 81;
int32_t ae = 12;
printf("%d\n", 7);;
int32_t af = -18 / 7;
printf("%d\n", -20);;
printf("%d\n", -3 * (k / -24));;
return 0;}