#include <stdint.h>
int main() {
int32_t a = 21;
printf("%d\n", a);;
printf("%d\n", 42);;
printf("%d\n", a * (-41 + 29));;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", -5);;
int32_t b = ((-47 * 38) * (-7 - -23)) + a;
int32_t c = a;
printf("%d\n", -4);;
printf("%d\n", b);;
printf("%d\n", c);;
printf("%d\n", 12 - (-16 + -55));;
int32_t d = -28;
printf("%d\n", 16);;
printf("%d\n", -16);;
int32_t e = c;
printf("%d\n", 91);;
printf("%d\n", 105);;
int32_t f = (48 - 21) - e;
printf("%d\n", c * d);;
printf("%d\n", 25);;
printf("%d\n", ((b + (d * d)) / f) / (a - -59));;
printf("%d\n", 63);;
int32_t g = f;
int32_t h = a;
printf("%d\n", -48);;
int32_t i = (-21 / -38) + -58;
printf("%d\n", 48);;
int32_t j = 94;
printf("%d\n", b);;
int32_t k = 40 / 30;
printf("%d\n", 12);;
printf("%d\n", e);;
int32_t l = 47;
printf("%d\n", j);;
printf("%d\n", 93);;
printf("%d\n", 68);;
int32_t m = 90 - (-15 + f);
printf("%d\n", d);;
printf("%d\n", l * -22);;
printf("%d\n", k + -26);;
printf("%d\n", b);;
printf("%d\n", e);;
int32_t n = -15;
int32_t o = -41 * l;
printf("%d\n", i + 2);;
int32_t p = -3 + i;
printf("%d\n", (48 + (11 / p)) - -25);;
printf("%d\n", 40);;
printf("%d\n", 94);;
int32_t q = -12 - p;
printf("%d\n", 40);;
printf("%d\n", o);;
printf("%d\n", l);;
printf("%d\n", 0);;
printf("%d\n", 64);;
printf("%d\n", m / (-27 + (c / b)));;
printf("%d\n", n);;
return 0;}