#include <stdint.h>
int main() {
printf("%d\n", 30 / (-28 + 26));;
printf("%d\n", -15 - -45);;
int32_t a = -52;
printf("%d\n", a);;
printf("%d\n", (a * (-8 - -8)) / -4);;
printf("%d\n", -18 * a);;
printf("%d\n", 56);;
int32_t b = a * -31;
int32_t c = b;
int32_t d = 47;
printf("%d\n", c);;
int32_t e = (b / -11) + d;
int32_t f = c;
printf("%d\n", -22);;
printf("%d\n", 4);;
printf("%d\n", -16);;
printf("%d\n", 14);;
int32_t g = d;
printf("%d\n", d);;
printf("%d\n", -14 / c);;
printf("%d\n", 19);;
printf("%d\n", -16);;
printf("%d\n", e);;
int32_t h = e;
printf("%d\n", f + (13 * ((d + 34) + (20 - a))));;
printf("%d\n", (-60 * (-1 + ((1 - ((f * 83) * f)) * 51))) / -5);;
printf("%d\n", -41);;
printf("%d\n", 52);;
printf("%d\n", e);;
printf("%d\n", -12 * b);;
printf("%d\n", 32 + ((g - 42) * 15));;
printf("%d\n", -75);;
printf("%d\n", a);;
int32_t i = -13;
printf("%d\n", (b - c) - b);;
printf("%d\n", ((g + 100) - 12) + g);;
int32_t j = 78 - -5;
printf("%d\n", a);;
printf("%d\n", 24 - g);;
printf("%d\n", e);;
printf("%d\n", 56);;
printf("%d\n", -2);;
printf("%d\n", j);;
printf("%d\n", -52);;
printf("%d\n", -63);;
printf("%d\n", 2);;
printf("%d\n", e);;
printf("%d\n", j + (((g + i) - (-37 + g)) - i));;
printf("%d\n", (12 * -6) - -28);;
printf("%d\n", 20);;
int32_t k = 5;
printf("%d\n", k);;
printf("%d\n", -27 + 55);;
printf("%d\n", 57);;
printf("%d\n", ((d + ((41 / ((29 * (g / i)) - -12)) * 34)) - (k * (-77 - i))) - f);;
printf("%d\n", i);;
printf("%d\n", -50);;
printf("%d\n", -69);;
printf("%d\n", 21 * (64 / -18));;
printf("%d\n", d);;
printf("%d\n", h);;
int32_t l = e;
printf("%d\n", b);;
printf("%d\n", (-16 - (k + 74)) + f);;
int32_t m = h;
printf("%d\n", d - (((c * 14) - a) * (h - 47)));;
int32_t n = e;
printf("%d\n", 9);;
int32_t o = b;
printf("%d\n", -24);;
int32_t p = f;
printf("%d\n", c);;
printf("%d\n", (l - o) * (b + m));;
printf("%d\n", (42 + k) * 31);;
int32_t q = 2;
int32_t r = (47 * ((23 / (e * ((-2 * c) * ((-68 / d) - 74)))) * (18 + 32))) * (q + k);
printf("%d\n", p);;
return 0;}