#include <stdint.h>
int main() {
int32_t a = -5 + -87;
printf("%d\n", -35);;
printf("%d\n", 54);;
int32_t b = a;
int32_t c = -38;
printf("%d\n", -32);;
printf("%d\n", (80 + b) - -8);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", 28);;
int32_t d = a;
printf("%d\n", (25 + b) * -49);;
printf("%d\n", 79 - -36);;
printf("%d\n", a);;
printf("%d\n", (60 - 33) - b);;
printf("%d\n", -38);;
printf("%d\n", 11 / (35 + 32));;
printf("%d\n", 10 * b);;
printf("%d\n", -24 * -19);;
printf("%d\n", (-20 - -51) * (57 / -15));;
printf("%d\n", 72);;
printf("%d\n", b);;
int32_t e = -113;
int32_t f = -50;
printf("%d\n", 18);;
printf("%d\n", d / ((b + -20) / 37));;
printf("%d\n", 20);;
printf("%d\n", -12);;
int32_t g = -41;
int32_t h = 45;
int32_t i = (((e * 41) + d) - -56) / f;
printf("%d\n", e * 15);;
printf("%d\n", 9);;
int32_t j = f;
printf("%d\n", 7);;
printf("%d\n", d);;
int32_t k = i / b;
printf("%d\n", -22);;
printf("%d\n", -3);;
printf("%d\n", h);;
int32_t l = -75;
int32_t m = 35;
printf("%d\n", b);;
int32_t n = 46;
int32_t o = a - l;
printf("%d\n", (j * 42) - -40);;
printf("%d\n", j * 83);;
int32_t p = ((11 * d) + 27) + (19 - (h + d));
printf("%d\n", -10 + (70 - k));;
int32_t q = 5;
printf("%d\n", j);;
printf("%d\n", 27);;
printf("%d\n", (9 - (f / (l - ((52 + 48) + -57)))) - d);;
printf("%d\n", -30 - (8 / 28));;
printf("%d\n", o);;
printf("%d\n", (m - 24) * 13);;
printf("%d\n", -1);;
printf("%d\n", m);;
printf("%d\n", g / a);;
printf("%d\n", q - -26);;
printf("%d\n", 30);;
printf("%d\n", 39 * -8);;
printf("%d\n", -21);;
printf("%d\n", f);;
printf("%d\n", p * h);;
printf("%d\n", 14);;
printf("%d\n", f * (32 / a));;
printf("%d\n", (a + q) - ((((-12 - (n * m)) / o) - -3) / 91));;
printf("%d\n", a);;
printf("%d\n", q);;
printf("%d\n", n);;
printf("%d\n", -12);;
printf("%d\n", m);;
int32_t r = c;
int32_t s = -6;
printf("%d\n", ((1 * (0 * (8 / m))) * (((o * (33 - (r / -1))) + (l + 3)) + n)) - (61 / l));;
int32_t t = (19 * (52 * -2)) + (((-45 - (65 + e)) / r) * 60);
printf("%d\n", d);;
int32_t u = 24;
int32_t v = 55;
printf("%d\n", ((k * o) / l) + 18);;
int32_t w = u;
printf("%d\n", o + r);;
printf("%d\n", -5);;
printf("%d\n", p * 22);;
printf("%d\n", 10 + (a * (m - (e / -10))));;
printf("%d\n", -83);;
printf("%d\n", n);;
printf("%d\n", 23 / c);;
printf("%d\n", g);;
printf("%d\n", 64);;
printf("%d\n", 66);;
printf("%d\n", k);;
printf("%d\n", (-72 + w) - 1);;
printf("%d\n", -53);;
int32_t x = j;
printf("%d\n", q);;
printf("%d\n", c * (r - c));;
printf("%d\n", 47);;
printf("%d\n", r);;
printf("%d\n", -30);;
printf("%d\n", j);;
printf("%d\n", d);;
int32_t y = 17 * 79;
printf("%d\n", 34);;
int32_t z = (22 * ((d - (f - -36)) * (s + b))) + (((8 - (-4 / r)) * -60) / -17);
printf("%d\n", -7 + c);;
printf("%d\n", o * 72);;
printf("%d\n", (t / (-37 + s)) * 35);;
printf("%d\n", ((17 + e) * -43) / -54);;
int32_t aa = e;
printf("%d\n", 12);;
printf("%d\n", 47 / c);;
printf("%d\n", 19 / -69);;
int32_t ab = 5;
int32_t ac = -128;
printf("%d\n", c);;
printf("%d\n", ((((-1 + (((l + (-35 / m)) / g) - aa)) - k) / 1) + w) / (ac / -73));;
printf("%d\n", r * w);;
printf("%d\n", t);;
printf("%d\n", k + (-37 + z));;
printf("%d\n", 26);;
printf("%d\n", c);;
int32_t ad = u;
return 0;}