#include <stdint.h>
int main() {
int32_t a = -14;
printf("%d\n", 39);;
printf("%d\n", a);;
int32_t b = -1;
printf("%d\n", -1);;
int32_t c = (-46 - a) * (b + -75);
printf("%d\n", 12);;
printf("%d\n", c - ((47 * a) * 55));;
int32_t d = 2;
printf("%d\n", 63 + (b - a));;
printf("%d\n", 27 - (-46 * (-18 * b)));;
printf("%d\n", d);;
printf("%d\n", (-16 * a) * 66);;
printf("%d\n", 39);;
printf("%d\n", -35);;
printf("%d\n", b);;
printf("%d\n", -6 * c);;
printf("%d\n", d);;
printf("%d\n", d + 39);;
printf("%d\n", -14);;
printf("%d\n", -11);;
printf("%d\n", (((35 - ((63 * 26) * -1)) * b) - d) * (b - (-48 + 56)));;
printf("%d\n", d * -68);;
printf("%d\n", (d / 9) / (-44 - -3));;
printf("%d\n", 65);;
printf("%d\n", d);;
printf("%d\n", 60 * -34);;
printf("%d\n", c - -28);;
printf("%d\n", b / c);;
int32_t e = -11;
printf("%d\n", 26);;
int32_t f = 78;
printf("%d\n", -41);;
int32_t g = 12;
printf("%d\n", f);;
printf("%d\n", 5);;
int32_t h = d;
printf("%d\n", a);;
int32_t i = d * -27;
printf("%d\n", 7);;
printf("%d\n", b);;
printf("%d\n", -38 * -3);;
printf("%d\n", d);;
int32_t j = 19;
printf("%d\n", -105);;
printf("%d\n", f + ((16 / -12) / e));;
printf("%d\n", (-8 * (-9 + (48 / e))) + 28);;
int32_t k = 37;
printf("%d\n", g);;
printf("%d\n", 67);;
printf("%d\n", g);;
printf("%d\n", 5);;
printf("%d\n", k);;
printf("%d\n", -52);;
printf("%d\n", d * 59);;
printf("%d\n", -12);;
printf("%d\n", 74 + e);;
printf("%d\n", -27);;
printf("%d\n", k);;
printf("%d\n", a / d);;
int32_t l = -3;
printf("%d\n", d);;
int32_t m = 50;
printf("%d\n", -6);;
int32_t n = i;
printf("%d\n", -49);;
int32_t o = (a - ((81 / f) * 26)) / (-38 + ((g * 19) - b));
printf("%d\n", 83 + (-25 + (67 + o)));;
printf("%d\n", 10);;
printf("%d\n", j);;
int32_t p = 133;
printf("%d\n", -27);;
return 0;}