#include <stdint.h>
int main() {
int32_t a = (59 * (-10 + 21)) - (-40 / 58);
int32_t b = a;
printf("%d\n", 46 + ((-4 / (b / ((b / b) * b))) - ((a - ((-40 * b) * -2)) + b)));;
printf("%d\n", (-59 - 8) * a);;
printf("%d\n", -27);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", b - (((-43 * a) - (-6 / b)) - a));;
printf("%d\n", -39 - (46 * a));;
printf("%d\n", -12);;
printf("%d\n", b * (a / a));;
printf("%d\n", 17 + a);;
printf("%d\n", b + (b - 1));;
printf("%d\n", -35 + a);;
printf("%d\n", -84);;
int32_t c = (-3 - 4) / -15;
printf("%d\n", c);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", -7 / -33);;
printf("%d\n", 24);;
printf("%d\n", 9);;
int32_t d = 17 / -68;
int32_t e = c + (32 * a);
int32_t f = d;
printf("%d\n", e);;
int32_t g = a;
int32_t h = 51;
printf("%d\n", -11 + (f * c));;
printf("%d\n", f);;
printf("%d\n", ((c / e) - (-24 / (b * 62))) - b);;
int32_t i = b;
printf("%d\n", g);;
printf("%d\n", 3);;
int32_t j = ((h / -10) * -71) - (c * b);
printf("%d\n", e);;
printf("%d\n", (40 + ((b * 44) * 27)) / 27);;
printf("%d\n", -8);;
printf("%d\n", a);;
printf("%d\n", -23 + 37);;
printf("%d\n", -4);;
printf("%d\n", i * -44);;
int32_t k = 52;
printf("%d\n", f);;
printf("%d\n", h - ((((a * (13 / ((-15 + -6) - ((-4 / 43) + -6)))) / h) * -42) * i));;
printf("%d\n", 7 * b);;
printf("%d\n", -81);;
printf("%d\n", a);;
printf("%d\n", h);;
printf("%d\n", i);;
printf("%d\n", a);;
printf("%d\n", 7);;
printf("%d\n", (a - 24) + 52);;
int32_t l = 6;
int32_t m = l;
int32_t n = 21;
printf("%d\n", (n - b) + 54);;
printf("%d\n", b);;
printf("%d\n", 60);;
int32_t o = 8;
int32_t p = b + 27;
int32_t q = p * -65;
printf("%d\n", -30 - (i / (30 + (g + (-32 + 43)))));;
printf("%d\n", 44 - l);;
printf("%d\n", -13 * n);;
int32_t r = c;
printf("%d\n", -10);;
printf("%d\n", p);;
int32_t s = o * (h * 55);
printf("%d\n", -10);;
printf("%d\n", b);;
return 0;}