#include <stdint.h>
int main() {
int32_t a = (61 - (-6 * 47)) * 46;
printf("%d\n", a / 26);;
int32_t b = ((a - a) * a) * ((27 * a) * ((a - a) + a));
printf("%d\n", 41);;
printf("%d\n", 9);;
int32_t c = -51;
int32_t d = 15;
printf("%d\n", 51);;
printf("%d\n", d - -8);;
printf("%d\n", (a - (-42 + (76 / (45 - (a + c))))) / c);;
printf("%d\n", 44 - b);;
printf("%d\n", b);;
printf("%d\n", -3);;
printf("%d\n", -69 + b);;
printf("%d\n", a);;
printf("%d\n", -37 + 40);;
printf("%d\n", b);;
printf("%d\n", a - d);;
printf("%d\n", d);;
printf("%d\n", d);;
printf("%d\n", -56);;
printf("%d\n", 23);;
printf("%d\n", -9);;
printf("%d\n", c);;
printf("%d\n", a * 24);;
printf("%d\n", d / -15);;
int32_t e = (d * c) * c;
printf("%d\n", d);;
printf("%d\n", 23);;
printf("%d\n", e + b);;
printf("%d\n", e / (((60 * (c - ((-11 + e) / -40))) + (c * 3)) - e));;
int32_t f = -16;
printf("%d\n", -26);;
printf("%d\n", 0);;
printf("%d\n", f + ((a + ((((23 * f) + 58) - a) / a)) * b));;
printf("%d\n", -23);;
printf("%d\n", a);;
printf("%d\n", 20 - 25);;
int32_t g = 22 - c;
int32_t h = 4;
int32_t i = 26;
int32_t j = 60;
printf("%d\n", 30 / 20);;
printf("%d\n", -15);;
printf("%d\n", h);;
printf("%d\n", f);;
int32_t k = j;
int32_t l = k;
int32_t m = c / (l - (e + 47));
printf("%d\n", ((5 / (b - l)) / 12) + 10);;
printf("%d\n", e * -16);;
printf("%d\n", i);;
int32_t n = h;
printf("%d\n", -27 + ((g - 71) + (((-2 / (-56 - k)) * j) / -33)));;
printf("%d\n", k * ((((26 - (-88 / j)) + 39) * (i - a)) * (30 + -10)));;
printf("%d\n", -11);;
int32_t o = -3;
int32_t p = 60;
printf("%d\n", 70);;
printf("%d\n", ((17 - m) + o) * -11);;
int32_t q = 29 - (l - (-28 - h));
printf("%d\n", 0);;
int32_t r = 15;
printf("%d\n", -10);;
return 0;}