#include <stdint.h>
int main() {
int32_t a = (32 + (31 + (-5 - 12))) + -4;
int32_t b = ((40 + 14) * a) + 39;
printf("%d\n", -8);;
printf("%d\n", 36);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", -65);;
printf("%d\n", b);;
int32_t c = a * a;
printf("%d\n", b);;
printf("%d\n", 22);;
printf("%d\n", 22);;
printf("%d\n", -41);;
printf("%d\n", 56);;
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t d = a + ((-47 / ((52 / -11) + (a + a))) - (b * (c - c)));
printf("%d\n", 48 / b);;
printf("%d\n", (d / 95) - 45);;
int32_t e = a;
printf("%d\n", 37);;
printf("%d\n", b);;
printf("%d\n", d - 15);;
int32_t f = -28 * -29;
int32_t g = 24;
int32_t h = -60;
int32_t i = -64;
printf("%d\n", ((((h * -4) * (e / h)) * 30) * (i / c)) + 13);;
int32_t j = 20 * g;
printf("%d\n", 70 - -31);;
printf("%d\n", f);;
printf("%d\n", a);;
printf("%d\n", (d + -27) + i);;
printf("%d\n", j);;
printf("%d\n", 3);;
printf("%d\n", 26 + j);;
printf("%d\n", -2);;
printf("%d\n", i / 37);;
printf("%d\n", 16);;
printf("%d\n", (f - 44) + -18);;
printf("%d\n", 3);;
int32_t k = 14;
printf("%d\n", 29);;
printf("%d\n", f);;
printf("%d\n", h);;
int32_t l = c;
printf("%d\n", 33 - e);;
int32_t m = c;
printf("%d\n", -67);;
int32_t n = -31;
int32_t o = -55;
printf("%d\n", 1 * (3 + o));;
printf("%d\n", 21);;
int32_t p = -27;
printf("%d\n", o);;
int32_t q = 37 * 35;
printf("%d\n", e);;
printf("%d\n", 42);;
printf("%d\n", -29);;
printf("%d\n", d);;
printf("%d\n", d + 44);;
printf("%d\n", 102 + e);;
int32_t r = 14;
int32_t s = 8;
printf("%d\n", a / g);;
printf("%d\n", 6);;
printf("%d\n", 20 + 32);;
int32_t t = (i / (j + 11)) * -24;
printf("%d\n", -7);;
printf("%d\n", 22);;
printf("%d\n", 11);;
printf("%d\n", 0);;
int32_t u = j / 59;
int32_t v = e;
int32_t w = -20;
printf("%d\n", c);;
printf("%d\n", (t - 38) * p);;
printf("%d\n", 25 / n);;
printf("%d\n", g);;
printf("%d\n", -17 - g);;
printf("%d\n", -48 - (g - -7));;
return 0;}