#include <stdint.h>
int main() {
printf("%d\n", 7);;
int32_t a = -30 + ((60 * (-14 * -1)) - 1);
printf("%d\n", a);;
printf("%d\n", 61);;
int32_t b = 37;
printf("%d\n", 13);;
printf("%d\n", 10);;
printf("%d\n", 82);;
printf("%d\n", a);;
printf("%d\n", b / b);;
printf("%d\n", 22);;
printf("%d\n", (b - (b + 26)) - -36);;
printf("%d\n", 50);;
printf("%d\n", b);;
printf("%d\n", a);;
int32_t c = -28 * b;
printf("%d\n", 64);;
printf("%d\n", c);;
printf("%d\n", 76);;
printf("%d\n", b * -44);;
printf("%d\n", (b + a) + b);;
int32_t d = (23 - (-49 - -19)) + -50;
printf("%d\n", d / ((b / d) + (d / -30)));;
printf("%d\n", -31 * ((-6 * 56) + -8));;
int32_t e = c;
printf("%d\n", (10 / -28) - -13);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 85);;
printf("%d\n", -9 + (24 / -39));;
printf("%d\n", 73 - e);;
printf("%d\n", 1 * b);;
printf("%d\n", 2 - e);;
printf("%d\n", -22);;
printf("%d\n", e);;
printf("%d\n", 2 * d);;
printf("%d\n", ((e / 41) + d) / a);;
printf("%d\n", c);;
printf("%d\n", 89 + 7);;
printf("%d\n", a);;
printf("%d\n", e);;
printf("%d\n", d);;
printf("%d\n", -49);;
int32_t f = e;
printf("%d\n", d);;
printf("%d\n", 23);;
printf("%d\n", 50);;
printf("%d\n", 20);;
printf("%d\n", 31);;
printf("%d\n", (-30 / -11) / e);;
printf("%d\n", 31);;
printf("%d\n", 50 + e);;
printf("%d\n", 63);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", -20);;
printf("%d\n", 36 * 22);;
printf("%d\n", b - f);;
printf("%d\n", b);;
printf("%d\n", 19);;
printf("%d\n", -2);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", 51 - (e + 19));;
int32_t g = 0;
printf("%d\n", e + f);;
printf("%d\n", g);;
printf("%d\n", 29);;
printf("%d\n", d / (5 + f));;
printf("%d\n", g);;
printf("%d\n", 9 * g);;
printf("%d\n", f);;
printf("%d\n", 27);;
printf("%d\n", -36);;
return 0;}