#include <stdint.h>
int main() {
printf("%d\n", 47 + -91);;
printf("%d\n", 31 / 34);;
printf("%d\n", 28 + 94);;
printf("%d\n", (((((-76 * ((63 - 44) + 6)) / 28) - -46) * -1) - ((19 / 60) - (-21 + 14))) / -76);;
printf("%d\n", (57 - 67) + ((63 - 21) / 34));;
printf("%d\n", -11);;
int32_t a = 5 + 38;
printf("%d\n", a);;
printf("%d\n", (((((22 + 25) + a) + a) - (5 - a)) - 28) / a);;
int32_t b = 72;
printf("%d\n", a * 76);;
printf("%d\n", -14);;
printf("%d\n", 74);;
printf("%d\n", -3);;
printf("%d\n", a);;
int32_t c = b;
printf("%d\n", 25 - c);;
printf("%d\n", -38);;
printf("%d\n", (c / -12) / a);;
printf("%d\n", 2);;
printf("%d\n", (b + c) - c);;
printf("%d\n", c);;
printf("%d\n", a + c);;
printf("%d\n", b * (c / (c - (47 + b))));;
int32_t d = 57;
int32_t e = b;
printf("%d\n", b * c);;
printf("%d\n", b / (c / -3));;
int32_t f = -17;
printf("%d\n", -16 * 45);;
printf("%d\n", -29);;
printf("%d\n", -9 * (-91 + 49));;
int32_t g = -19;
int32_t h = 35;
int32_t i = d * g;
printf("%d\n", i);;
int32_t j = 4;
printf("%d\n", (-21 * j) + g);;
printf("%d\n", e);;
printf("%d\n", -2);;
int32_t k = j;
printf("%d\n", 75);;
int32_t l = 9;
printf("%d\n", l);;
printf("%d\n", -76);;
printf("%d\n", k);;
int32_t m = 35;
printf("%d\n", f - (10 / -55));;
printf("%d\n", 55);;
int32_t n = -63;
int32_t o = k;
printf("%d\n", b);;
int32_t p = j;
int32_t q = h;
printf("%d\n", 32 + (o + (-105 * ((((6 - q) - p) - 28) + ((m - (1 - 113)) + 14)))));;
int32_t r = b;
printf("%d\n", -24);;
int32_t s = g;
printf("%d\n", -47);;
printf("%d\n", h);;
printf("%d\n", 27);;
printf("%d\n", e);;
printf("%d\n", (22 * (r + -25)) / -12);;
printf("%d\n", n);;
printf("%d\n", (-11 - (r - -88)) / g);;
printf("%d\n", 14);;
printf("%d\n", 49);;
int32_t t = 76;
printf("%d\n", (p - h) / a);;
printf("%d\n", k - (i / i));;
printf("%d\n", 53 + d);;
int32_t u = 35;
int32_t v = t - a;
printf("%d\n", i);;
int32_t w = 9;
int32_t x = u;
int32_t y = 30 / -29;
printf("%d\n", 23 / 74);;
int32_t z = 39;
printf("%d\n", -6);;
printf("%d\n", n);;
printf("%d\n", -19);;
printf("%d\n", 7 * a);;
int32_t aa = 37;
printf("%d\n", -6);;
printf("%d\n", 34);;
printf("%d\n", -17 * (-6 + -68));;
printf("%d\n", 52);;
printf("%d\n", c);;
int32_t ab = ((n / (-39 + (0 + (-15 - d)))) + ((e - 46) * b)) - (q / 26);
int32_t ac = p;
printf("%d\n", 66);;
printf("%d\n", d);;
int32_t ad = r;
int32_t ae = y;
int32_t af = 28 - l;
int32_t ag = w / h;
printf("%d\n", 56);;
int32_t ah = -15;
printf("%d\n", k - n);;
printf("%d\n", l + 31);;
printf("%d\n", q);;
printf("%d\n", 24);;
printf("%d\n", h);;
printf("%d\n", v);;
printf("%d\n", ac);;
printf("%d\n", l);;
int32_t ai = (ah - (ah * u)) * j;
printf("%d\n", 38);;
printf("%d\n", (ag / (-10 + c)) / (14 + (f * (e / (e - 25)))));;
printf("%d\n", aa);;
printf("%d\n", s);;
printf("%d\n", ai + 38);;
int32_t aj = -45;
printf("%d\n", l);;
int32_t ak = 7;
printf("%d\n", f / ((19 / aa) + (v + 38)));;
printf("%d\n", ac - j);;
printf("%d\n", 21);;
int32_t al = v * 13;
printf("%d\n", 16);;
int32_t am = ((s / ac) + u) * q;
printf("%d\n", 43);;
printf("%d\n", e);;
printf("%d\n", ae);;
printf("%d\n", l);;
printf("%d\n", am);;
printf("%d\n", f);;
int32_t an = 40;
printf("%d\n", ((k - (((((-26 * 49) + d) / (11 - ((ai - -9) * (-3 * (e * 13))))) * -49) / -83)) + ((24 + (64 / h)) + 47)) - (d / (af - 82)));;
int32_t ao = ak;
printf("%d\n", 40);;
printf("%d\n", ab / ((aj * (7 * x)) + f));;
printf("%d\n", ((-34 + (g * x)) - k) * (ab * z));;
printf("%d\n", -10);;
printf("%d\n", -47);;
printf("%d\n", -28);;
printf("%d\n", v - u);;
int32_t ap = o;
int32_t aq = 32 / ap;
printf("%d\n", 30);;
printf("%d\n", ao);;
printf("%d\n", ac);;
int32_t ar = 3;
printf("%d\n", p);;
printf("%d\n", i);;
printf("%d\n", ab / -56);;
printf("%d\n", h);;
printf("%d\n", -12 - -61);;
printf("%d\n", ac);;
printf("%d\n", -5 - i);;
printf("%d\n", 53);;
printf("%d\n", ae);;
printf("%d\n", l);;
return 0;}