#include <stdint.h>
int main() {
int32_t a = 16;
printf("%d\n", a + a);;
printf("%d\n", 0);;
printf("%d\n", 45 / a);;
printf("%d\n", a);;
printf("%d\n", 8 + 19);;
printf("%d\n", 16);;
int32_t b = 6;
printf("%d\n", 20);;
printf("%d\n", -29);;
printf("%d\n", a * a);;
printf("%d\n", 14);;
printf("%d\n", (a - b) + a);;
printf("%d\n", 115);;
int32_t c = 7;
int32_t d = -30;
int32_t e = 9;
printf("%d\n", a);;
printf("%d\n", 0);;
printf("%d\n", 42);;
printf("%d\n", b / 19);;
printf("%d\n", 26);;
printf("%d\n", -33);;
printf("%d\n", c + 2);;
printf("%d\n", 52);;
int32_t f = ((d * -16) - (42 - b)) / ((28 * 16) + 21);
printf("%d\n", 23);;
printf("%d\n", 68);;
printf("%d\n", (a + 26) - (20 - c));;
int32_t g = e;
printf("%d\n", b);;
printf("%d\n", 28);;
printf("%d\n", -31);;
printf("%d\n", d * -84);;
printf("%d\n", -42);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", 18);;
printf("%d\n", c);;
printf("%d\n", e / (c - 83));;
printf("%d\n", c);;
printf("%d\n", g);;
printf("%d\n", -17);;
printf("%d\n", 72);;
printf("%d\n", 54);;
int32_t h = 7;
printf("%d\n", e);;
printf("%d\n", a);;
printf("%d\n", e * -56);;
printf("%d\n", (g + -102) - g);;
printf("%d\n", g / -46);;
int32_t i = c;
int32_t j = -3;
printf("%d\n", j);;
printf("%d\n", 48);;
printf("%d\n", a);;
printf("%d\n", f / ((21 / (((-35 + i) + -14) * 24)) + a));;
printf("%d\n", 29);;
printf("%d\n", 28);;
printf("%d\n", a);;
printf("%d\n", 82);;
return 0;}