#include <stdint.h>
int main() {
printf("%d\n", 27 + 47);;
int32_t a = 22 - (18 / -25);
printf("%d\n", a);;
printf("%d\n", -26);;
int32_t b = 37;
printf("%d\n", a);;
printf("%d\n", 50 + -28);;
printf("%d\n", -8 / a);;
printf("%d\n", 2);;
int32_t c = a;
printf("%d\n", a);;
printf("%d\n", b);;
int32_t d = 66;
printf("%d\n", 23);;
printf("%d\n", 5);;
printf("%d\n", 70);;
int32_t e = b;
int32_t f = 115;
printf("%d\n", 71);;
printf("%d\n", a * e);;
int32_t g = 32;
printf("%d\n", 57);;
int32_t h = ((f + 5) * ((((65 / (22 - b)) + -22) * c) + 63)) + f;
int32_t i = 9;
int32_t j = 45 + -27;
printf("%d\n", (g / (47 - (93 - e))) + f);;
printf("%d\n", b);;
int32_t k = i;
printf("%d\n", b);;
int32_t l = 25 * g;
printf("%d\n", k);;
printf("%d\n", 0 * i);;
printf("%d\n", -44);;
printf("%d\n", 28);;
printf("%d\n", b - h);;
printf("%d\n", -10);;
printf("%d\n", -23);;
printf("%d\n", 54 - (c + d));;
printf("%d\n", 2);;
printf("%d\n", l);;
printf("%d\n", d / (g / -12));;
printf("%d\n", c);;
printf("%d\n", f);;
int32_t m = 6;
int32_t n = -30;
printf("%d\n", m);;
printf("%d\n", (e / -44) - i);;
printf("%d\n", 39);;
printf("%d\n", 58 / (a * f));;
printf("%d\n", 46);;
printf("%d\n", 35);;
int32_t o = h - -13;
int32_t p = o;
printf("%d\n", l);;
printf("%d\n", h);;
printf("%d\n", 42);;
printf("%d\n", 46);;
printf("%d\n", 2);;
return 0;}