#include <stdint.h>
int main() {
int32_t a = 39;
int32_t b = a;
printf("%d\n", b);;
printf("%d\n", 6);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", 69);;
printf("%d\n", b);;
printf("%d\n", b);;
int32_t c = a;
printf("%d\n", a);;
printf("%d\n", -5 / b);;
printf("%d\n", a / (7 * (((59 * 40) + c) - (-23 - ((c / (-52 - ((-15 * 19) - -6))) - b)))));;
int32_t d = (c - 8) + (c * (-63 - -2));
printf("%d\n", 45);;
printf("%d\n", b);;
printf("%d\n", -39);;
printf("%d\n", b);;
int32_t e = b;
printf("%d\n", -17 + (b - b));;
printf("%d\n", -73);;
printf("%d\n", 51);;
int32_t f = e;
int32_t g = 41 + (-2 - (-69 + (f * -13)));
printf("%d\n", g);;
printf("%d\n", 49);;
printf("%d\n", -53);;
printf("%d\n", a);;
printf("%d\n", -3);;
int32_t h = a - 19;
printf("%d\n", (((-4 * 32) + h) + e) * (-112 / (-20 * -34)));;
printf("%d\n", h);;
printf("%d\n", 25);;
int32_t i = b;
printf("%d\n", (24 / -47) / 43);;
printf("%d\n", c);;
printf("%d\n", 64);;
return 0;}