#include <stdint.h>
int main() {
int32_t a = 56;
printf("%d\n", a);;
printf("%d\n", 1);;
int32_t b = 39;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", -17);;
printf("%d\n", -30);;
int32_t c = -36;
printf("%d\n", 43);;
printf("%d\n", -4);;
printf("%d\n", b);;
printf("%d\n", a);;
int32_t d = -6;
printf("%d\n", -20);;
int32_t e = d;
printf("%d\n", d);;
int32_t f = -90 / -53;
printf("%d\n", 62);;
printf("%d\n", e);;
printf("%d\n", (-36 / ((42 / (97 * 24)) + (e + (e + b)))) - f);;
int32_t g = -4;
printf("%d\n", 58);;
printf("%d\n", d);;
printf("%d\n", -56);;
printf("%d\n", -34);;
printf("%d\n", 46);;
int32_t h = a;
printf("%d\n", 47);;
printf("%d\n", 5 / (f + -35));;
printf("%d\n", e);;
int32_t i = h;
printf("%d\n", -2);;
printf("%d\n", 111);;
printf("%d\n", g);;
printf("%d\n", i);;
printf("%d\n", b / (((c + -40) * 112) - a));;
int32_t j = (d - (f + 133)) * e;
printf("%d\n", f - -19);;
printf("%d\n", f - 2);;
printf("%d\n", j);;
int32_t k = 10;
printf("%d\n", 33);;
printf("%d\n", c);;
int32_t l = c;
printf("%d\n", e);;
printf("%d\n", (-73 + (((((-47 / 41) * 19) / d) / (f + (16 - j))) - 52)) + (((j * j) * (-5 * k)) / 39));;
printf("%d\n", 3);;
int32_t m = 20;
printf("%d\n", a);;
printf("%d\n", 26);;
printf("%d\n", m);;
int32_t n = (h * h) * e;
printf("%d\n", l);;
printf("%d\n", c - -69);;
printf("%d\n", n * -23);;
printf("%d\n", d);;
printf("%d\n", ((i * g) + f) / -16);;
printf("%d\n", -19 + -24);;
int32_t o = 61 / (-99 * 78);
printf("%d\n", c);;
printf("%d\n", h);;
printf("%d\n", 14);;
printf("%d\n", c);;
int32_t p = i - (((7 - j) * (101 + (j / j))) * 4);
printf("%d\n", l);;
printf("%d\n", k);;
int32_t q = f;
printf("%d\n", j);;
printf("%d\n", m + (-18 - 4));;
int32_t r = q;
printf("%d\n", ((-4 / -41) + 25) * n);;
int32_t s = 82 * r;
int32_t t = -3;
printf("%d\n", -11);;
printf("%d\n", l);;
printf("%d\n", -20 + 39);;
printf("%d\n", h);;
int32_t u = -4;
printf("%d\n", 38);;
int32_t v = f / ((m * 4) - b);
int32_t w = g + (g - (u + (k / g)));
int32_t x = o;
printf("%d\n", -30 + (c * d));;
printf("%d\n", e);;
int32_t y = r;
printf("%d\n", -28);;
printf("%d\n", 7);;
int32_t z = 27 + w;
printf("%d\n", t);;
printf("%d\n", -47);;
int32_t aa = w;
int32_t ab = aa;
printf("%d\n", n);;
return 0;}