#include <stdint.h>
int main() {
printf("%d\n", 73);;
printf("%d\n", (8 - ((((-18 + -42) - ((-12 / -21) + 46)) / -129) + (2 - 43))) / ((35 * 18) / 12));;
int32_t a = (6 - ((-3 * 95) * 94)) + 43;
int32_t b = a + 18;
printf("%d\n", a);;
int32_t c = b - a;
int32_t d = 50 + b;
int32_t e = a + (13 - -2);
int32_t f = b;
printf("%d\n", 26);;
printf("%d\n", f);;
printf("%d\n", a);;
printf("%d\n", -36);;
printf("%d\n", -20);;
printf("%d\n", 17 + 39);;
int32_t g = 70 * (d / (b / 36));
printf("%d\n", g);;
printf("%d\n", b);;
printf("%d\n", e + (3 * g));;
printf("%d\n", f);;
printf("%d\n", 28);;
printf("%d\n", a);;
printf("%d\n", -40);;
int32_t h = -102;
printf("%d\n", -17);;
printf("%d\n", -43);;
printf("%d\n", b);;
printf("%d\n", h / f);;
printf("%d\n", b);;
printf("%d\n", 44);;
int32_t i = -3;
printf("%d\n", -41 + (g + (46 - a)));;
printf("%d\n", c);;
int32_t j = (f * b) - 51;
printf("%d\n", a);;
printf("%d\n", 104);;
printf("%d\n", e * (j + (h - 14)));;
printf("%d\n", i);;
printf("%d\n", (((c * j) * -41) * 1) / (((((51 - (-13 / (c - h))) - (41 - (d - -41))) - 56) + -58) + -20));;
printf("%d\n", b);;
printf("%d\n", 13);;
printf("%d\n", i + -41);;
printf("%d\n", j);;
int32_t k = h;
printf("%d\n", 21);;
printf("%d\n", 3);;
int32_t l = j;
printf("%d\n", -53);;
printf("%d\n", g);;
printf("%d\n", k - k);;
int32_t m = 35 + j;
printf("%d\n", -23 + (k + i));;
int32_t n = -34;
printf("%d\n", -37);;
printf("%d\n", 15);;
printf("%d\n", 35);;
printf("%d\n", b);;
printf("%d\n", g);;
return 0;}