#include <stdint.h>
int main() {
printf("%d\n", 41);;
printf("%d\n", (8 * 37) + -17);;
printf("%d\n", (-3 - ((-36 - 6) - ((4 - -1) + (83 + -53)))) / -17);;
printf("%d\n", 51 / -21);;
printf("%d\n", ((47 + -35) * -7) - -1);;
printf("%d\n", -65);;
printf("%d\n", 24);;
int32_t a = -15;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 49);;
printf("%d\n", a);;
printf("%d\n", -11);;
int32_t b = a;
printf("%d\n", 25);;
printf("%d\n", -51);;
int32_t c = a;
printf("%d\n", a * c);;
printf("%d\n", (-37 / (-20 - a)) + (-19 / ((c * (((c + -27) / a) * (a + a))) + ((18 * 19) + b))));;
printf("%d\n", b - c);;
int32_t d = (c / (-1 - c)) - c;
int32_t e = b;
int32_t f = (-47 / (-29 - (e - ((-50 / 6) - (c * -10))))) * 42;
printf("%d\n", (b / 25) + -1);;
int32_t g = f;
printf("%d\n", c);;
printf("%d\n", -54);;
int32_t h = -3;
printf("%d\n", -28);;
printf("%d\n", 62);;
printf("%d\n", -34);;
int32_t i = -11 * b;
printf("%d\n", h);;
printf("%d\n", c);;
int32_t j = h;
printf("%d\n", (g - j) - f);;
printf("%d\n", g);;
int32_t k = 64;
printf("%d\n", b - 20);;
printf("%d\n", 6);;
printf("%d\n", -1);;
int32_t l = h + j;
printf("%d\n", 2);;
printf("%d\n", d);;
printf("%d\n", 29);;
printf("%d\n", -50);;
int32_t m = (c - -77) * -25;
printf("%d\n", 47);;
int32_t n = f;
int32_t o = -40;
int32_t p = b - ((j * k) * 24);
printf("%d\n", 21 - -60);;
printf("%d\n", c);;
int32_t q = 66;
printf("%d\n", b);;
printf("%d\n", f);;
int32_t r = 31;
int32_t s = l;
printf("%d\n", 33);;
int32_t t = e;
printf("%d\n", o);;
int32_t u = t;
printf("%d\n", 24);;
int32_t v = a;
printf("%d\n", 20);;
printf("%d\n", (-10 - (-11 / q)) / -22);;
printf("%d\n", -9);;
printf("%d\n", 48);;
printf("%d\n", p);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", k * l);;
printf("%d\n", (-16 / m) * 5);;
printf("%d\n", 8 * -1);;
return 0;}