#include <stdint.h>
int main() {
printf("%d\n", -45 - -9);;
int32_t a = (15 * (73 * -20)) - 78;
printf("%d\n", a);;
printf("%d\n", 66 * a);;
printf("%d\n", -6);;
int32_t b = 4 - ((((a + (-5 + -34)) - a) - -13) * 84);
printf("%d\n", -61 + (b * (16 * (b / (((38 * ((b / 31) / 35)) + b) / -36)))));;
printf("%d\n", a * -58);;
printf("%d\n", 9 - b);;
printf("%d\n", -79);;
printf("%d\n", b);;
printf("%d\n", -62);;
int32_t c = a;
printf("%d\n", b - (a * ((a / -37) - (a + (8 * a)))));;
int32_t d = (((-12 / (((-53 + 134) * 19) * c)) + (b - 12)) * c) + -38;
printf("%d\n", c * d);;
printf("%d\n", c - b);;
printf("%d\n", -36);;
printf("%d\n", 12 * 22);;
int32_t e = a / (c + 44);
printf("%d\n", d);;
int32_t f = -2 + 36;
int32_t g = 9;
int32_t h = (((e * -32) * (-49 / f)) + -57) / ((10 / ((c - -39) / 78)) - (((c * ((21 + 22) + -19)) / -21) + (f * 40)));
printf("%d\n", 4);;
printf("%d\n", b - (c + (((a + ((h - g) - a)) / -12) * f)));;
printf("%d\n", -37 + 49);;
printf("%d\n", e / (b + d));;
printf("%d\n", d);;
printf("%d\n", -16 + (3 * 33));;
int32_t i = -78 * b;
printf("%d\n", f * -13);;
printf("%d\n", -96);;
printf("%d\n", f);;
printf("%d\n", a * b);;
printf("%d\n", c);;
int32_t j = -39;
printf("%d\n", 5);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", 22 - -32);;
printf("%d\n", a);;
int32_t k = i;
printf("%d\n", f);;
int32_t l = 59;
int32_t m = 5;
printf("%d\n", (d + i) - (-21 + (i / 56)));;
int32_t n = c;
printf("%d\n", l * e);;
int32_t o = l;
printf("%d\n", m);;
printf("%d\n", i - d);;
printf("%d\n", o);;
int32_t p = (n - i) * (66 / ((-33 + (l / 32)) + 17));
printf("%d\n", 34);;
int32_t q = 31;
printf("%d\n", o + (28 + m));;
printf("%d\n", d);;
printf("%d\n", q);;
printf("%d\n", 15);;
printf("%d\n", ((71 + ((-30 * -9) + ((p - ((59 * o) / ((b - k) - (((g * ((k / a) / o)) + 101) * (d / m))))) + -27))) * 17) * (-20 / f));;
printf("%d\n", 1);;
int32_t r = 5;
int32_t s = o;
int32_t t = 31;
int32_t u = b;
printf("%d\n", k);;
printf("%d\n", -15);;
printf("%d\n", -82 - (((-19 + -22) + (37 - 23)) * (5 / 45)));;
printf("%d\n", r);;
printf("%d\n", -1);;
printf("%d\n", -46 + -4);;
printf("%d\n", 28);;
int32_t v = i;
int32_t w = (d / (20 + (-29 + -59))) - (86 / m);
int32_t x = v;
printf("%d\n", e * v);;
int32_t y = t;
printf("%d\n", j);;
int32_t z = p;
int32_t aa = 40;
int32_t ab = 39 + (z * d);
printf("%d\n", -9 / (((63 * (((n + 37) - (u - (98 + 29))) + (-1 + 6))) + (a - -5)) / 42));;
printf("%d\n", b * (b * -5));;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", w);;
printf("%d\n", ((c - x) / -76) - 36);;
printf("%d\n", h - (b * e));;
printf("%d\n", f);;
printf("%d\n", g + h);;
printf("%d\n", aa + -63);;
printf("%d\n", 51);;
printf("%d\n", 16);;
printf("%d\n", -18);;
printf("%d\n", d - (q * (-3 / (-9 * 23))));;
printf("%d\n", r);;
int32_t ac = j;
printf("%d\n", n);;
printf("%d\n", -8);;
return 0;}