#include <stdint.h>
int main() {
int32_t a = 34;
printf("%d\n", 32 + (a / a));;
printf("%d\n", a / a);;
int32_t b = a;
int32_t c = b;
printf("%d\n", a);;
printf("%d\n", -69);;
printf("%d\n", -32);;
int32_t d = a * (b + a);
int32_t e = 12;
printf("%d\n", 71);;
printf("%d\n", a);;
int32_t f = -16;
printf("%d\n", 32);;
printf("%d\n", 37);;
int32_t g = d * e;
int32_t h = -40;
printf("%d\n", e);;
printf("%d\n", ((a / (c * -36)) - (79 + 63)) + e);;
printf("%d\n", c);;
int32_t i = f;
printf("%d\n", i);;
printf("%d\n", 24);;
printf("%d\n", (55 * f) + i);;
printf("%d\n", d - g);;
printf("%d\n", b);;
printf("%d\n", 31);;
printf("%d\n", (i / -36) * h);;
int32_t j = g;
printf("%d\n", 108 + e);;
int32_t k = -7 + 27;
printf("%d\n", 28 * (b + -36));;
printf("%d\n", (j - (-21 + 6)) - (j / 27));;
printf("%d\n", e);;
int32_t l = 34;
printf("%d\n", -71 + 45);;
int32_t m = (l + (c - -25)) - f;
printf("%d\n", -27);;
int32_t n = 55;
printf("%d\n", i);;
printf("%d\n", 43 / -29);;
printf("%d\n", g);;
printf("%d\n", 28);;
printf("%d\n", l);;
printf("%d\n", 16 + g);;
printf("%d\n", d);;
printf("%d\n", 13);;
printf("%d\n", n / -39);;
printf("%d\n", 33);;
printf("%d\n", (17 + j) * 26);;
printf("%d\n", b / (b - -39));;
int32_t o = -49;
int32_t p = (34 + l) / a;
printf("%d\n", j);;
printf("%d\n", ((-15 / -87) - b) / (m * 62));;
printf("%d\n", 9);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t q = c;
int32_t r = 105;
printf("%d\n", (-26 / c) + a);;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", 57 + ((-23 * d) - -49));;
printf("%d\n", ((10 + g) / 18) / d);;
printf("%d\n", l);;
int32_t s = m;
int32_t t = g;
printf("%d\n", -57);;
printf("%d\n", h);;
printf("%d\n", e);;
printf("%d\n", 10);;
printf("%d\n", r / ((-31 + i) * d));;
printf("%d\n", c - (e * ((r + 43) - m)));;
printf("%d\n", 17 / ((7 * f) - (l + -68)));;
printf("%d\n", e - p);;
printf("%d\n", (6 + 21) / 43);;
printf("%d\n", -11);;
printf("%d\n", q + f);;
printf("%d\n", j);;
int32_t u = -37 - -48;
int32_t v = m;
printf("%d\n", a);;
int32_t w = m + (44 + (19 / -59));
printf("%d\n", l - 60);;
printf("%d\n", j + (-2 + 38));;
printf("%d\n", 67 - q);;
printf("%d\n", c);;
printf("%d\n", 26 + -11);;
printf("%d\n", w);;
printf("%d\n", -31);;
printf("%d\n", -15 - -67);;
printf("%d\n", q);;
printf("%d\n", g);;
printf("%d\n", -30);;
int32_t x = 32 + -3;
printf("%d\n", t);;
printf("%d\n", g);;
int32_t y = 31;
printf("%d\n", j - h);;
int32_t z = c - (v + -19);
printf("%d\n", 3 * -15);;
printf("%d\n", -40);;
int32_t aa = -2;
printf("%d\n", z);;
printf("%d\n", -19 + 1);;
printf("%d\n", -22);;
printf("%d\n", q);;
printf("%d\n", e);;
int32_t ab = (-23 + -2) * aa;
printf("%d\n", c);;
printf("%d\n", y);;
printf("%d\n", -48);;
printf("%d\n", ((51 + -8) / h) + 2);;
printf("%d\n", k);;
printf("%d\n", -61 * ab);;
printf("%d\n", q);;
int32_t ac = -26;
printf("%d\n", 16);;
printf("%d\n", s * (e + (o + (((i + (2 / aa)) / 27) * -33))));;
printf("%d\n", x);;
printf("%d\n", z);;
printf("%d\n", n);;
printf("%d\n", y - q);;
printf("%d\n", (16 - 41) + 1);;
return 0;}