#include <stdint.h>
int main() {
printf("%d\n", -17 - 26);;
printf("%d\n", -35 / (((((2 + -13) * 20) - ((62 - -4) + 30)) * -39) * 1));;
printf("%d\n", 42);;
printf("%d\n", 23 - 119);;
printf("%d\n", 7 + 20);;
printf("%d\n", -1);;
printf("%d\n", -30);;
int32_t a = 73;
printf("%d\n", a);;
printf("%d\n", (-20 * ((a + -16) - a)) / 40);;
printf("%d\n", a);;
int32_t b = -16;
printf("%d\n", (b - (6 - (-33 / -60))) / (b * a));;
printf("%d\n", -1);;
printf("%d\n", a);;
int32_t c = 41 + a;
printf("%d\n", -1 - c);;
printf("%d\n", a);;
int32_t d = 32;
int32_t e = b + d;
printf("%d\n", 6 - (d + (c - (b + (b / b)))));;
printf("%d\n", c);;
printf("%d\n", 42);;
int32_t f = d;
printf("%d\n", (-84 * a) - (37 - b));;
printf("%d\n", f);;
int32_t g = a;
printf("%d\n", g + (-10 / (f - a)));;
printf("%d\n", -28);;
printf("%d\n", 26);;
int32_t h = e;
printf("%d\n", a * (b / 28));;
printf("%d\n", h);;
printf("%d\n", e);;
printf("%d\n", 32);;
int32_t i = 68;
int32_t j = -4;
printf("%d\n", g);;
printf("%d\n", j);;
int32_t k = j + d;
printf("%d\n", k);;
printf("%d\n", e);;
printf("%d\n", (58 + -51) / d);;
printf("%d\n", 1);;
printf("%d\n", k - 78);;
int32_t l = j;
int32_t m = (d * -4) * -1;
int32_t n = j;
int32_t o = l;
printf("%d\n", d / h);;
printf("%d\n", 38);;
printf("%d\n", -56 + -12);;
int32_t p = m / c;
int32_t q = -84;
int32_t r = 21;
printf("%d\n", -26);;
printf("%d\n", 82);;
printf("%d\n", -78 + h);;
printf("%d\n", m);;
int32_t s = n - j;
printf("%d\n", -17);;
int32_t t = 30;
printf("%d\n", 35);;
printf("%d\n", h * (-19 - ((45 * 32) / q)));;
printf("%d\n", 42);;
int32_t u = 50;
printf("%d\n", -22);;
printf("%d\n", -35);;
printf("%d\n", r);;
printf("%d\n", g - l);;
printf("%d\n", 48);;
int32_t v = i;
printf("%d\n", a);;
printf("%d\n", 11);;
printf("%d\n", a / 31);;
return 0;}