#include <stdint.h>
int main() {
int32_t a = 43 / 31;
printf("%d\n", -13);;
printf("%d\n", a);;
printf("%d\n", -24 * 42);;
int32_t b = 1;
printf("%d\n", -93);;
printf("%d\n", -7);;
printf("%d\n", (b * (a * -27)) / b);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 19);;
printf("%d\n", (a / 4) + 99);;
printf("%d\n", 9);;
int32_t c = 26 + (b * a);
printf("%d\n", -4);;
int32_t d = -54 / -73;
printf("%d\n", (c + ((a + b) / 64)) - (b - (23 + b)));;
printf("%d\n", -42);;
printf("%d\n", b);;
printf("%d\n", -16);;
int32_t e = (65 + b) * -31;
printf("%d\n", e);;
int32_t f = a * -5;
printf("%d\n", 50 - ((30 / 65) + f));;
printf("%d\n", b - 20);;
printf("%d\n", e);;
printf("%d\n", (a - 17) / (-34 - e));;
int32_t g = f;
printf("%d\n", a);;
printf("%d\n", e);;
printf("%d\n", -2);;
printf("%d\n", -24);;
printf("%d\n", 34);;
printf("%d\n", g);;
printf("%d\n", c);;
int32_t h = b / -36;
printf("%d\n", -20);;
printf("%d\n", ((50 + -47) / (f - (4 / 19))) + b);;
printf("%d\n", 12);;
printf("%d\n", c);;
printf("%d\n", (h * h) / ((41 / -18) - g));;
printf("%d\n", 50);;
printf("%d\n", -58);;
int32_t i = -31;
int32_t j = (((-22 * c) + -6) - f) / -41;
printf("%d\n", 21 / (64 / (j + -16)));;
int32_t k = 1 + -2;
printf("%d\n", k);;
return 0;}