#include <stdint.h>
int main() {
int32_t a = -29;
int32_t b = 19;
printf("%d\n", 23);;
printf("%d\n", b);;
printf("%d\n", a);;
int32_t c = 37 - a;
printf("%d\n", -51);;
printf("%d\n", 14);;
printf("%d\n", -28);;
printf("%d\n", a);;
printf("%d\n", 47);;
int32_t d = 22 + 15;
printf("%d\n", b - (a / (a - 85)));;
printf("%d\n", a);;
printf("%d\n", -6);;
printf("%d\n", d);;
printf("%d\n", -6);;
printf("%d\n", 34);;
printf("%d\n", d);;
int32_t e = b;
printf("%d\n", 42);;
printf("%d\n", 6);;
int32_t f = e / d;
int32_t g = 20 - ((((b - b) - c) - -10) * -14);
printf("%d\n", d);;
int32_t h = b;
int32_t i = -47;
printf("%d\n", 36 * -32);;
int32_t j = h;
printf("%d\n", (66 * (8 * ((73 + (g * -19)) * ((-3 * c) + 26)))) - -35);;
printf("%d\n", i);;
printf("%d\n", -30);;
printf("%d\n", f);;
printf("%d\n", 79);;
printf("%d\n", 37);;
printf("%d\n", a);;
printf("%d\n", 22);;
int32_t k = -28;
printf("%d\n", e);;
printf("%d\n", ((i * c) * (h - 23)) / 68);;
printf("%d\n", 20);;
printf("%d\n", 62);;
int32_t l = (e / (((h / 24) + j) * d)) / g;
printf("%d\n", 59);;
printf("%d\n", -23);;
int32_t m = 22;
int32_t n = i;
printf("%d\n", l - c);;
printf("%d\n", n);;
printf("%d\n", 41);;
int32_t o = l;
int32_t p = j;
printf("%d\n", 32);;
int32_t q = d;
printf("%d\n", e);;
printf("%d\n", 2);;
printf("%d\n", j);;
printf("%d\n", -1);;
printf("%d\n", e + -27);;
printf("%d\n", (d * ((84 - -41) - 31)) / 101);;
printf("%d\n", 19);;
printf("%d\n", 32 + -14);;
printf("%d\n", 45);;
printf("%d\n", 70);;
printf("%d\n", (14 / (-27 + k)) * h);;
int32_t r = c - 12;
int32_t s = 34;
printf("%d\n", c);;
printf("%d\n", -5);;
printf("%d\n", m);;
int32_t t = 4;
printf("%d\n", a);;
printf("%d\n", l + r);;
printf("%d\n", -33);;
int32_t u = -45 * (l * c);
printf("%d\n", 25);;
int32_t v = -1;
int32_t w = j;
printf("%d\n", t + -9);;
printf("%d\n", j);;
printf("%d\n", -67);;
printf("%d\n", 29);;
printf("%d\n", i - (-39 - p));;
printf("%d\n", b);;
printf("%d\n", -25);;
printf("%d\n", 81);;
printf("%d\n", s + o);;
printf("%d\n", -37 - 130);;
printf("%d\n", (4 / 22) / ((p * q) + c));;
int32_t x = -23 - (r / 39);
int32_t y = -4 - 4;
printf("%d\n", -26);;
printf("%d\n", -32);;
printf("%d\n", 88 - k);;
printf("%d\n", (103 - 97) + 53);;
printf("%d\n", -70);;
int32_t z = 31;
return 0;}