#include <stdint.h>
int main() {
printf("%d\n", -7);;
int32_t a = -42 / 35;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 21);;
printf("%d\n", 43);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", -40);;
printf("%d\n", (33 + a) / -20);;
printf("%d\n", a);;
int32_t b = -31;
printf("%d\n", 41);;
int32_t c = a;
int32_t d = b;
int32_t e = 23;
printf("%d\n", ((c * -47) + 31) - (((((a / a) * e) - ((((85 + 12) * d) + ((54 - 16) - b)) / (a + (-3 - e)))) * d) - a));;
int32_t f = 41;
printf("%d\n", a);;
printf("%d\n", 3);;
printf("%d\n", -60 - -14);;
printf("%d\n", -23);;
int32_t g = (a - 44) + 113;
printf("%d\n", -46);;
printf("%d\n", -63 - f);;
printf("%d\n", c);;
int32_t h = ((((0 / (6 - -21)) - f) / -16) + (((f + -3) + 86) * -47)) - f;
printf("%d\n", -71);;
printf("%d\n", -44);;
printf("%d\n", 55);;
printf("%d\n", (g * (40 * 28)) + h);;
printf("%d\n", g + d);;
int32_t i = -30;
printf("%d\n", a - -8);;
int32_t j = g;
printf("%d\n", 22);;
printf("%d\n", j);;
printf("%d\n", f);;
printf("%d\n", 16 - f);;
printf("%d\n", 16);;
printf("%d\n", a);;
int32_t k = (c - (34 + -26)) + (32 * b);
int32_t l = -10;
printf("%d\n", h);;
printf("%d\n", 31);;
int32_t m = 66;
int32_t n = 29;
printf("%d\n", m);;
printf("%d\n", m);;
printf("%d\n", 0);;
printf("%d\n", 30);;
printf("%d\n", k);;
printf("%d\n", (-8 * f) - (27 + 39));;
printf("%d\n", d);;
printf("%d\n", 12);;
printf("%d\n", d);;
int32_t o = -7;
printf("%d\n", b);;
printf("%d\n", h);;
int32_t p = 26;
printf("%d\n", 5 + l);;
printf("%d\n", d);;
printf("%d\n", -29);;
printf("%d\n", -26);;
printf("%d\n", 25);;
printf("%d\n", j);;
printf("%d\n", d);;
int32_t q = (((3 * -27) * -46) / -79) + f;
int32_t r = 64;
int32_t s = (86 + -70) - 32;
printf("%d\n", k);;
int32_t t = l;
int32_t u = l / 35;
int32_t v = -32;
printf("%d\n", k);;
printf("%d\n", t);;
printf("%d\n", (((a / (-32 + 20)) / j) * (k + o)) / t);;
printf("%d\n", -16);;
int32_t w = 0 / (c - 6);
printf("%d\n", m);;
printf("%d\n", p);;
printf("%d\n", c);;
printf("%d\n", -13);;
int32_t x = -1;
printf("%d\n", 12);;
printf("%d\n", f);;
printf("%d\n", m);;
int32_t y = v;
int32_t z = m / 32;
printf("%d\n", m);;
printf("%d\n", v);;
printf("%d\n", u);;
printf("%d\n", (-40 / 68) + (j / 52));;
int32_t aa = p;
int32_t ab = a;
printf("%d\n", -15);;
printf("%d\n", h - 23);;
printf("%d\n", 69);;
printf("%d\n", p);;
printf("%d\n", f);;
printf("%d\n", 53);;
printf("%d\n", 50);;
printf("%d\n", f);;
printf("%d\n", -35);;
int32_t ac = 46;
printf("%d\n", -12 + ab);;
printf("%d\n", (-22 / (j - ac)) + p);;
int32_t ad = j;
printf("%d\n", -46);;
printf("%d\n", 5);;
printf("%d\n", u);;
printf("%d\n", 22);;
printf("%d\n", f);;
printf("%d\n", v);;
printf("%d\n", 11);;
int32_t ae = -21;
int32_t af = 27;
printf("%d\n", v);;
printf("%d\n", (-55 / n) - j);;
printf("%d\n", 43);;
printf("%d\n", c);;
int32_t ag = 47;
printf("%d\n", v);;
printf("%d\n", e);;
printf("%d\n", l);;
printf("%d\n", 40 - (a / ag));;
printf("%d\n", (26 - -17) * g);;
printf("%d\n", u + ad);;
printf("%d\n", -15);;
printf("%d\n", b);;
int32_t ah = ac;
int32_t ai = 24 + f;
printf("%d\n", -45);;
printf("%d\n", 2);;
printf("%d\n", t / 11);;
int32_t aj = n;
printf("%d\n", -6);;
printf("%d\n", ad);;
printf("%d\n", l / f);;
int32_t ak = d;
printf("%d\n", 34);;
printf("%d\n", -44);;
int32_t al = -24;
printf("%d\n", b);;
int32_t am = m;
printf("%d\n", 28);;
printf("%d\n", 15);;
printf("%d\n", -56);;
printf("%d\n", -20);;
int32_t an = c;
printf("%d\n", -98);;
printf("%d\n", 9 * -6);;
printf("%d\n", 42);;
printf("%d\n", -39);;
printf("%d\n", y);;
printf("%d\n", 29);;
printf("%d\n", -1);;
printf("%d\n", e);;
printf("%d\n", -21);;
printf("%d\n", 52 + -85);;
int32_t ao = am + (an / (p * ab));
printf("%d\n", -41);;
printf("%d\n", af);;
printf("%d\n", s);;
printf("%d\n", -6);;
int32_t ap = (((am - 17) * 17) - ah) * i;
printf("%d\n", -6);;
printf("%d\n", -80);;
printf("%d\n", -37);;
printf("%d\n", -32);;
printf("%d\n", (44 - ag) / 67);;
printf("%d\n", 23 - -4);;
int32_t aq = 45;
printf("%d\n", -48);;
printf("%d\n", -2);;
printf("%d\n", e);;
printf("%d\n", c);;
printf("%d\n", 35);;
printf("%d\n", t);;
return 0;}