#include <stdint.h>
int main() {
printf("%d\n", -19);;
int32_t a = 36 + -51;
printf("%d\n", 8);;
printf("%d\n", a);;
printf("%d\n", 22);;
printf("%d\n", 46);;
printf("%d\n", -43);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t b = -33;
printf("%d\n", a);;
printf("%d\n", -12);;
printf("%d\n", a / b);;
printf("%d\n", a);;
printf("%d\n", -25);;
printf("%d\n", b);;
printf("%d\n", (18 + a) * (36 + 87));;
printf("%d\n", a - 24);;
printf("%d\n", 58 - (64 + a));;
printf("%d\n", 4 / ((-91 - (-2 * -9)) + -8));;
printf("%d\n", 66);;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 18);;
printf("%d\n", 65);;
printf("%d\n", 33);;
printf("%d\n", b);;
printf("%d\n", -32);;
printf("%d\n", 89);;
printf("%d\n", -27);;
int32_t c = -12;
printf("%d\n", (c / (b - (30 / c))) - -7);;
int32_t d = 22;
printf("%d\n", a / (a / (a / a)));;
printf("%d\n", 42);;
int32_t e = 20;
printf("%d\n", -92);;
int32_t f = 9;
printf("%d\n", c * f);;
printf("%d\n", 4 / b);;
int32_t g = b;
printf("%d\n", e);;
printf("%d\n", 4);;
printf("%d\n", -8);;
printf("%d\n", c);;
printf("%d\n", ((g + -29) * 3) + e);;
printf("%d\n", -53);;
printf("%d\n", f);;
int32_t h = -5;
int32_t i = g;
int32_t j = -15;
printf("%d\n", f);;
printf("%d\n", f / b);;
printf("%d\n", 47);;
int32_t k = i;
int32_t l = b;
printf("%d\n", 8);;
int32_t m = b * (j / 3);
printf("%d\n", e);;
printf("%d\n", 16);;
int32_t n = 15;
int32_t o = i - l;
printf("%d\n", i - i);;
printf("%d\n", 41 + -1);;
printf("%d\n", f);;
printf("%d\n", n / n);;
printf("%d\n", 18);;
printf("%d\n", d);;
printf("%d\n", -10 * (i / -63));;
printf("%d\n", -7);;
printf("%d\n", h);;
printf("%d\n", h + 2);;
printf("%d\n", -12);;
printf("%d\n", g);;
int32_t p = ((i - (49 * i)) / f) / i;
int32_t q = 51;
printf("%d\n", k);;
int32_t r = 27 / c;
printf("%d\n", (((47 / -43) + -18) + c) / -127);;
int32_t s = d;
int32_t t = -32;
printf("%d\n", m / j);;
printf("%d\n", -25 - (46 / -5));;
int32_t u = q;
int32_t v = o;
int32_t w = -14;
printf("%d\n", -15 + j);;
printf("%d\n", o);;
printf("%d\n", -30);;
printf("%d\n", -3);;
printf("%d\n", s);;
printf("%d\n", c);;
printf("%d\n", -108);;
int32_t x = 16;
int32_t y = -5;
printf("%d\n", r);;
printf("%d\n", 12);;
printf("%d\n", 13 / 38);;
printf("%d\n", o / (((6 * (f / x)) - o) - d));;
printf("%d\n", -21);;
printf("%d\n", ((m / h) - (((k * (w / 13)) - r) * (7 + m))) - y);;
printf("%d\n", s);;
printf("%d\n", 10);;
printf("%d\n", -46);;
printf("%d\n", w + 14);;
printf("%d\n", 11 * -66);;
printf("%d\n", d);;
int32_t z = b;
int32_t aa = b;
printf("%d\n", d);;
printf("%d\n", (-42 * t) + o);;
int32_t ab = -56;
int32_t ac = 25;
printf("%d\n", 8);;
int32_t ad = 60;
printf("%d\n", 1);;
printf("%d\n", x - (h * h));;
int32_t ae = ((x + i) - (50 * (g * (34 - 54)))) / -21;
printf("%d\n", (-14 + (d * ((-28 / 28) - -11))) * ((-38 - (-89 / ((((t + 25) + 43) * ((s * -57) - k)) - (z + (h + (ae - (43 / ((j - ((d / (s * e)) / 41)) * -38)))))))) - (aa * 0)));;
int32_t af = 69 / 52;
printf("%d\n", ((49 / (((t / 65) / -69) + 4)) - 28) + (28 * (v * s)));;
printf("%d\n", x);;
printf("%d\n", 14);;
int32_t ag = 15;
printf("%d\n", e);;
printf("%d\n", x);;
printf("%d\n", -8);;
printf("%d\n", -12 - -54);;
printf("%d\n", g + (c - n));;
printf("%d\n", u);;
printf("%d\n", -53);;
printf("%d\n", (aa + 49) * (75 / (r - (15 - z))));;
printf("%d\n", (89 * 13) / h);;
printf("%d\n", (((45 + q) / e) - n) + -112);;
printf("%d\n", -1 / f);;
printf("%d\n", (f / ((a + k) * l)) / x);;
printf("%d\n", 16);;
printf("%d\n", -9);;
printf("%d\n", m);;
int32_t ah = t;
printf("%d\n", 48);;
int32_t ai = z;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", -33);;
printf("%d\n", r);;
printf("%d\n", (27 - (af + 33)) * (72 * (8 / (76 - o))));;
printf("%d\n", -11);;
printf("%d\n", ai);;
int32_t aj = h;
printf("%d\n", a);;
printf("%d\n", (2 / k) * e);;
int32_t ak = (((y * 27) / aj) + ((l - 71) + f)) * z;
printf("%d\n", 25);;
printf("%d\n", 3);;
printf("%d\n", ag);;
printf("%d\n", ag / t);;
printf("%d\n", -27);;
printf("%d\n", f + d);;
printf("%d\n", k);;
int32_t al = 5;
printf("%d\n", (af - 32) + 69);;
printf("%d\n", ag);;
int32_t am = (a + 29) - -37;
printf("%d\n", z / x);;
printf("%d\n", -7);;
printf("%d\n", ah);;
printf("%d\n", 13 * g);;
int32_t an = -9;
printf("%d\n", 33);;
printf("%d\n", ac);;
printf("%d\n", s);;
printf("%d\n", s * (-14 * 61));;
int32_t ao = i;
int32_t ap = (10 + (65 - w)) * 7;
int32_t aq = (r - -33) * (-20 - (w / 9));
printf("%d\n", v / 37);;
return 0;}