#include <stdint.h>
int main() {
int32_t a = 51;
printf("%d\n", a);;
int32_t b = -11 * -14;
printf("%d\n", a);;
printf("%d\n", b);;
int32_t c = 20;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", a);;
int32_t d = ((11 / (c + c)) - b) + 82;
int32_t e = 19;
printf("%d\n", d);;
int32_t f = 2;
printf("%d\n", -33);;
printf("%d\n", a);;
printf("%d\n", 10);;
printf("%d\n", 30);;
printf("%d\n", f);;
printf("%d\n", -8 / 78);;
printf("%d\n", e);;
printf("%d\n", b);;
int32_t g = -30 / -12;
printf("%d\n", e);;
printf("%d\n", (d / g) - 0);;
printf("%d\n", 38);;
printf("%d\n", g + 42);;
printf("%d\n", 27);;
printf("%d\n", 34 / -34);;
int32_t h = 54 / e;
printf("%d\n", d);;
printf("%d\n", d);;
printf("%d\n", a * 10);;
printf("%d\n", -34);;
printf("%d\n", 20);;
printf("%d\n", ((((9 - f) + (((e / 60) - e) / ((e - 113) - 28))) + -39) / (-23 + ((c / ((e / 61) - -10)) * (((d - h) * g) * 69)))) * g);;
printf("%d\n", 34);;
int32_t i = 41;
printf("%d\n", 34);;
printf("%d\n", ((((((b - 0) / (22 + (a / a))) / f) - b) * b) - 11) / (-26 + -30));;
printf("%d\n", 44);;
int32_t j = (100 - (-47 * (-43 + (i / -14)))) * -42;
printf("%d\n", (j + (i * i)) - d);;
int32_t k = j;
int32_t l = h;
return 0;}