#include <stdint.h>
int main() {
printf("%d\n", -55);;
int32_t a = 3;
printf("%d\n", 60);;
printf("%d\n", a);;
printf("%d\n", 104);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t b = a;
int32_t c = a;
int32_t d = ((88 - -19) - -8) + 55;
printf("%d\n", d);;
int32_t e = c - (c * (15 - -98));
printf("%d\n", e);;
printf("%d\n", 8);;
printf("%d\n", -8);;
printf("%d\n", 0 + (c + (e + e)));;
printf("%d\n", (62 / -24) - -22);;
printf("%d\n", 6);;
printf("%d\n", ((e - b) - (-64 * -16)) - 16);;
printf("%d\n", d / 46);;
printf("%d\n", d / 18);;
printf("%d\n", 17 - a);;
printf("%d\n", -30);;
printf("%d\n", -10);;
printf("%d\n", -24);;
printf("%d\n", e);;
printf("%d\n", 36);;
printf("%d\n", 1);;
printf("%d\n", (a + 27) - 1);;
printf("%d\n", 58);;
printf("%d\n", a);;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", c);;
printf("%d\n", 33);;
printf("%d\n", 10);;
printf("%d\n", e);;
printf("%d\n", -28);;
printf("%d\n", a);;
printf("%d\n", (-12 * d) - 8);;
int32_t f = b;
int32_t g = b;
int32_t h = 20;
int32_t i = c - d;
printf("%d\n", b + (-11 + -20));;
printf("%d\n", 37 * 17);;
printf("%d\n", 37 / -6);;
printf("%d\n", b);;
return 0;}