#include <stdint.h>
int main() {
int32_t a = 58;
int32_t b = 4;
printf("%d\n", -10);;
printf("%d\n", -3);;
printf("%d\n", -60);;
printf("%d\n", (4 / 42) / b);;
printf("%d\n", 76);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 29);;
int32_t c = 53;
int32_t d = 3 + -34;
int32_t e = b;
int32_t f = (-7 - (-5 - (c + -14))) + a;
int32_t g = -55;
int32_t h = b;
printf("%d\n", f);;
int32_t i = d;
printf("%d\n", d);;
printf("%d\n", 24);;
printf("%d\n", 45 + 44);;
int32_t j = b;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", h);;
printf("%d\n", a);;
int32_t k = a;
printf("%d\n", -2);;
printf("%d\n", d);;
printf("%d\n", g);;
int32_t l = (52 + -2) - (-87 - (a / b));
printf("%d\n", (19 / (33 + (-28 / k))) + -5);;
printf("%d\n", ((g * (52 / ((-11 / 53) + -21))) - 82) * (28 - j));;
printf("%d\n", 10);;
printf("%d\n", 13);;
int32_t m = 3;
int32_t n = -48;
printf("%d\n", d);;
printf("%d\n", l - a);;
int32_t o = c;
printf("%d\n", 18);;
printf("%d\n", h);;
printf("%d\n", 28);;
int32_t p = a;
int32_t q = j;
int32_t r = (0 + j) - g;
printf("%d\n", 31 + e);;
printf("%d\n", q);;
printf("%d\n", -4);;
int32_t s = g + -5;
printf("%d\n", c);;
int32_t t = e;
printf("%d\n", a);;
printf("%d\n", m);;
printf("%d\n", -31);;
printf("%d\n", -26);;
printf("%d\n", 14);;
printf("%d\n", -34);;
int32_t u = q;
int32_t v = -30;
printf("%d\n", i - (-17 / t));;
printf("%d\n", s);;
printf("%d\n", (-7 + 24) + h);;
int32_t w = s;
printf("%d\n", (l * -27) * 54);;
int32_t x = -24;
printf("%d\n", b - -66);;
int32_t y = f;
int32_t z = (-24 / (26 - (6 * ((q / 32) / t)))) / 93;
printf("%d\n", -2 * a);;
int32_t aa = t + ((q + y) * -36);
printf("%d\n", q);;
printf("%d\n", -21 - -20);;
printf("%d\n", g);;
printf("%d\n", c);;
printf("%d\n", (aa + -23) - 34);;
printf("%d\n", t);;
int32_t ab = 24;
printf("%d\n", 3);;
printf("%d\n", (s - i) + (21 / d));;
int32_t ac = 17 + (j + ((((i - -24) * 9) - q) - (16 / (s / -15))));
printf("%d\n", o);;
int32_t ad = 52;
printf("%d\n", 16);;
printf("%d\n", 27);;
printf("%d\n", o);;
printf("%d\n", q - u);;
printf("%d\n", t + (50 * g));;
int32_t ae = ad - -74;
printf("%d\n", 8);;
int32_t af = 22;
printf("%d\n", ad + af);;
int32_t ag = r;
printf("%d\n", 39 - (ag / (7 - -19)));;
printf("%d\n", aa - af);;
printf("%d\n", -11);;
printf("%d\n", -58);;
printf("%d\n", aa);;
printf("%d\n", (1 * ((56 - 9) * 144)) / (-3 - ((c + -43) / (-11 * j))));;
int32_t ah = -37;
printf("%d\n", 2);;
int32_t ai = -14;
printf("%d\n", ad);;
printf("%d\n", -51 / 51);;
printf("%d\n", w);;
printf("%d\n", q);;
printf("%d\n", -9);;
printf("%d\n", i);;
printf("%d\n", h);;
printf("%d\n", 61 * ag);;
printf("%d\n", aa);;
printf("%d\n", 47 - 12);;
printf("%d\n", ah);;
printf("%d\n", 29);;
int32_t aj = u - (i * (y + a));
printf("%d\n", 26 + ((ab + (v / ((t + p) * 51))) * k));;
printf("%d\n", ad);;
int32_t ak = t * -43;
printf("%d\n", -8 + z);;
printf("%d\n", n);;
int32_t al = (-38 / (25 / m)) * -15;
int32_t am = ad * -1;
printf("%d\n", h);;
return 0;}