#include <stdint.h>
int main() {
int32_t a = (-19 + -13) + -55;
printf("%d\n", (50 + 12) * a);;
printf("%d\n", (33 - -43) + ((-2 - 78) + (a * ((14 + (a - a)) * 24))));;
printf("%d\n", 36);;
printf("%d\n", a);;
int32_t b = 28;
printf("%d\n", (a - (26 + a)) + (29 + (20 / -52)));;
int32_t c = -1;
printf("%d\n", b);;
printf("%d\n", 7 / (-45 - 66));;
printf("%d\n", -23);;
printf("%d\n", a);;
printf("%d\n", 49);;
printf("%d\n", c + b);;
printf("%d\n", c / -33);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", a + a);;
int32_t d = a * 35;
printf("%d\n", d);;
printf("%d\n", ((d * (((d / -84) / a) / b)) + 45) + -12);;
printf("%d\n", c / 28);;
printf("%d\n", d - 32);;
printf("%d\n", d / d);;
int32_t e = b * b;
printf("%d\n", b);;
printf("%d\n", b + -14);;
printf("%d\n", -10 + (3 / (5 + 38)));;
int32_t f = 4;
printf("%d\n", f);;
int32_t g = d / (d + 9);
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", -6);;
printf("%d\n", b + -1);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", -34);;
printf("%d\n", 79);;
printf("%d\n", a * 38);;
printf("%d\n", (-52 / d) * a);;
int32_t h = 22;
printf("%d\n", 8 - a);;
printf("%d\n", f);;
int32_t i = (a * (32 / -3)) - a;
printf("%d\n", a);;
printf("%d\n", e + -65);;
int32_t j = (d + g) * -47;
printf("%d\n", g);;
int32_t k = 36 * 23;
printf("%d\n", 2);;
int32_t l = k;
printf("%d\n", 35);;
printf("%d\n", -3);;
int32_t m = h * l;
printf("%d\n", d + -21);;
printf("%d\n", j);;
printf("%d\n", -10);;
printf("%d\n", ((9 / e) + 69) - (2 - 80));;
printf("%d\n", -11 * ((f - -11) - 47));;
printf("%d\n", 40);;
int32_t n = 76;
int32_t o = k;
printf("%d\n", -75 / j);;
printf("%d\n", a * a);;
int32_t p = j;
return 0;}