#include <stdint.h>
int main() {
printf("%d\n", -38 + 43);;
printf("%d\n", 7);;
printf("%d\n", 0 * 119);;
printf("%d\n", 5);;
printf("%d\n", -54);;
printf("%d\n", -77 / 29);;
int32_t a = -3;
int32_t b = (-48 / ((a + -56) / 1)) - (80 + a);
printf("%d\n", (((-37 + -56) - (a + -39)) - 87) / a);;
printf("%d\n", b);;
printf("%d\n", 9);;
int32_t c = 17 + -7;
printf("%d\n", -19);;
int32_t d = c;
printf("%d\n", -53 - -85);;
int32_t e = 12;
printf("%d\n", (d + (95 + d)) - (-17 * ((((-27 - a) * a) - 4) + -6)));;
printf("%d\n", c);;
int32_t f = d / 85;
printf("%d\n", f);;
int32_t g = 74;
printf("%d\n", -5);;
printf("%d\n", 75);;
printf("%d\n", 26);;
printf("%d\n", d);;
printf("%d\n", b);;
printf("%d\n", g);;
int32_t h = -26;
printf("%d\n", 24 - g);;
printf("%d\n", ((c * 74) / h) + b);;
printf("%d\n", (-22 - -36) + -58);;
printf("%d\n", -10);;
printf("%d\n", g / e);;
printf("%d\n", (29 + h) - h);;
int32_t i = -62;
int32_t j = 43;
int32_t k = 88;
int32_t l = -3;
printf("%d\n", j);;
int32_t m = l;
printf("%d\n", i);;
printf("%d\n", g);;
printf("%d\n", -22 - -13);;
int32_t n = a;
printf("%d\n", 64 * -26);;
printf("%d\n", -26);;
int32_t o = ((a * (((j * 9) - (a / 65)) + (82 / -86))) - -27) + -51;
printf("%d\n", i);;
int32_t p = o;
printf("%d\n", 17);;
printf("%d\n", m);;
printf("%d\n", -6);;
printf("%d\n", a / j);;
printf("%d\n", c + 2);;
printf("%d\n", 33);;
int32_t q = m;
printf("%d\n", i);;
int32_t r = 27;
printf("%d\n", b / h);;
printf("%d\n", b);;
printf("%d\n", -30);;
printf("%d\n", c);;
printf("%d\n", 34);;
printf("%d\n", -45);;
int32_t s = -7;
printf("%d\n", f);;
printf("%d\n", 63 / 4);;
printf("%d\n", m);;
printf("%d\n", 93);;
printf("%d\n", (35 / s) + b);;
printf("%d\n", -23);;
printf("%d\n", -19);;
printf("%d\n", i);;
printf("%d\n", k);;
printf("%d\n", o);;
printf("%d\n", b / 49);;
printf("%d\n", 37);;
printf("%d\n", 66);;
printf("%d\n", -22);;
printf("%d\n", p);;
printf("%d\n", -22 * i);;
return 0;}