#include <stdint.h>
int main() {
printf("%d\n", -57);;
int32_t a = -5;
printf("%d\n", 12);;
printf("%d\n", a);;
int32_t b = a;
printf("%d\n", a);;
printf("%d\n", 38);;
int32_t c = -31;
printf("%d\n", ((a + 28) / (c - (c - -36))) + a);;
printf("%d\n", c);;
printf("%d\n", -23 * (27 * -12));;
printf("%d\n", 25);;
printf("%d\n", -6 + -51);;
printf("%d\n", c);;
printf("%d\n", a);;
printf("%d\n", 7);;
printf("%d\n", c + (c + b));;
printf("%d\n", b / ((84 - (13 / c)) / 42));;
printf("%d\n", -22);;
printf("%d\n", (3 - (b + 79)) + 54);;
printf("%d\n", 87);;
int32_t d = -40;
printf("%d\n", -23 - 54);;
int32_t e = d;
printf("%d\n", a / (((a - e) + 87) - ((-28 / (e / d)) / b)));;
printf("%d\n", -10);;
printf("%d\n", 6);;
printf("%d\n", d + b);;
printf("%d\n", e);;
printf("%d\n", 10);;
printf("%d\n", -41);;
printf("%d\n", a);;
printf("%d\n", 18);;
int32_t f = -8;
printf("%d\n", (((((b * ((f - (((c - 28) * a) + (3 * (((21 + (c + (d - (-62 + a)))) + c) - e)))) + -55)) - e) / d) / (27 - (-18 + (-18 * -50)))) - 13) + 19);;
int32_t g = 45;
printf("%d\n", f + b);;
printf("%d\n", 27 * (-29 * e));;
printf("%d\n", b);;
printf("%d\n", b);;
int32_t h = e;
printf("%d\n", 2);;
printf("%d\n", e);;
printf("%d\n", b);;
printf("%d\n", a * (26 - (-51 + 62)));;
int32_t i = -58;
printf("%d\n", d);;
printf("%d\n", a * (a - i));;
printf("%d\n", (-2 + f) - b);;
printf("%d\n", d);;
int32_t j = i;
int32_t k = e;
printf("%d\n", c);;
int32_t l = (3 * 17) * (-10 / b);
printf("%d\n", i);;
int32_t m = j;
int32_t n = ((24 - 15) / (((-5 * c) * i) / -62)) * -7;
printf("%d\n", 78);;
printf("%d\n", d + (65 - f));;
int32_t o = b + g;
printf("%d\n", c + (-35 + ((a / 76) + (0 * h))));;
printf("%d\n", e);;
int32_t p = k;
printf("%d\n", -6);;
printf("%d\n", i);;
int32_t q = (62 * 20) - 17;
printf("%d\n", 16);;
int32_t r = (77 + -15) / c;
printf("%d\n", (j + 53) - (g - -21));;
printf("%d\n", -1);;
int32_t s = g;
return 0;}