#include <stdint.h>
int main() {
printf("%d\n", (36 / 19) * -37);;
int32_t a = 28 + (22 - -20);
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a - (a * (39 / a)));;
int32_t b = 22;
printf("%d\n", 66);;
printf("%d\n", -61);;
printf("%d\n", b);;
printf("%d\n", (b / a) / b);;
int32_t c = b;
printf("%d\n", c);;
int32_t d = (b + (a + 71)) - -9;
printf("%d\n", a * a);;
printf("%d\n", 39 * b);;
int32_t e = c;
printf("%d\n", 62);;
printf("%d\n", e * d);;
printf("%d\n", d + 45);;
printf("%d\n", c / ((-20 * b) + c));;
printf("%d\n", -95);;
printf("%d\n", 15 / 1);;
printf("%d\n", -4);;
printf("%d\n", e);;
printf("%d\n", 23 + e);;
printf("%d\n", (33 * -20) * 37);;
int32_t f = 7;
printf("%d\n", ((d + 30) - (d - (b - c))) + -53);;
int32_t g = f - (26 + ((e - (47 + 50)) - (62 - c)));
printf("%d\n", -24);;
printf("%d\n", ((g - b) * 93) + -48);;
int32_t h = b;
printf("%d\n", f);;
int32_t i = b;
printf("%d\n", 33);;
printf("%d\n", 12);;
int32_t j = -22;
printf("%d\n", -16 * (-19 * -52));;
printf("%d\n", a);;
printf("%d\n", h);;
printf("%d\n", e - (-31 / (g + -60)));;
int32_t k = a;
printf("%d\n", 71 * 68);;
int32_t l = g;
printf("%d\n", (-28 + -10) * (h * (f / (b + -16))));;
printf("%d\n", j);;
int32_t m = f;
int32_t n = h + ((((l + h) - (l + 65)) + g) / (i - l));
printf("%d\n", 64);;
int32_t o = 4 + -63;
int32_t p = d * -18;
printf("%d\n", -37 / (-40 - l));;
printf("%d\n", -2);;
printf("%d\n", j);;
printf("%d\n", 58 + d);;
printf("%d\n", e);;
printf("%d\n", (j / (42 * d)) - (g - (c * c)));;
printf("%d\n", a);;
printf("%d\n", f);;
printf("%d\n", k + 99);;
printf("%d\n", o);;
printf("%d\n", a);;
int32_t q = (((g + c) - b) * 34) * (((n - (-20 - j)) + d) * -32);
printf("%d\n", k);;
int32_t r = 0;
int32_t s = 9;
printf("%d\n", s);;
printf("%d\n", -65);;
printf("%d\n", s);;
printf("%d\n", 26);;
printf("%d\n", f);;
printf("%d\n", -29);;
int32_t t = e;
printf("%d\n", s - ((-13 - (c * j)) - (61 + 9)));;
int32_t u = t;
printf("%d\n", ((((59 + 3) * (s + d)) - 7) * (4 / ((14 + 41) + (-39 + d)))) / -30);;
printf("%d\n", a - r);;
printf("%d\n", 13);;
int32_t v = 15;
printf("%d\n", 109);;
printf("%d\n", -53);;
int32_t w = a;
printf("%d\n", m + 64);;
printf("%d\n", 2);;
printf("%d\n", 6);;
printf("%d\n", 15);;
int32_t x = h;
printf("%d\n", 5);;
printf("%d\n", 64);;
printf("%d\n", 10 - g);;
printf("%d\n", x);;
printf("%d\n", -24);;
int32_t y = -56 * e;
int32_t z = c;
printf("%d\n", j);;
printf("%d\n", p - (k * (62 + j)));;
printf("%d\n", v);;
printf("%d\n", y);;
printf("%d\n", -66 * a);;
printf("%d\n", (p + 31) * 12);;
printf("%d\n", -15 + ((-70 - (7 - (y / s))) * (s / n)));;
int32_t aa = j;
int32_t ab = m + o;
printf("%d\n", o);;
printf("%d\n", -55 - ((p / h) * x));;
printf("%d\n", -5);;
int32_t ac = (d * (v * 39)) / ((19 / 14) + -53);
printf("%d\n", -42);;
printf("%d\n", r);;
printf("%d\n", y);;
printf("%d\n", ab);;
printf("%d\n", x);;
printf("%d\n", -17);;
printf("%d\n", 30);;
printf("%d\n", p);;
printf("%d\n", 38);;
printf("%d\n", z);;
printf("%d\n", -1);;
printf("%d\n", (g * o) / a);;
int32_t ad = (((ac + c) + b) * 9) * v;
printf("%d\n", 43 + 25);;
printf("%d\n", m - (-2 / (m * ((q * t) * ((((70 * 18) + -8) / ab) * m)))));;
int32_t ae = (52 / 40) * (x * (8 + p));
int32_t af = 12 - (ad / f);
printf("%d\n", -29);;
printf("%d\n", 19);;
int32_t ag = k;
printf("%d\n", 23);;
int32_t ah = 18;
printf("%d\n", l);;
int32_t ai = y;
printf("%d\n", 35);;
int32_t aj = -26 * 55;
int32_t ak = -20;
int32_t al = v;
printf("%d\n", 61);;
int32_t am = s + ((x * (n + j)) / ((c * q) + m));
printf("%d\n", 14);;
return 0;}