#include <stdint.h>
int main() {
printf("%d\n", 79 + 62);;
int32_t a = 18;
printf("%d\n", 47);;
printf("%d\n", 2);;
printf("%d\n", a);;
printf("%d\n", -88);;
printf("%d\n", a);;
printf("%d\n", ((-2 + a) - -14) - a);;
printf("%d\n", 31);;
printf("%d\n", -33);;
printf("%d\n", 38 + a);;
int32_t b = a;
printf("%d\n", -25);;
printf("%d\n", b);;
printf("%d\n", a);;
int32_t c = a;
printf("%d\n", 69);;
printf("%d\n", -29);;
printf("%d\n", b);;
printf("%d\n", c);;
printf("%d\n", ((((a - -42) - (1 * 46)) * (((((-25 / c) + b) * c) - b) * a)) * -20) * (7 - 57));;
printf("%d\n", -21);;
printf("%d\n", ((-9 - -79) / 36) * 13);;
printf("%d\n", -28);;
printf("%d\n", 24);;
printf("%d\n", -4);;
printf("%d\n", a);;
printf("%d\n", 14);;
printf("%d\n", a);;
printf("%d\n", b + 54);;
printf("%d\n", b);;
printf("%d\n", (-46 + (b - (-70 - (-30 - b)))) / 16);;
int32_t d = a;
printf("%d\n", 11);;
printf("%d\n", 3);;
printf("%d\n", -22);;
printf("%d\n", d);;
printf("%d\n", -28);;
printf("%d\n", d);;
printf("%d\n", 53);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", d);;
printf("%d\n", 33 - -8);;
return 0;}