#include <stdint.h>
int main() {
printf("%d\n", 23);;
printf("%d\n", -62 - -32);;
int32_t a = -54;
int32_t b = a;
int32_t c = -15;
int32_t d = c;
printf("%d\n", (35 / -34) * 8);;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", (((-66 + c) - (((a - (-51 / (d + 0))) + (d - 35)) - -62)) - 16) * -26);;
printf("%d\n", 17);;
printf("%d\n", 46);;
printf("%d\n", c);;
int32_t e = -76;
printf("%d\n", -9);;
printf("%d\n", a + c);;
printf("%d\n", b);;
printf("%d\n", b / ((b + e) + 42));;
printf("%d\n", (((116 - (16 + -15)) - 11) * 29) + (-23 - b));;
printf("%d\n", 34);;
int32_t f = a;
int32_t g = a;
printf("%d\n", 25 - ((39 / -53) - 6));;
int32_t h = e;
printf("%d\n", e * d);;
printf("%d\n", 40 / -26);;
printf("%d\n", -14);;
printf("%d\n", d);;
int32_t i = -32;
printf("%d\n", -5);;
printf("%d\n", 11);;
printf("%d\n", (i + h) + g);;
int32_t j = -6;
int32_t k = 44;
printf("%d\n", f);;
int32_t l = 12 / -18;
printf("%d\n", j);;
printf("%d\n", i + g);;
printf("%d\n", e);;
int32_t m = f;
printf("%d\n", 46);;
int32_t n = e;
printf("%d\n", 31);;
int32_t o = 58;
printf("%d\n", 60);;
printf("%d\n", i);;
printf("%d\n", -5);;
int32_t p = o;
printf("%d\n", 36);;
printf("%d\n", h);;
printf("%d\n", l);;
printf("%d\n", e);;
printf("%d\n", -35);;
printf("%d\n", b - d);;
printf("%d\n", 6);;
printf("%d\n", k);;
printf("%d\n", 21 - b);;
printf("%d\n", 45);;
printf("%d\n", e);;
printf("%d\n", 30 - (-9 / b));;
printf("%d\n", (g / 27) * p);;
printf("%d\n", (((a * n) * (l - c)) + 9) * g);;
printf("%d\n", 36 - l);;
return 0;}