#include <stdint.h>
int main() {
printf("%d\n", 110);;
printf("%d\n", ((-53 * 5) * 29) - -14);;
printf("%d\n", 27);;
printf("%d\n", 74 - 32);;
printf("%d\n", 75);;
printf("%d\n", (((22 + -22) + (((-101 - 39) + (-10 / 8)) * -43)) * 59) - -24);;
int32_t a = -45;
printf("%d\n", (a - (-13 - -1)) - 48);;
printf("%d\n", a);;
int32_t b = 21;
printf("%d\n", b);;
printf("%d\n", 60);;
printf("%d\n", 5);;
printf("%d\n", (((28 / a) - (-30 + a)) * a) * ((a / (b * b)) - a));;
printf("%d\n", 42 + (a - b));;
printf("%d\n", -18);;
printf("%d\n", 30 * b);;
printf("%d\n", -27);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t c = b;
printf("%d\n", a);;
printf("%d\n", -33);;
printf("%d\n", c);;
printf("%d\n", b - 47);;
printf("%d\n", a);;
int32_t d = 60 - c;
printf("%d\n", 5);;
printf("%d\n", 20);;
printf("%d\n", 35);;
int32_t e = -23;
printf("%d\n", 19 * e);;
printf("%d\n", -18);;
printf("%d\n", a);;
int32_t f = 34;
printf("%d\n", d / b);;
printf("%d\n", 103);;
printf("%d\n", e);;
printf("%d\n", 27);;
printf("%d\n", d);;
printf("%d\n", e);;
int32_t g = b;
printf("%d\n", 42);;
printf("%d\n", b);;
printf("%d\n", g);;
printf("%d\n", -81);;
printf("%d\n", g);;
printf("%d\n", b);;
printf("%d\n", f);;
printf("%d\n", 69);;
printf("%d\n", -12);;
int32_t h = (18 - (a + d)) + b;
printf("%d\n", f);;
printf("%d\n", 90 + (-82 * -83));;
printf("%d\n", g - 43);;
printf("%d\n", 52);;
printf("%d\n", e);;
printf("%d\n", -64);;
printf("%d\n", -47);;
printf("%d\n", -83);;
printf("%d\n", b);;
printf("%d\n", -7);;
printf("%d\n", d);;
printf("%d\n", 49);;
return 0;}