#include <stdint.h>
int main() {
printf("%d\n", 62);;
printf("%d\n", 24);;
printf("%d\n", -72);;
printf("%d\n", -30 * (-4 + 25));;
printf("%d\n", ((-15 + 20) - (-39 - -18)) * -22);;
int32_t a = 20;
printf("%d\n", 22 * 5);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 32 / -2);;
printf("%d\n", -5 - -8);;
printf("%d\n", a - (a + -1));;
printf("%d\n", 70);;
printf("%d\n", 6);;
printf("%d\n", 26);;
printf("%d\n", a);;
printf("%d\n", -13);;
printf("%d\n", 65);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 31 / ((-4 - (14 / 46)) - (-57 - (-55 + -28))));;
printf("%d\n", -2 - a);;
printf("%d\n", a);;
printf("%d\n", 11);;
int32_t b = a - -78;
int32_t c = -10;
printf("%d\n", 37);;
printf("%d\n", 1);;
int32_t d = b;
printf("%d\n", 42);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", (-20 + (b * d)) / d);;
printf("%d\n", 9);;
printf("%d\n", 76);;
int32_t e = 37 - b;
printf("%d\n", b);;
printf("%d\n", 8 + ((e - (((a / a) / -74) - (b - (a - -23)))) + 53));;
printf("%d\n", e);;
printf("%d\n", 16);;
printf("%d\n", c);;
printf("%d\n", 45);;
int32_t f = a + 75;
int32_t g = -19;
printf("%d\n", 82);;
printf("%d\n", 51);;
printf("%d\n", -10);;
int32_t h = 18;
printf("%d\n", g);;
printf("%d\n", (b - g) + -41);;
printf("%d\n", a);;
int32_t i = c;
printf("%d\n", -5);;
int32_t j = a;
printf("%d\n", d);;
int32_t k = 23;
printf("%d\n", 42);;
int32_t l = -19;
int32_t m = b;
int32_t n = 75;
printf("%d\n", (39 - (32 / (95 + (n + 72)))) * -70);;
printf("%d\n", 10);;
printf("%d\n", 76);;
printf("%d\n", b - k);;
return 0;}