#include <stdint.h>
int main() {
int32_t a = 33;
printf("%d\n", 59);;
int32_t b = a;
printf("%d\n", ((-35 / (-105 * 29)) - 32) * 28);;
printf("%d\n", ((b * (17 / 5)) - -24) - b);;
printf("%d\n", b * a);;
printf("%d\n", 38);;
printf("%d\n", -8);;
printf("%d\n", b);;
printf("%d\n", -7);;
printf("%d\n", a);;
printf("%d\n", -6 - 52);;
printf("%d\n", 59);;
int32_t c = -10 * 40;
printf("%d\n", 7);;
printf("%d\n", 50);;
printf("%d\n", b);;
printf("%d\n", a / -37);;
printf("%d\n", -3 / 32);;
printf("%d\n", 7);;
printf("%d\n", 60);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", 56);;
printf("%d\n", 2);;
printf("%d\n", -6);;
printf("%d\n", a - (c - a));;
printf("%d\n", b);;
int32_t d = a * (b - (a * (-32 * -41)));
printf("%d\n", -1);;
printf("%d\n", 38);;
int32_t e = 10 + b;
printf("%d\n", -20 - e);;
printf("%d\n", 38);;
printf("%d\n", a);;
printf("%d\n", 7 * 60);;
printf("%d\n", 43);;
printf("%d\n", (-7 * (20 - (a - -63))) + ((b + ((b * d) - (10 - c))) - e));;
printf("%d\n", (35 / (c * 1)) - d);;
int32_t f = (-31 * e) + 49;
printf("%d\n", 32);;
int32_t g = -35 / c;
printf("%d\n", -49);;
printf("%d\n", 23);;
printf("%d\n", e);;
int32_t h = 14 - (e - (-44 + 35));
printf("%d\n", -83);;
int32_t i = h;
printf("%d\n", a + 18);;
printf("%d\n", a - a);;
int32_t j = 9;
return 0;}