#include <stdint.h>
int main() {
int32_t a = 18;
printf("%d\n", 127);;
printf("%d\n", a / ((16 + -54) - a));;
printf("%d\n", a);;
printf("%d\n", 55);;
int32_t b = a - ((30 * a) * -1);
int32_t c = b;
int32_t d = (47 / (-23 - a)) - ((((-19 / ((a * a) - (-46 * (((((4 - b) - -5) + -16) - a) - -26)))) - (-13 - 27)) - 61) + 71);
printf("%d\n", a);;
int32_t e = -70;
printf("%d\n", e);;
printf("%d\n", e * ((-36 / (3 * e)) * (-17 / (d * e))));;
int32_t f = -25 + -17;
printf("%d\n", c / 65);;
printf("%d\n", f);;
printf("%d\n", c);;
int32_t g = b;
printf("%d\n", d);;
printf("%d\n", -18 + ((f * e) * (g - 15)));;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", -15);;
int32_t h = f * b;
printf("%d\n", d);;
printf("%d\n", d);;
int32_t i = f - 12;
printf("%d\n", i);;
printf("%d\n", i);;
printf("%d\n", 40 * (e - f));;
printf("%d\n", d);;
printf("%d\n", 64);;
printf("%d\n", g);;
printf("%d\n", 54);;
printf("%d\n", 79);;
int32_t j = 42;
printf("%d\n", -4 - (e * (c + j)));;
printf("%d\n", a / ((i * ((f - -33) - ((d / ((34 - (-69 / (102 * -8))) / 13)) - 6))) * d));;
printf("%d\n", d);;
printf("%d\n", f);;
printf("%d\n", 55 - 35);;
int32_t k = -58;
printf("%d\n", 65 + 43);;
printf("%d\n", -40 * -51);;
printf("%d\n", i);;
printf("%d\n", -15 / c);;
printf("%d\n", g);;
printf("%d\n", g);;
printf("%d\n", k);;
printf("%d\n", 63);;
printf("%d\n", -56 - -57);;
printf("%d\n", 67);;
int32_t l = a;
printf("%d\n", f);;
int32_t m = -67 * g;
printf("%d\n", (39 + -17) + -32);;
int32_t n = (12 / (g - -20)) + h;
printf("%d\n", -5);;
int32_t o = -19;
printf("%d\n", m * (g * 30));;
printf("%d\n", h);;
printf("%d\n", 109);;
printf("%d\n", -30);;
printf("%d\n", e);;
printf("%d\n", k);;
printf("%d\n", c);;
printf("%d\n", 108);;
printf("%d\n", b);;
printf("%d\n", d);;
return 0;}