#include <stdint.h>
int main() {
int32_t a = 22;
printf("%d\n", -13);;
int32_t b = a;
printf("%d\n", b);;
printf("%d\n", b - (-7 - a));;
int32_t c = b;
printf("%d\n", a - c);;
printf("%d\n", 20);;
printf("%d\n", b);;
printf("%d\n", 26 * (93 / a));;
printf("%d\n", b);;
printf("%d\n", 41 + 19);;
printf("%d\n", c);;
int32_t d = 7;
int32_t e = d;
printf("%d\n", (-12 - -27) + (a + ((11 / d) / -70)));;
printf("%d\n", (d - (2 - 3)) - 8);;
int32_t f = -5 - ((((-47 * b) - 102) + 5) + (-14 - c));
printf("%d\n", d);;
int32_t g = b;
int32_t h = -60;
int32_t i = 28 + c;
printf("%d\n", -82);;
printf("%d\n", c);;
printf("%d\n", 73 * 32);;
printf("%d\n", 50);;
int32_t j = d;
printf("%d\n", (a / f) - -16);;
printf("%d\n", 1);;
printf("%d\n", f - 1);;
printf("%d\n", 1);;
printf("%d\n", g);;
int32_t k = 7;
printf("%d\n", -63);;
printf("%d\n", 13);;
printf("%d\n", 55 * ((h + f) / 25));;
printf("%d\n", -82);;
printf("%d\n", d + j);;
printf("%d\n", b);;
int32_t l = i;
printf("%d\n", -19);;
printf("%d\n", (f - ((i / 16) - (-45 * 18))) - (((((42 - (h + ((i - c) - (d * d)))) + -1) / e) + -13) / 29));;
printf("%d\n", 54 - d);;
printf("%d\n", h + (-52 * 55));;
int32_t m = e;
printf("%d\n", 1);;
printf("%d\n", i - -13);;
printf("%d\n", m);;
printf("%d\n", 22 / g);;
int32_t n = b + ((d - (m / e)) - (m - i));
int32_t o = n;
printf("%d\n", -1);;
printf("%d\n", c);;
printf("%d\n", (o / ((-40 + o) + c)) / ((25 / (((o * n) * ((21 - d) - (-42 * 8))) * m)) - j));;
printf("%d\n", h);;
printf("%d\n", -82);;
printf("%d\n", e);;
printf("%d\n", 27);;
printf("%d\n", -9);;
printf("%d\n", g * (g + 27));;
printf("%d\n", -65);;
int32_t p = b;
printf("%d\n", 65);;
int32_t q = -1;
printf("%d\n", 18);;
printf("%d\n", (3 / e) - (-21 / (((d + m) - c) * 3)));;
printf("%d\n", a);;
printf("%d\n", -45);;
printf("%d\n", (e / 14) - (a - h));;
printf("%d\n", -2);;
printf("%d\n", -28);;
printf("%d\n", h);;
int32_t r = (53 - a) * h;
int32_t s = h;
int32_t t = -2;
int32_t u = s;
printf("%d\n", t + 61);;
printf("%d\n", m);;
printf("%d\n", 1);;
printf("%d\n", p);;
printf("%d\n", 28 * -19);;
printf("%d\n", e);;
int32_t v = b * -31;
printf("%d\n", 8);;
int32_t w = l * -20;
printf("%d\n", (p - 12) / (f - (-52 - (91 + 34))));;
printf("%d\n", o);;
return 0;}