#include <stdint.h>
int main() {
printf("%d\n", 14);;
int32_t a = ((35 * ((79 / (-54 * 62)) - (18 * (12 + 38)))) / -2) + 70;
printf("%d\n", 96 * -68);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", (a - a) - -3);;
printf("%d\n", ((-38 + a) * (69 - a)) + a);;
printf("%d\n", a);;
printf("%d\n", -2);;
printf("%d\n", -4);;
printf("%d\n", 48);;
printf("%d\n", a);;
printf("%d\n", a);;
int32_t b = a * (a / 22);
printf("%d\n", b);;
printf("%d\n", 17 * b);;
printf("%d\n", -10);;
printf("%d\n", a * -11);;
printf("%d\n", b);;
printf("%d\n", 13);;
int32_t c = b;
printf("%d\n", b);;
printf("%d\n", -14);;
printf("%d\n", c);;
printf("%d\n", -4);;
int32_t d = a;
printf("%d\n", b);;
int32_t e = -17 - d;
printf("%d\n", 15);;
printf("%d\n", -18);;
printf("%d\n", (c / (16 * e)) * (-6 - c));;
printf("%d\n", 97 / 3);;
printf("%d\n", -4 - a);;
printf("%d\n", 20);;
printf("%d\n", d);;
printf("%d\n", -22);;
printf("%d\n", b - (74 / c));;
printf("%d\n", -13);;
printf("%d\n", (-22 - 19) * (79 - d));;
printf("%d\n", 11);;
printf("%d\n", d);;
printf("%d\n", 39);;
printf("%d\n", (1 * (c * d)) - -21);;
int32_t f = e;
printf("%d\n", -13);;
int32_t g = -22;
int32_t h = a / c;
printf("%d\n", h);;
printf("%d\n", g);;
printf("%d\n", 56 * 21);;
printf("%d\n", -23 - 39);;
int32_t i = f;
printf("%d\n", (e + 48) / -10);;
return 0;}