#include <stdint.h>
int main() {
printf("%d\n", 18 - -9);;
printf("%d\n", 1);;
int32_t a = -87 / 3;
printf("%d\n", -14);;
int32_t b = -14;
printf("%d\n", a);;
printf("%d\n", b);;
int32_t c = a;
printf("%d\n", a);;
printf("%d\n", 49 - 39);;
int32_t d = b;
int32_t e = 30;
int32_t f = ((-13 / (c + b)) + (a - 55)) / 4;
int32_t g = f;
int32_t h = c - ((b + 3) - (-47 / (g * 39)));
printf("%d\n", (-22 + e) + (35 - -15));;
int32_t i = -5;
printf("%d\n", -62);;
int32_t j = 73;
printf("%d\n", b);;
printf("%d\n", -26);;
printf("%d\n", d * a);;
int32_t k = g;
printf("%d\n", f * (c + (-3 * (g - i))));;
printf("%d\n", j);;
printf("%d\n", e);;
printf("%d\n", -8);;
printf("%d\n", 4 + (139 * (k * -12)));;
printf("%d\n", -2);;
int32_t l = 29 * (83 + h);
printf("%d\n", g);;
printf("%d\n", (-39 - h) - 7);;
int32_t m = b;
printf("%d\n", -12 / (h / m));;
printf("%d\n", b);;
int32_t n = j + b;
printf("%d\n", 3);;
int32_t o = k;
printf("%d\n", -27);;
printf("%d\n", 61 / f);;
printf("%d\n", a * c);;
int32_t p = 59;
printf("%d\n", 20);;
int32_t q = h;
printf("%d\n", p / o);;
printf("%d\n", f);;
printf("%d\n", 17);;
printf("%d\n", b);;
printf("%d\n", -57 - h);;
int32_t r = o;
printf("%d\n", i);;
printf("%d\n", j);;
printf("%d\n", -13);;
printf("%d\n", p - -23);;
printf("%d\n", -78);;
printf("%d\n", a);;
printf("%d\n", -12 * 6);;
printf("%d\n", -1);;
printf("%d\n", p / -6);;
printf("%d\n", (-7 + 24) * -43);;
printf("%d\n", d);;
int32_t s = -3 / r;
printf("%d\n", 37 + a);;
printf("%d\n", q);;
printf("%d\n", e / -4);;
printf("%d\n", -50);;
printf("%d\n", 16);;
printf("%d\n", n);;
printf("%d\n", 31);;
int32_t t = 32 + (i - m);
int32_t u = s;
printf("%d\n", a);;
printf("%d\n", c / j);;
int32_t v = 41;
printf("%d\n", -1);;
int32_t w = -39 * q;
int32_t x = h;
printf("%d\n", l);;
printf("%d\n", o / k);;
printf("%d\n", -109);;
int32_t y = k;
int32_t z = -13;
int32_t aa = w;
printf("%d\n", 60 / (-3 - z));;
printf("%d\n", -26);;
printf("%d\n", d);;
printf("%d\n", 29);;
printf("%d\n", 3);;
printf("%d\n", t);;
printf("%d\n", ((g * k) - f) / x);;
int32_t ab = ((f / (t - -28)) - ((11 / ((p * p) * 41)) * 35)) / (30 * q);
int32_t ac = y;
printf("%d\n", y);;
printf("%d\n", ((-27 + 8) - 41) + -42);;
printf("%d\n", -77);;
printf("%d\n", d / -33);;
int32_t ad = 2 * u;
printf("%d\n", k);;
int32_t ae = l;
printf("%d\n", ((g - c) * t) / ae);;
return 0;}