#include <stdint.h>
int main() {
int32_t a = ((71 - ((-29 - ((-22 / 50) * -23)) + 13)) * -34) - -4;
printf("%d\n", 48);;
printf("%d\n", a);;
printf("%d\n", a / -54);;
printf("%d\n", (a - (a + a)) * -7);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a * (a - a));;
printf("%d\n", -68);;
printf("%d\n", 59);;
printf("%d\n", a);;
printf("%d\n", -5);;
printf("%d\n", 43);;
printf("%d\n", a);;
printf("%d\n", 18);;
int32_t b = -50 - a;
int32_t c = 23;
printf("%d\n", b - 56);;
printf("%d\n", c);;
printf("%d\n", 6);;
printf("%d\n", c);;
printf("%d\n", b + 37);;
printf("%d\n", 95);;
printf("%d\n", b - b);;
printf("%d\n", -58 - -64);;
printf("%d\n", a);;
printf("%d\n", 8 + (21 - (a * c)));;
printf("%d\n", b);;
printf("%d\n", b);;
int32_t d = -68;
printf("%d\n", b);;
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", -37);;
printf("%d\n", 91);;
printf("%d\n", 35);;
printf("%d\n", b);;
printf("%d\n", (c * (10 + (((((c * b) + ((((-10 + (-21 / a)) + (-11 - 116)) + (19 / c)) + 97)) * -49) + a) * -47))) * ((a * -12) + -27));;
printf("%d\n", 18);;
int32_t e = -6;
printf("%d\n", -23);;
printf("%d\n", a);;
printf("%d\n", b + a);;
printf("%d\n", a);;
printf("%d\n", a / -17);;
int32_t f = a;
int32_t g = 78;
printf("%d\n", d);;
printf("%d\n", d * g);;
printf("%d\n", -29);;
printf("%d\n", e / -13);;
printf("%d\n", ((d - (101 * (-46 / -17))) + 24) - e);;
printf("%d\n", d);;
printf("%d\n", d);;
printf("%d\n", 25);;
return 0;}