#include <stdint.h>
int main() {
printf("%d\n", 61);;
printf("%d\n", 39 / 42);;
printf("%d\n", -10);;
printf("%d\n", (((-36 - 64) / 3) * 63) / 2);;
printf("%d\n", 81);;
printf("%d\n", -24);;
int32_t a = 9;
printf("%d\n", a);;
printf("%d\n", ((a + -29) * a) - 8);;
printf("%d\n", 17);;
printf("%d\n", a * a);;
int32_t b = a;
printf("%d\n", a);;
int32_t c = 44;
int32_t d = -53;
printf("%d\n", c);;
printf("%d\n", c * (2 + d));;
int32_t e = -34;
printf("%d\n", 70);;
printf("%d\n", b + e);;
printf("%d\n", 12 + e);;
printf("%d\n", -16);;
printf("%d\n", (12 - a) + -11);;
printf("%d\n", -26 * (a / -68));;
int32_t f = d / (-33 + 59);
printf("%d\n", e);;
int32_t g = e;
printf("%d\n", (e * b) / (d / 27));;
printf("%d\n", 40);;
printf("%d\n", 47 - e);;
printf("%d\n", 131);;
printf("%d\n", c);;
printf("%d\n", f);;
printf("%d\n", b);;
int32_t h = a;
printf("%d\n", (-44 - -8) - (g / c));;
printf("%d\n", h);;
printf("%d\n", 10);;
printf("%d\n", -52);;
printf("%d\n", g);;
printf("%d\n", g);;
printf("%d\n", 50 * c);;
int32_t i = a - 24;
printf("%d\n", g);;
int32_t j = g * i;
printf("%d\n", f);;
printf("%d\n", j);;
printf("%d\n", g);;
printf("%d\n", 23);;
int32_t k = 45;
return 0;}