#include <stdint.h>
int main() {
int32_t a = 6 * -10;
printf("%d\n", a);;
printf("%d\n", 7 / a);;
int32_t b = a * 66;
printf("%d\n", a);;
printf("%d\n", -17);;
int32_t c = -79 - 1;
int32_t d = b;
int32_t e = a;
int32_t f = -29;
printf("%d\n", -14);;
int32_t g = 1;
int32_t h = 1 + (18 + c);
printf("%d\n", 8 + (f + b));;
int32_t i = b;
int32_t j = -4;
printf("%d\n", a);;
printf("%d\n", (135 + e) - (a / -3));;
printf("%d\n", -4);;
printf("%d\n", -1);;
printf("%d\n", f);;
int32_t k = h / b;
printf("%d\n", 4 / -26);;
printf("%d\n", -90);;
printf("%d\n", ((((d - 19) + ((23 - d) / e)) - (g * ((20 + 22) / 5))) - -5) - c);;
printf("%d\n", g);;
printf("%d\n", 35);;
printf("%d\n", a / 21);;
printf("%d\n", e);;
printf("%d\n", -32 * -9);;
printf("%d\n", 36);;
int32_t l = e;
int32_t m = d + -6;
printf("%d\n", (b + b) * -8);;
int32_t n = (47 * k) * h;
int32_t o = 40;
printf("%d\n", g);;
printf("%d\n", d);;
int32_t p = i;
printf("%d\n", n);;
int32_t q = 47 + -17;
int32_t r = (((-44 / -14) + ((n / a) * q)) / 60) + (28 * (-16 - 37));
printf("%d\n", c);;
printf("%d\n", j * r);;
printf("%d\n", j);;
int32_t s = 14;
printf("%d\n", f - s);;
printf("%d\n", k);;
return 0;}