#include <stdint.h>
int main() {
int32_t a = (-11 - 22) / 7;
printf("%d\n", a + 3);;
printf("%d\n", -24);;
printf("%d\n", a);;
printf("%d\n", -11 * 31);;
printf("%d\n", 1);;
int32_t b = 31;
printf("%d\n", b);;
int32_t c = (11 * a) + (-11 / b);
printf("%d\n", -17 - ((((-13 + 25) - b) + 49) + a));;
int32_t d = (11 / b) * ((-73 - -2) - b);
printf("%d\n", c * (b - ((-41 + d) - ((d - d) / 22))));;
printf("%d\n", b);;
printf("%d\n", ((d - 62) - 2) / a);;
int32_t e = 64;
int32_t f = 10;
printf("%d\n", 0);;
printf("%d\n", f + 32);;
printf("%d\n", -66);;
printf("%d\n", e);;
int32_t g = 7 - (d + 78);
int32_t h = b + 12;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", g);;
printf("%d\n", h);;
printf("%d\n", -1);;
int32_t i = f;
printf("%d\n", g * (-11 / 41));;
printf("%d\n", 24);;
printf("%d\n", 29 + ((27 + 9) * e));;
int32_t j = -88;
printf("%d\n", h);;
printf("%d\n", e + b);;
printf("%d\n", 66);;
int32_t k = 8;
int32_t l = k * (69 - ((k - g) + k));
printf("%d\n", k - (a * (-29 * 0)));;
printf("%d\n", 52);;
printf("%d\n", d * (d + 68));;
printf("%d\n", d);;
printf("%d\n", 14);;
printf("%d\n", -36 / (j * j));;
printf("%d\n", 20);;
printf("%d\n", b / h);;
printf("%d\n", g / j);;
int32_t m = 77 + l;
printf("%d\n", -71 - (j * -30));;
printf("%d\n", -5 / k);;
int32_t n = c - 30;
printf("%d\n", -39 / (((b + (-10 * k)) + c) + (k - ((14 + f) / (18 - (i - -41))))));;
printf("%d\n", n);;
printf("%d\n", -41);;
printf("%d\n", n);;
int32_t o = f - -21;
printf("%d\n", 15);;
printf("%d\n", -3 * (c - ((((-6 - o) * 34) * 50) - (j * l))));;
return 0;}