#include <stdint.h>
int main() {
int32_t a = 26;
printf("%d\n", a);;
int32_t b = a;
int32_t c = b - ((a - 27) * b);
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", -60);;
printf("%d\n", 3 * (35 * (a * c)));;
printf("%d\n", c);;
printf("%d\n", -9);;
printf("%d\n", 26);;
printf("%d\n", 35 - 52);;
printf("%d\n", (-20 / 17) + ((c * (36 + 0)) * 67));;
printf("%d\n", (a - a) * -13);;
printf("%d\n", 47 / (-31 - 43));;
printf("%d\n", (-42 * 47) * a);;
printf("%d\n", c);;
printf("%d\n", 54);;
printf("%d\n", c);;
int32_t d = c;
printf("%d\n", d);;
printf("%d\n", 48 / d);;
printf("%d\n", 4);;
printf("%d\n", 65 + (6 + c));;
printf("%d\n", 12);;
printf("%d\n", b - -12);;
printf("%d\n", (d - 52) - 21);;
int32_t e = d;
printf("%d\n", -6);;
printf("%d\n", (e / (c / (e - b))) * (8 - 21));;
printf("%d\n", -42 * (8 * (e - (d - 87))));;
printf("%d\n", -41);;
printf("%d\n", b);;
printf("%d\n", 55 - e);;
printf("%d\n", (((24 / (0 + c)) * -1) * (e * ((d - b) / -58))) / (a - ((e + -59) + 77)));;
int32_t f = a;
printf("%d\n", c);;
printf("%d\n", (a - b) + e);;
printf("%d\n", -7);;
int32_t g = -11 * 18;
printf("%d\n", 45);;
int32_t h = e;
printf("%d\n", d);;
printf("%d\n", b / b);;
printf("%d\n", -5 / (c - f));;
printf("%d\n", 25 - (-32 / e));;
printf("%d\n", d);;
printf("%d\n", -19);;
printf("%d\n", g);;
printf("%d\n", 52 - e);;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", 8);;
printf("%d\n", -56);;
printf("%d\n", 19);;
int32_t i = b;
printf("%d\n", (g * c) * 16);;
printf("%d\n", b);;
int32_t j = d;
printf("%d\n", h);;
printf("%d\n", -5);;
printf("%d\n", c);;
printf("%d\n", h);;
printf("%d\n", (((17 * (20 - b)) - -19) * ((-23 + (29 - 42)) * 23)) / h);;
printf("%d\n", e + -6);;
printf("%d\n", (((g + c) - i) + b) / i);;
printf("%d\n", f);;
int32_t k = -26 - -9;
printf("%d\n", 36);;
printf("%d\n", 77 - (h - 40));;
printf("%d\n", (17 + (4 / (34 - -3))) + -4);;
int32_t l = i;
printf("%d\n", 59);;
printf("%d\n", 40);;
printf("%d\n", d);;
int32_t m = f;
return 0;}