#include <stdint.h>
int main() {
printf("%d\n", 76 * (-97 + 16));;
int32_t a = -1 + -30;
int32_t b = -1;
printf("%d\n", -3);;
printf("%d\n", b);;
int32_t c = -11;
printf("%d\n", -35);;
int32_t d = 95 / c;
printf("%d\n", 87 - c);;
int32_t e = 58;
printf("%d\n", a);;
int32_t f = 17;
printf("%d\n", c);;
printf("%d\n", 8);;
printf("%d\n", -56);;
printf("%d\n", -15);;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", b * (f + -13));;
int32_t g = 76;
printf("%d\n", ((a - -3) * c) * e);;
printf("%d\n", -13 + (((c - (((-25 / b) / 3) * -5)) / (a - (b / (d / -3)))) - b));;
printf("%d\n", f * 9);;
printf("%d\n", -5);;
int32_t h = d;
printf("%d\n", 15);;
printf("%d\n", c);;
int32_t i = 91;
printf("%d\n", (((h - 2) - d) - ((c + -1) / (2 + 55))) - b);;
int32_t j = g;
printf("%d\n", g + b);;
int32_t k = c;
printf("%d\n", e * ((17 - 27) / (14 * -8)));;
printf("%d\n", 6 / h);;
printf("%d\n", b);;
printf("%d\n", 48);;
printf("%d\n", -78);;
printf("%d\n", 0);;
printf("%d\n", -10);;
printf("%d\n", b);;
printf("%d\n", 80);;
printf("%d\n", (d / (f - b)) + (d / d));;
printf("%d\n", -17);;
printf("%d\n", 35);;
printf("%d\n", 36);;
printf("%d\n", g / e);;
printf("%d\n", -7);;
printf("%d\n", a);;
printf("%d\n", -2 / d);;
printf("%d\n", 8);;
printf("%d\n", 44);;
printf("%d\n", k);;
printf("%d\n", -44 - 16);;
printf("%d\n", -83);;
printf("%d\n", 11);;
printf("%d\n", 30 + (a * 10));;
printf("%d\n", 10 - -6);;
int32_t l = i;
printf("%d\n", 61 / f);;
printf("%d\n", g);;
printf("%d\n", a * g);;
printf("%d\n", k);;
printf("%d\n", b);;
int32_t m = j / (((5 + i) * 21) * b);
printf("%d\n", 3);;
int32_t n = i;
printf("%d\n", -29);;
int32_t o = 75;
printf("%d\n", -47);;
printf("%d\n", ((-30 * (-7 - f)) - (o - ((((49 + -24) * (f + a)) - (34 - (c * 20))) * 45))) - (0 - l));;
printf("%d\n", 24);;
printf("%d\n", 68 * 4);;
printf("%d\n", h);;
int32_t p = m;
printf("%d\n", 18);;
printf("%d\n", j + (-1 * (p - (d - (22 * n)))));;
return 0;}