#include <stdint.h>
int main() {
printf("%d\n", -26);;
int32_t a = 17;
printf("%d\n", 8 / 33);;
printf("%d\n", -21);;
printf("%d\n", a - 25);;
int32_t b = 12;
printf("%d\n", a);;
printf("%d\n", b);;
printf("%d\n", a * 17);;
printf("%d\n", -101 / b);;
int32_t c = (3 + 99) + 30;
printf("%d\n", 2);;
printf("%d\n", c);;
printf("%d\n", a);;
int32_t d = (((a + 70) + -1) * -53) * -10;
printf("%d\n", b / (10 - -30));;
printf("%d\n", b);;
printf("%d\n", b);;
int32_t e = 79;
printf("%d\n", 2);;
printf("%d\n", d);;
printf("%d\n", 41 / 9);;
int32_t f = 2;
int32_t g = -64;
printf("%d\n", -7);;
int32_t h = 49;
printf("%d\n", ((f + -64) * e) / -15);;
printf("%d\n", 48);;
printf("%d\n", 26 + (-28 * ((78 / -44) + ((15 / 52) / 25))));;
printf("%d\n", g);;
int32_t i = f;
printf("%d\n", 2 / (g / -31));;
printf("%d\n", b + 25);;
printf("%d\n", c);;
printf("%d\n", 67 * (12 * g));;
printf("%d\n", c);;
printf("%d\n", 46);;
printf("%d\n", c);;
printf("%d\n", (-26 + 89) * ((a * e) / ((((i + -51) * c) / ((((i - g) / -15) + -49) * (c + -9))) + e)));;
printf("%d\n", b);;
printf("%d\n", d);;
int32_t j = c;
printf("%d\n", -69 - (c / c));;
int32_t k = 24;
printf("%d\n", e);;
int32_t l = h;
printf("%d\n", (f + b) / (k / i));;
printf("%d\n", 0);;
printf("%d\n", 12 * ((l + ((7 + (47 + a)) - (-17 + f))) - -22));;
printf("%d\n", b);;
printf("%d\n", b - (j / (7 + 56)));;
int32_t m = b;
int32_t n = -4;
printf("%d\n", -28);;
printf("%d\n", -101);;
printf("%d\n", -11);;
return 0;}