#include <stdint.h>
int main() {
printf("%d\n", 9 - ((67 + ((-52 - 45) - 104)) + -18));;
int32_t a = 29 - 69;
printf("%d\n", 23);;
printf("%d\n", a);;
printf("%d\n", 35);;
printf("%d\n", a);;
int32_t b = -36 / -33;
printf("%d\n", b);;
int32_t c = a;
int32_t d = 43;
printf("%d\n", b / 61);;
printf("%d\n", 12 + d);;
printf("%d\n", 6);;
printf("%d\n", d / -131);;
int32_t e = -60;
printf("%d\n", -8);;
printf("%d\n", 29 * a);;
printf("%d\n", a);;
printf("%d\n", d);;
printf("%d\n", b + ((53 / d) * e));;
int32_t f = -20;
printf("%d\n", 5);;
printf("%d\n", (0 / (76 - (((-16 - a) / d) - a))) - (27 + c));;
printf("%d\n", e);;
printf("%d\n", -7);;
printf("%d\n", e);;
int32_t g = -26;
printf("%d\n", d - 23);;
printf("%d\n", g);;
int32_t h = f + c;
printf("%d\n", e);;
printf("%d\n", g);;
printf("%d\n", (h + a) + ((26 * 3) / -28));;
printf("%d\n", ((f - ((b * (22 + 54)) * ((66 + (48 * d)) - c))) + c) * ((a * (((a / -31) / b) / 61)) * b));;
printf("%d\n", a);;
printf("%d\n", 6);;
printf("%d\n", -83 - 38);;
printf("%d\n", e);;
printf("%d\n", g);;
printf("%d\n", 8 + (f / (d + g)));;
printf("%d\n", -30);;
printf("%d\n", 32);;
printf("%d\n", a + (45 - -34));;
printf("%d\n", (f / 65) + g);;
printf("%d\n", -45 * f);;
printf("%d\n", 25);;
return 0;}