#include <stdint.h>
int main() {
printf("%d\n", (-4 + (28 + 23)) * ((-8 / ((41 + -29) - -31)) - 26));;
printf("%d\n", 38);;
printf("%d\n", 14);;
int32_t a = 4;
printf("%d\n", -67 + a);;
printf("%d\n", 1);;
printf("%d\n", -42);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", -30);;
int32_t b = -35;
printf("%d\n", 32);;
int32_t c = b;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", b - (((a / 19) * ((c + b) - a)) + b));;
printf("%d\n", c);;
int32_t d = (a + b) + b;
printf("%d\n", (-31 / (5 - (73 + (b - (22 - c))))) * a);;
printf("%d\n", (-33 + (-23 / -23)) + b);;
printf("%d\n", c);;
printf("%d\n", -40);;
printf("%d\n", -34);;
printf("%d\n", d);;
int32_t e = b * 16;
printf("%d\n", 33);;
int32_t f = 19;
printf("%d\n", -32);;
printf("%d\n", 45);;
printf("%d\n", 14);;
printf("%d\n", (a - (f / (((e + -7) - 29) + c))) / (b + c));;
printf("%d\n", c - -28);;
printf("%d\n", ((e * -75) + (a / f)) - c);;
int32_t g = a;
int32_t h = (((31 / 12) - 75) + e) / 55;
printf("%d\n", f);;
printf("%d\n", c / 3);;
printf("%d\n", -30);;
printf("%d\n", 31 * a);;
printf("%d\n", 28 + g);;
printf("%d\n", 6);;
printf("%d\n", e);;
printf("%d\n", (-41 * h) + -23);;
printf("%d\n", -2);;
int32_t i = d;
printf("%d\n", i);;
printf("%d\n", d);;
printf("%d\n", (((b / 42) - -48) + -37) * (((59 / f) + b) + f));;
printf("%d\n", -28 * -26);;
printf("%d\n", -13 / -12);;
printf("%d\n", 90);;
printf("%d\n", f + d);;
printf("%d\n", -14);;
int32_t j = 50;
printf("%d\n", 11);;
printf("%d\n", b);;
printf("%d\n", -19);;
printf("%d\n", 52);;
printf("%d\n", -83);;
printf("%d\n", a);;
int32_t k = 2;
printf("%d\n", 0 + j);;
printf("%d\n", 63);;
int32_t l = b / (f * e);
printf("%d\n", b);;
int32_t m = 50 / 31;
printf("%d\n", ((-25 - i) + k) + (b - 54));;
printf("%d\n", d);;
printf("%d\n", -29);;
printf("%d\n", 88 / 47);;
printf("%d\n", k + (c + (j + 61)));;
return 0;}