#include <stdint.h>
int main() {
int32_t a = (82 / (2 * ((-25 * -9) - -37))) + -17;
printf("%d\n", a * a);;
printf("%d\n", -64);;
int32_t b = 13;
printf("%d\n", (13 / (14 * 37)) / a);;
printf("%d\n", b);;
printf("%d\n", -59 - -2);;
int32_t c = -22;
int32_t d = ((b + a) / a) / a;
printf("%d\n", a);;
int32_t e = 2;
printf("%d\n", 21);;
printf("%d\n", -24);;
printf("%d\n", -28);;
int32_t f = 37 + (-35 / (40 * (a + ((c * 20) + d))));
printf("%d\n", d);;
printf("%d\n", c);;
printf("%d\n", 2);;
int32_t g = e;
int32_t h = -23;
int32_t i = d;
int32_t j = a + -12;
printf("%d\n", -31 + h);;
printf("%d\n", d);;
printf("%d\n", 23);;
printf("%d\n", 11 - i);;
printf("%d\n", f);;
printf("%d\n", 147);;
printf("%d\n", 71);;
printf("%d\n", c);;
printf("%d\n", h);;
printf("%d\n", a);;
int32_t k = 73;
printf("%d\n", 9);;
printf("%d\n", g / 4);;
int32_t l = f;
int32_t m = (k / e) * (2 / (-60 - 16));
printf("%d\n", m);;
printf("%d\n", i);;
printf("%d\n", a - k);;
printf("%d\n", 57);;
printf("%d\n", 20);;
printf("%d\n", 6);;
printf("%d\n", (l * (c / -6)) - 33);;
printf("%d\n", 97);;
int32_t n = 4;
int32_t o = 8;
printf("%d\n", d * m);;
printf("%d\n", h);;
printf("%d\n", j - j);;
int32_t p = 22;
int32_t q = -9 * (l - ((k + 49) / (n * (((2 + -26) / g) / -10))));
int32_t r = c;
printf("%d\n", -61);;
printf("%d\n", (n + (9 - (23 + -19))) * c);;
printf("%d\n", -45);;
printf("%d\n", n);;
printf("%d\n", i + (e - i));;
printf("%d\n", -5);;
printf("%d\n", a);;
printf("%d\n", 38 / -10);;
int32_t s = g;
int32_t t = p;
printf("%d\n", 6);;
printf("%d\n", -65 / (53 + 50));;
int32_t u = b;
int32_t v = 37;
printf("%d\n", 61);;
printf("%d\n", -20 - (v * t));;
printf("%d\n", (g + -27) / -26);;
printf("%d\n", 37);;
printf("%d\n", 14);;
int32_t w = 14;
printf("%d\n", m - e);;
printf("%d\n", -45);;
int32_t x = k;
int32_t y = m;
printf("%d\n", e / f);;
printf("%d\n", -26);;
printf("%d\n", u);;
printf("%d\n", f);;
int32_t z = -10;
int32_t aa = y;
printf("%d\n", t);;
printf("%d\n", f);;
printf("%d\n", -50 - r);;
printf("%d\n", ((k / -7) * 30) - 31);;
printf("%d\n", 18);;
printf("%d\n", a);;
printf("%d\n", 65 - 49);;
printf("%d\n", 28);;
printf("%d\n", d);;
int32_t ab = h;
printf("%d\n", o / -48);;
printf("%d\n", m + 71);;
int32_t ac = a - 4;
printf("%d\n", y / 35);;
printf("%d\n", 50);;
printf("%d\n", b);;
printf("%d\n", -27);;
printf("%d\n", q * (-44 - m));;
printf("%d\n", 81);;
printf("%d\n", -46);;
printf("%d\n", 50 / t);;
printf("%d\n", g * s);;
int32_t ad = i;
printf("%d\n", -71);;
printf("%d\n", y);;
printf("%d\n", g);;
printf("%d\n", r);;
printf("%d\n", n);;
printf("%d\n", -40);;
printf("%d\n", u);;
int32_t ae = -27 / 57;
printf("%d\n", x);;
printf("%d\n", ((-55 / t) - (35 * 74)) + (y + 14));;
printf("%d\n", (34 - (27 * (31 - t))) / ((b - aa) - -18));;
int32_t af = s;
printf("%d\n", 2 - 3);;
printf("%d\n", d + y);;
printf("%d\n", 45 - ((22 * -36) * d));;
printf("%d\n", y);;
printf("%d\n", -9);;
int32_t ag = j;
int32_t ah = 154;
printf("%d\n", 62);;
printf("%d\n", 16);;
printf("%d\n", w);;
printf("%d\n", -12 * i);;
printf("%d\n", ad);;
printf("%d\n", 24);;
printf("%d\n", l - 65);;
printf("%d\n", q * 62);;
printf("%d\n", -72);;
printf("%d\n", 12);;
int32_t ai = u;
printf("%d\n", 34);;
printf("%d\n", l - (k - (f - 42)));;
int32_t aj = q;
int32_t ak = 1;
printf("%d\n", 54);;
printf("%d\n", u / (54 * ((-23 - ae) * 33)));;
int32_t al = -7 + (17 / 76);
int32_t am = s;
int32_t an = -9;
printf("%d\n", g);;
int32_t ao = q;
printf("%d\n", w);;
printf("%d\n", -46 * (d * (g * ae)));;
int32_t ap = 10;
printf("%d\n", h - -18);;
printf("%d\n", ai);;
printf("%d\n", ad);;
int32_t aq = 73;
int32_t ar = j;
printf("%d\n", 14 + 100);;
printf("%d\n", -57);;
printf("%d\n", 104);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", 3 * aj);;
printf("%d\n", -27);;
return 0;}