#include <stdint.h>
int main() {
printf("%d\n", 42);;
printf("%d\n", 41);;
printf("%d\n", 61);;
printf("%d\n", -3);;
printf("%d\n", -43);;
int32_t a = -13;
printf("%d\n", -42);;
printf("%d\n", -3);;
int32_t b = -51 / -29;
printf("%d\n", a);;
printf("%d\n", -32);;
printf("%d\n", (a / a) + (-18 + a));;
printf("%d\n", a - -31);;
int32_t c = 19;
int32_t d = a - -16;
printf("%d\n", a + (b / 2));;
int32_t e = 36;
printf("%d\n", d);;
printf("%d\n", e);;
printf("%d\n", (-32 + a) - ((1 / ((((-71 + (-54 - 37)) + a) - c) * (b + (b + ((128 - b) + 87))))) * 23));;
printf("%d\n", -42);;
printf("%d\n", e - (-6 - a));;
printf("%d\n", -11 - (b / (c + 33)));;
printf("%d\n", -17);;
printf("%d\n", a);;
printf("%d\n", 32 - 8);;
int32_t f = 40;
printf("%d\n", -47 - c);;
printf("%d\n", (-47 - 64) * e);;
printf("%d\n", -8);;
printf("%d\n", 50);;
printf("%d\n", (-25 * a) * a);;
printf("%d\n", -46);;
printf("%d\n", f - 13);;
int32_t g = -47;
printf("%d\n", a);;
printf("%d\n", b - g);;
printf("%d\n", -13);;
printf("%d\n", b);;
printf("%d\n", -24);;
printf("%d\n", 20 / g);;
printf("%d\n", a);;
int32_t h = a;
int32_t i = 36;
printf("%d\n", d);;
int32_t j = -25;
return 0;}