#include <stdint.h>
int main() {
printf("%d\n", -47 * (-142 / -35));;
int32_t a = 34;
printf("%d\n", 19 * 6);;
int32_t b = a;
printf("%d\n", -51);;
printf("%d\n", -26 - (a * 43));;
int32_t c = 47 + -1;
printf("%d\n", c);;
printf("%d\n", -7);;
printf("%d\n", 31);;
printf("%d\n", 1);;
printf("%d\n", b);;
printf("%d\n", 27);;
printf("%d\n", c);;
printf("%d\n", -15);;
int32_t d = c;
printf("%d\n", a);;
int32_t e = c;
printf("%d\n", (e + -32) * c);;
printf("%d\n", b);;
int32_t f = b;
printf("%d\n", 7 + -27);;
printf("%d\n", 22);;
printf("%d\n", d);;
printf("%d\n", 30);;
printf("%d\n", d);;
int32_t g = c;
int32_t h = 32;
int32_t i = 39;
printf("%d\n", 38 / a);;
printf("%d\n", d);;
printf("%d\n", -12);;
printf("%d\n", i);;
printf("%d\n", -35);;
int32_t j = -9;
printf("%d\n", i);;
printf("%d\n", 10);;
printf("%d\n", g);;
int32_t k = -17;
printf("%d\n", f);;
printf("%d\n", i);;
printf("%d\n", 74);;
printf("%d\n", -33);;
int32_t l = ((17 / a) / (h + (h + ((((10 / (h + ((-75 * (h + (((-35 - -6) - e) - e))) - 102))) + (((63 * (9 * ((-75 - j) + c))) - b) / g)) - k) + (d * (-7 - ((-9 + b) * g))))))) / 27;
printf("%d\n", f);;
printf("%d\n", c + a);;
int32_t m = 43 + g;
printf("%d\n", i);;
printf("%d\n", 27);;
printf("%d\n", e);;
printf("%d\n", f);;
int32_t n = ((68 * k) + 33) - -83;
printf("%d\n", (k - (-15 * 46)) + ((-51 - (h * f)) - (g / (d * g))));;
printf("%d\n", h / (105 + e));;
printf("%d\n", ((((((l - j) - (j / -11)) / i) + 67) + (-34 - i)) - 45) + 9);;
printf("%d\n", -8);;
printf("%d\n", -21);;
printf("%d\n", 39 - (i - -13));;
printf("%d\n", -36);;
int32_t o = -22;
printf("%d\n", h);;
printf("%d\n", f * c);;
printf("%d\n", 8);;
printf("%d\n", e);;
printf("%d\n", -11);;
printf("%d\n", 69 - 73);;
return 0;}