#include <stdint.h>
int main() {
int32_t a = 52;
int32_t b = a;
printf("%d\n", b);;
int32_t c = b - (((((18 + 8) - ((-18 + 41) / b)) / b) - -22) * (14 + (48 - b)));
printf("%d\n", c);;
printf("%d\n", 51);;
printf("%d\n", (c + 41) / a);;
printf("%d\n", (a - 16) * -52);;
int32_t d = -30;
printf("%d\n", a);;
printf("%d\n", -39 * (36 / -10));;
int32_t e = a;
printf("%d\n", 55);;
printf("%d\n", 6);;
printf("%d\n", -57);;
printf("%d\n", -55);;
printf("%d\n", 16);;
printf("%d\n", 17);;
printf("%d\n", b);;
printf("%d\n", 48);;
printf("%d\n", (a + 18) / (-31 * c));;
printf("%d\n", 55);;
int32_t f = -45 / -35;
printf("%d\n", 39);;
int32_t g = (b * (d - b)) + 79;
printf("%d\n", d);;
printf("%d\n", 42);;
int32_t h = (b * (d / -10)) / -59;
printf("%d\n", g);;
printf("%d\n", h);;
printf("%d\n", a * e);;
printf("%d\n", e);;
printf("%d\n", -46 / g);;
printf("%d\n", d);;
printf("%d\n", 42 + e);;
int32_t i = c;
printf("%d\n", 32 / -26);;
printf("%d\n", 33 / c);;
int32_t j = c;
int32_t k = f;
int32_t l = -29 + 97;
int32_t m = l;
printf("%d\n", k);;
printf("%d\n", 8);;
int32_t n = 32 - a;
printf("%d\n", i);;
printf("%d\n", 46 / (9 - 50));;
int32_t o = d;
printf("%d\n", 34);;
printf("%d\n", j);;
int32_t p = n;
printf("%d\n", (1 / 21) * -37);;
printf("%d\n", d);;
int32_t q = 5;
int32_t r = 32;
printf("%d\n", j);;
int32_t s = a;
printf("%d\n", m);;
printf("%d\n", -41);;
printf("%d\n", 40);;
int32_t t = 29;
printf("%d\n", -10);;
int32_t u = o;
printf("%d\n", j);;
printf("%d\n", l);;
printf("%d\n", r);;
int32_t v = -35;
printf("%d\n", 21);;
printf("%d\n", -17);;
return 0;}