#include <stdint.h>
int main() {
printf("%d\n", (9 * 52) / -37);;
printf("%d\n", ((-59 + 92) * ((-6 + ((-13 + -9) - 14)) + (((-33 - (-20 * 11)) + -28) / (11 + (-5 / (-51 - (26 / 59))))))) + (-42 / -49));;
int32_t a = 14;
printf("%d\n", -27);;
int32_t b = 8 - a;
int32_t c = (((-11 - b) / 32) - b) * b;
printf("%d\n", c);;
printf("%d\n", ((((7 * 14) * b) * (60 / (23 + (27 / -20)))) - b) - (a + -15));;
printf("%d\n", -58 + c);;
printf("%d\n", 27);;
int32_t d = 25;
int32_t e = a * -28;
printf("%d\n", -36);;
int32_t f = 36;
printf("%d\n", -37);;
printf("%d\n", -8);;
printf("%d\n", 1);;
int32_t g = 73;
printf("%d\n", -15);;
printf("%d\n", -29);;
int32_t h = f / f;
printf("%d\n", 24 * ((d / b) + b));;
printf("%d\n", 59);;
int32_t i = b;
int32_t j = 33;
printf("%d\n", c);;
printf("%d\n", b);;
printf("%d\n", ((-32 + 42) / -59) - h);;
printf("%d\n", 4);;
printf("%d\n", 93);;
printf("%d\n", 44);;
printf("%d\n", 6);;
printf("%d\n", b);;
int32_t k = f / (60 - g);
printf("%d\n", j / -34);;
printf("%d\n", (7 / g) * 35);;
printf("%d\n", 65);;
printf("%d\n", f + 25);;
int32_t l = (-42 / -33) - 42;
int32_t m = 40;
printf("%d\n", 62);;
printf("%d\n", (b + (f * i)) - -2);;
printf("%d\n", (h / 23) * 27);;
printf("%d\n", i);;
printf("%d\n", -24 / -16);;
int32_t n = ((j - -29) / 25) + (-22 / d);
int32_t o = 52;
printf("%d\n", h);;
printf("%d\n", (-20 * m) * 2);;
printf("%d\n", l);;
printf("%d\n", -15);;
printf("%d\n", 14);;
printf("%d\n", f);;
printf("%d\n", l);;
int32_t p = 24;
printf("%d\n", k);;
printf("%d\n", -36);;
int32_t q = ((71 + m) - o) - 29;
printf("%d\n", -8);;
int32_t r = 5 * -32;
printf("%d\n", j + c);;
printf("%d\n", m);;
int32_t s = 37;
printf("%d\n", -62);;
printf("%d\n", f);;
int32_t t = 17;
printf("%d\n", n);;
printf("%d\n", 46 / (-29 - (-4 * ((h + r) - a))));;
printf("%d\n", j);;
int32_t u = b;
printf("%d\n", 10 / f);;
printf("%d\n", g);;
printf("%d\n", u);;
printf("%d\n", l * k);;
printf("%d\n", 17);;
printf("%d\n", 29 / u);;
printf("%d\n", -14 - k);;
int32_t v = (d + r) / t;
int32_t w = -35;
int32_t x = 75;
printf("%d\n", -16);;
printf("%d\n", 74);;
printf("%d\n", -3);;
int32_t y = a;
printf("%d\n", 4);;
printf("%d\n", 11);;
printf("%d\n", 9);;
int32_t z = (-24 / ((28 * -51) - 94)) + -17;
printf("%d\n", 0);;
printf("%d\n", 15 + -12);;
printf("%d\n", w / (((-20 - 4) + k) - d));;
int32_t aa = (13 - -32) * w;
printf("%d\n", q);;
printf("%d\n", r);;
int32_t ab = f - 39;
int32_t ac = 109 + (k - aa);
printf("%d\n", u);;
printf("%d\n", k);;
printf("%d\n", 38);;
printf("%d\n", 26);;
printf("%d\n", 42 + 44);;
printf("%d\n", q - (((16 * p) - ((((23 - h) + -22) + ((-12 - z) / ac)) + 46)) + -73));;
printf("%d\n", s);;
printf("%d\n", 48 - (p + v));;
printf("%d\n", 24);;
printf("%d\n", (((((w * x) + (n - (ac - s))) * r) * -48) * 30) * z);;
printf("%d\n", 3);;
printf("%d\n", -29 - (-76 - -45));;
printf("%d\n", t);;
printf("%d\n", 6);;
printf("%d\n", q - p);;
printf("%d\n", e);;
printf("%d\n", w);;
printf("%d\n", 28 - 9);;
int32_t ad = j;
printf("%d\n", b);;
int32_t ae = w;
int32_t af = 20;
printf("%d\n", -27);;
printf("%d\n", p);;
printf("%d\n", -9);;
printf("%d\n", z * 21);;
int32_t ag = 43;
printf("%d\n", j + (c + -30));;
printf("%d\n", -25);;
printf("%d\n", ag);;
printf("%d\n", d);;
printf("%d\n", 57 + (z * -45));;
printf("%d\n", u);;
printf("%d\n", d);;
printf("%d\n", y);;
printf("%d\n", -2);;
printf("%d\n", l);;
int32_t ah = j;
printf("%d\n", d);;
printf("%d\n", aa);;
printf("%d\n", 83);;
printf("%d\n", x);;
printf("%d\n", 8);;
int32_t ai = (i + i) - -51;
int32_t aj = d - r;
int32_t ak = -32 / (s * ab);
printf("%d\n", 11 - (-3 + (-9 + aj)));;
printf("%d\n", w);;
printf("%d\n", m / (33 * -15));;
printf("%d\n", -7 - (-10 - x));;
int32_t al = -24;
printf("%d\n", aa);;
int32_t am = g + v;
printf("%d\n", ai);;
printf("%d\n", af + (-25 - (65 / n)));;
printf("%d\n", -1);;
int32_t an = ((aj - 12) / a) - -7;
printf("%d\n", 39);;
printf("%d\n", c);;
int32_t ao = j;
printf("%d\n", f);;
int32_t ap = -13;
printf("%d\n", ab);;
printf("%d\n", af);;
printf("%d\n", -25 + (((o / y) / (30 * 67)) + -36));;
int32_t aq = 35;
printf("%d\n", ak);;
printf("%d\n", m * (29 - -26));;
int32_t ar = -1 - (40 * z);
printf("%d\n", aa);;
printf("%d\n", -13);;
int32_t as = x;
printf("%d\n", i);;
printf("%d\n", -7);;
int32_t at = ae;
printf("%d\n", j);;
printf("%d\n", ag - (aj * 1));;
printf("%d\n", (x / (-64 * -44)) + h);;
printf("%d\n", ak);;
int32_t au = (-32 * t) * -6;
printf("%d\n", ai / ((ah * (u - am)) * aj));;
printf("%d\n", 20);;
printf("%d\n", g * ((25 + ((ai - as) / (r / l))) - -22));;
printf("%d\n", ai);;
return 0;}