#include <stdint.h>
int main() {
printf("%d\n", 17);;
printf("%d\n", 17 / 21);;
printf("%d\n", 63 * (-3 + (47 / (-5 - ((61 + 7) - (-28 + 10))))));;
printf("%d\n", 28);;
printf("%d\n", 47);;
printf("%d\n", 47);;
printf("%d\n", 21);;
int32_t a = -5;
printf("%d\n", 56);;
int32_t b = 21;
int32_t c = 29 - (b * a);
printf("%d\n", (((c - -106) - a) - (17 * 45)) + (-48 * c));;
printf("%d\n", (c * (40 / (a + 26))) * ((9 * (a / c)) / ((b + c) - c)));;
printf("%d\n", 27 * c);;
int32_t d = b;
int32_t e = b;
printf("%d\n", 14);;
int32_t f = 66;
printf("%d\n", d + (-4 + (-27 - (a * b))));;
printf("%d\n", b);;
int32_t g = a + -28;
int32_t h = e;
printf("%d\n", -14);;
printf("%d\n", -15);;
printf("%d\n", f / 21);;
printf("%d\n", 44);;
printf("%d\n", 33);;
int32_t i = ((e * (f * c)) + h) + b;
printf("%d\n", (a * ((((g * -27) / (e + ((h * a) - f))) * -37) / 7)) - h);;
printf("%d\n", g);;
printf("%d\n", -19);;
printf("%d\n", a);;
int32_t j = 21;
int32_t k = 12 - -40;
printf("%d\n", -61);;
printf("%d\n", a);;
printf("%d\n", 28);;
printf("%d\n", (-66 * ((d * -29) - -39)) / -25);;
printf("%d\n", -18 / f);;
printf("%d\n", -7);;
printf("%d\n", c + ((-92 / 33) - k));;
printf("%d\n", 37);;
printf("%d\n", 17);;
printf("%d\n", 3);;
printf("%d\n", 95);;
printf("%d\n", f);;
printf("%d\n", -40);;
printf("%d\n", b * ((a * ((((-59 / (d - (g * j))) - 23) - -27) - (-49 * 7))) * k));;
printf("%d\n", -60);;
printf("%d\n", -44);;
int32_t l = h;
printf("%d\n", g);;
printf("%d\n", h);;
int32_t m = h;
printf("%d\n", m);;
printf("%d\n", 36);;
printf("%d\n", 6);;
printf("%d\n", g);;
printf("%d\n", -2);;
printf("%d\n", m);;
printf("%d\n", e);;
int32_t n = l;
int32_t o = e;
printf("%d\n", 7);;
printf("%d\n", i);;
printf("%d\n", e);;
int32_t p = -34;
printf("%d\n", b * (-61 * g));;
int32_t q = a;
printf("%d\n", -4);;
printf("%d\n", 64 - q);;
printf("%d\n", f);;
printf("%d\n", a);;
printf("%d\n", f);;
printf("%d\n", -40 / f);;
int32_t r = a;
return 0;}