#include <stdint.h>
int main() {
printf("%d\n", -51);;
printf("%d\n", 74);;
int32_t a = (-2 - (9 / -1)) - (7 * -6);
int32_t b = 21 * -27;
printf("%d\n", 3);;
int32_t c = a;
printf("%d\n", b + a);;
printf("%d\n", b - 11);;
printf("%d\n", 12);;
printf("%d\n", a);;
printf("%d\n", (-2 - (c - (-81 - -49))) / (5 * a));;
printf("%d\n", 78);;
int32_t d = 11;
int32_t e = a;
printf("%d\n", c + (-27 / a));;
int32_t f = e;
printf("%d\n", (68 / 63) * c);;
printf("%d\n", (2 * -35) * c);;
printf("%d\n", 26 * d);;
printf("%d\n", b);;
printf("%d\n", 9);;
printf("%d\n", -57 * -47);;
printf("%d\n", a);;
printf("%d\n", 11);;
printf("%d\n", -53);;
int32_t g = 44;
printf("%d\n", -1 * (13 / -16));;
int32_t h = -29;
printf("%d\n", -2);;
printf("%d\n", -10);;
printf("%d\n", h + f);;
printf("%d\n", b);;
printf("%d\n", c / -15);;
printf("%d\n", g + f);;
printf("%d\n", e);;
int32_t i = a;
printf("%d\n", i / e);;
int32_t j = -23;
printf("%d\n", -50);;
printf("%d\n", j * ((20 + -24) + 37));;
int32_t k = e + 14;
printf("%d\n", -2 * (k + (34 * (-34 - (-62 + (24 * 6))))));;
int32_t l = 42;
printf("%d\n", -1 / -21);;
printf("%d\n", i - a);;
printf("%d\n", e);;
int32_t m = i + 15;
printf("%d\n", e);;
printf("%d\n", 52);;
printf("%d\n", g);;
printf("%d\n", -46);;
printf("%d\n", (f + -38) - -53);;
printf("%d\n", a);;
printf("%d\n", -15);;
printf("%d\n", -5);;
printf("%d\n", -14);;
int32_t n = i;
printf("%d\n", f / n);;
printf("%d\n", 78);;
printf("%d\n", 34 - d);;
printf("%d\n", (c / -18) - i);;
printf("%d\n", -6);;
printf("%d\n", -45);;
printf("%d\n", l);;
printf("%d\n", l / k);;
printf("%d\n", ((((i / ((k + d) * d)) * 27) / ((-83 * (-8 * -26)) + 12)) * j) * h);;
printf("%d\n", -3);;
printf("%d\n", 43);;
printf("%d\n", 2);;
printf("%d\n", -2);;
printf("%d\n", g);;
int32_t o = d;
printf("%d\n", i);;
printf("%d\n", 23);;
printf("%d\n", ((f * (0 - h)) * -47) - m);;
printf("%d\n", 41 * k);;
printf("%d\n", -27);;
int32_t p = 4;
int32_t q = f;
printf("%d\n", -40);;
printf("%d\n", -69);;
int32_t r = d;
printf("%d\n", -13);;
int32_t s = 34;
printf("%d\n", (-53 * i) * (d / a));;
printf("%d\n", -27);;
printf("%d\n", -17 + 1);;
printf("%d\n", p + o);;
printf("%d\n", -37 - (((((p * c) / (((88 * ((f - (e + (c / -25))) + -76)) + (-44 - n)) - (o / m))) / -28) * ((((30 - l) / c) - -48) / 50)) / i));;
printf("%d\n", j * 12);;
printf("%d\n", i);;
printf("%d\n", (4 + g) - 3);;
printf("%d\n", 39 - -11);;
printf("%d\n", g - (45 * 19));;
printf("%d\n", 12 * -3);;
int32_t t = -28;
printf("%d\n", 43);;
printf("%d\n", j / -7);;
int32_t u = l;
int32_t v = -19 + 65;
printf("%d\n", s * e);;
printf("%d\n", 43);;
printf("%d\n", 65);;
printf("%d\n", e);;
return 0;}