#include <stdint.h>
int main() {
printf("%d\n", 47 + -81);;
printf("%d\n", 24 * -36);;
int32_t a = -14 + 62;
printf("%d\n", a + a);;
printf("%d\n", (a + a) + ((-22 / -25) / a));;
printf("%d\n", -42);;
printf("%d\n", 22);;
printf("%d\n", 124);;
int32_t b = 66;
printf("%d\n", a);;
printf("%d\n", -16);;
printf("%d\n", ((3 + a) / (27 + -37)) + b);;
int32_t c = -16;
int32_t d = 54 - ((c + (b + -1)) - (a - b));
printf("%d\n", c);;
printf("%d\n", a);;
int32_t e = -1;
printf("%d\n", -96 + (-23 - a));;
printf("%d\n", d);;
printf("%d\n", c);;
int32_t f = -42;
printf("%d\n", 3);;
printf("%d\n", 29);;
printf("%d\n", -12);;
printf("%d\n", b);;
int32_t g = c;
int32_t h = c / f;
printf("%d\n", a);;
printf("%d\n", (c + b) * 4);;
printf("%d\n", 36);;
printf("%d\n", 2);;
printf("%d\n", f);;
int32_t i = e;
printf("%d\n", e);;
printf("%d\n", 12);;
printf("%d\n", i);;
int32_t j = 39;
int32_t k = 12;
int32_t l = e;
printf("%d\n", h);;
printf("%d\n", i);;
printf("%d\n", -38);;
printf("%d\n", -28);;
int32_t m = -59;
printf("%d\n", 32);;
printf("%d\n", -56);;
printf("%d\n", g);;
printf("%d\n", l);;
int32_t n = -5;
printf("%d\n", d);;
int32_t o = 28;
printf("%d\n", l);;
printf("%d\n", -4 + 1);;
printf("%d\n", 41);;
printf("%d\n", -15 + (2 + (17 / -10)));;
printf("%d\n", l);;
printf("%d\n", -3);;
printf("%d\n", d);;
printf("%d\n", m);;
printf("%d\n", j);;
printf("%d\n", 26 + -65);;
printf("%d\n", j);;
printf("%d\n", 31);;
printf("%d\n", (n + f) * 131);;
int32_t p = 40;
printf("%d\n", 90);;
printf("%d\n", c);;
int32_t q = (-35 + 12) / 14;
printf("%d\n", 71);;
int32_t r = o;
printf("%d\n", p + (-11 - 75));;
printf("%d\n", ((a * (d - 41)) + (l + ((c * (43 - c)) * (-34 * -22)))) - -57);;
return 0;}