#include <stdint.h>
int main() {
printf("%d\n", -42);;
printf("%d\n", 19);;
printf("%d\n", ((53 - 27) - ((-95 + (-66 * (-11 / 19))) / 63)) + (54 * 65));;
int32_t a = 37;
printf("%d\n", -28);;
printf("%d\n", a);;
printf("%d\n", a * (19 + a));;
printf("%d\n", 51);;
printf("%d\n", a + (-3 * a));;
int32_t b = a;
printf("%d\n", b);;
printf("%d\n", 38);;
int32_t c = b - (a - (-44 / ((a - a) - 8)));
printf("%d\n", (b - 17) * 31);;
int32_t d = 72 * c;
printf("%d\n", b);;
int32_t e = (((((a + -42) - -40) / a) - a) - -24) / 47;
printf("%d\n", a * c);;
printf("%d\n", (5 + (17 - -44)) / (27 + -19));;
printf("%d\n", c - d);;
printf("%d\n", a + (a + c));;
printf("%d\n", 64);;
printf("%d\n", 52);;
printf("%d\n", a);;
printf("%d\n", (-18 * -15) / a);;
printf("%d\n", a);;
int32_t f = a;
printf("%d\n", 58);;
int32_t g = -23;
printf("%d\n", f);;
printf("%d\n", f);;
printf("%d\n", f);;
printf("%d\n", d);;
printf("%d\n", -3);;
printf("%d\n", -17);;
int32_t h = (-19 * -29) / (c + -16);
printf("%d\n", -56);;
printf("%d\n", ((31 / g) * c) * -19);;
int32_t i = 113;
printf("%d\n", c);;
printf("%d\n", -23);;
int32_t j = a;
printf("%d\n", 3);;
printf("%d\n", i);;
printf("%d\n", h);;
printf("%d\n", -104);;
printf("%d\n", (e + (((((26 + -38) * ((i + a) / (2 + (a * f)))) + j) - (48 - ((((((j / (f + 52)) + -15) + j) - e) * -7) * 42))) + (f - 14))) + -17);;
int32_t k = -1;
printf("%d\n", 108);;
int32_t l = ((((-56 / h) * ((-55 * -6) * 34)) / ((56 + (g + 83)) + (c + 50))) * -8) - (i * k);
printf("%d\n", g);;
printf("%d\n", e);;
printf("%d\n", j);;
int32_t m = a - c;
printf("%d\n", -6);;
int32_t n = h + j;
int32_t o = n;
printf("%d\n", (((-27 - (a - (-16 / j))) + -8) + (h * (c + c))) + ((73 - 49) + (b - b)));;
int32_t p = -6;
int32_t q = (92 + (71 * ((-47 - b) * ((36 + 44) + (g + -20))))) - (-19 - 74);
printf("%d\n", ((46 + (p - n)) * (e + (57 + -35))) / i);;
printf("%d\n", 30);;
printf("%d\n", 21);;
printf("%d\n", (89 - b) / ((((k - 53) - (j / (j * 45))) * i) / (26 - (-4 / b))));;
printf("%d\n", j - (b / -64));;
int32_t r = 22 + 52;
printf("%d\n", 24);;
printf("%d\n", -3 * l);;
printf("%d\n", o - r);;
printf("%d\n", -49);;
printf("%d\n", m);;
printf("%d\n", -80);;
printf("%d\n", k);;
printf("%d\n", l);;
int32_t s = -26;
printf("%d\n", (0 - -10) + -16);;
printf("%d\n", 18);;
int32_t t = f - (26 * b);
printf("%d\n", f);;
printf("%d\n", f);;
printf("%d\n", -57);;
printf("%d\n", 55 * j);;
printf("%d\n", (h - m) * -19);;
int32_t u = e;
printf("%d\n", j);;
int32_t v = 53;
printf("%d\n", g);;
int32_t w = 11;
int32_t x = d;
printf("%d\n", g * w);;
printf("%d\n", d + 25);;
printf("%d\n", b);;
printf("%d\n", -52);;
printf("%d\n", (-21 + 55) / 16);;
int32_t y = r;
printf("%d\n", -47);;
printf("%d\n", -41);;
printf("%d\n", v);;
printf("%d\n", d + (7 + c));;
int32_t z = c;
int32_t aa = r;
printf("%d\n", (a * o) / ((i - 16) - -56));;
printf("%d\n", -32);;
printf("%d\n", l);;
printf("%d\n", 25);;
printf("%d\n", r);;
int32_t ab = 15;
printf("%d\n", 44);;
printf("%d\n", 49);;
printf("%d\n", 45);;
printf("%d\n", f - a);;
printf("%d\n", (2 + (h / (ab / k))) + 39);;
printf("%d\n", 43);;
int32_t ac = 59;
int32_t ad = i;
printf("%d\n", (z * (67 - 5)) * 62);;
printf("%d\n", ab);;
int32_t ae = 37;
printf("%d\n", 21);;
printf("%d\n", e);;
int32_t af = -5;
printf("%d\n", 69 * ab);;
printf("%d\n", 45);;
printf("%d\n", -16);;
printf("%d\n", s);;
printf("%d\n", q * o);;
int32_t ag = 34;
printf("%d\n", -52);;
printf("%d\n", ((l / s) * ((t / ad) * (x * (-54 - 58)))) * b);;
printf("%d\n", 23);;
printf("%d\n", 35);;
printf("%d\n", m / ab);;
int32_t ah = ac;
printf("%d\n", (-15 * l) / 11);;
printf("%d\n", g);;
printf("%d\n", -23 - ah);;
printf("%d\n", -16);;
return 0;}