#include <stdint.h>
int main() {
printf("%d\n", 86 - (-8 / (-18 + -10)));;
int32_t a = (30 * 22) - (4 - ((20 + (11 - 8)) - 21));
printf("%d\n", 10 - (-36 + -12));;
printf("%d\n", -38);;
printf("%d\n", a);;
int32_t b = -1;
int32_t c = -23;
printf("%d\n", -18);;
int32_t d = a;
int32_t e = -19 / c;
int32_t f = c;
int32_t g = a;
printf("%d\n", 0);;
printf("%d\n", a);;
printf("%d\n", 43 - f);;
printf("%d\n", c + (f - (f + (29 / ((c - 54) * d)))));;
int32_t h = c + -55;
printf("%d\n", a * (71 + h));;
printf("%d\n", ((18 * (-17 + -33)) + 42) * (g + b));;
printf("%d\n", c);;
int32_t i = 24;
printf("%d\n", f);;
printf("%d\n", 22);;
printf("%d\n", 92);;
printf("%d\n", -4 * a);;
printf("%d\n", i);;
printf("%d\n", c / c);;
int32_t j = 121;
printf("%d\n", 15);;
printf("%d\n", -64);;
printf("%d\n", (e - b) - i);;
printf("%d\n", 44 * ((35 * ((31 - -64) + (-51 - -24))) * c));;
int32_t k = g / j;
int32_t l = i;
printf("%d\n", g);;
printf("%d\n", -2 - 45);;
printf("%d\n", -48 + l);;
printf("%d\n", (k - (c - 83)) + (86 / 49));;
printf("%d\n", f);;
printf("%d\n", -2);;
printf("%d\n", d);;
int32_t m = 67;
printf("%d\n", l);;
printf("%d\n", -1);;
int32_t n = (h / 43) + 30;
printf("%d\n", b);;
printf("%d\n", 33);;
printf("%d\n", 108);;
printf("%d\n", -15);;
printf("%d\n", g * 29);;
printf("%d\n", -47 + ((((f / c) - (f - 48)) + 15) / 48));;
printf("%d\n", j - g);;
printf("%d\n", d);;
printf("%d\n", 18);;
int32_t o = h;
printf("%d\n", i - 12);;
int32_t p = 30 / (80 / -56);
printf("%d\n", 20);;
printf("%d\n", n);;
int32_t q = -13;
printf("%d\n", 72);;
int32_t r = 42;
printf("%d\n", c * e);;
printf("%d\n", (n * g) - -34);;
int32_t s = 57;
printf("%d\n", 43);;
printf("%d\n", -22);;
int32_t t = a + (23 + -41);
printf("%d\n", -44 / o);;
printf("%d\n", -35 * -52);;
printf("%d\n", b);;
int32_t u = -22;
printf("%d\n", l);;
int32_t v = m;
printf("%d\n", 40);;
printf("%d\n", 37);;
printf("%d\n", i - v);;
printf("%d\n", n);;
printf("%d\n", i);;
printf("%d\n", -34);;
printf("%d\n", -2 * (o + o));;
printf("%d\n", i);;
int32_t w = ((h / (-63 * -7)) + 28) / -64;
printf("%d\n", b);;
printf("%d\n", -10);;
printf("%d\n", u - n);;
printf("%d\n", 5);;
printf("%d\n", d);;
printf("%d\n", a);;
printf("%d\n", 3 - (i - (86 / u)));;
printf("%d\n", 23);;
printf("%d\n", t - 6);;
printf("%d\n", m);;
printf("%d\n", 12 - -3);;
int32_t x = 60 * 63;
printf("%d\n", -12);;
int32_t y = 19 + a;
int32_t z = -29;
printf("%d\n", u);;
printf("%d\n", 18 * 39);;
printf("%d\n", u * (-29 / (r + i)));;
printf("%d\n", a);;
printf("%d\n", ((-41 / f) + -32) + l);;
int32_t aa = 43;
printf("%d\n", u);;
int32_t ab = v;
printf("%d\n", -39);;
printf("%d\n", (-11 / ((d - t) + -31)) + ((j / (p * (r + m))) / (-66 - -34)));;
printf("%d\n", -29);;
printf("%d\n", v);;
printf("%d\n", 11);;
printf("%d\n", 47);;
int32_t ac = 8;
int32_t ad = -1;
printf("%d\n", f);;
printf("%d\n", -45);;
printf("%d\n", ((c + (e + 23)) * -16) - (e * -2));;
int32_t ae = g;
printf("%d\n", -35);;
printf("%d\n", y + v);;
printf("%d\n", k);;
int32_t af = 38;
int32_t ag = -62;
printf("%d\n", g);;
return 0;}