#include <stdint.h>
int main() {
printf("%d\n", 6 * -32);;
int32_t a = 63;
int32_t b = (((a - (a * ((-22 / (a - (a - a))) + a))) / ((((a / a) * 7) + 15) * ((a / a) - a))) * ((a * a) / 1)) / (a - -28);
int32_t c = b - -71;
printf("%d\n", c);;
int32_t d = b;
printf("%d\n", d);;
printf("%d\n", -6);;
printf("%d\n", b);;
int32_t e = 4;
printf("%d\n", c);;
printf("%d\n", -8);;
printf("%d\n", -30);;
printf("%d\n", 55 / -44);;
printf("%d\n", -41);;
printf("%d\n", -7);;
printf("%d\n", -66);;
printf("%d\n", -37);;
printf("%d\n", d);;
int32_t f = 3;
printf("%d\n", d);;
printf("%d\n", c);;
printf("%d\n", e);;
int32_t g = (64 + ((a + (e + d)) * (38 + f))) * e;
printf("%d\n", 2);;
printf("%d\n", -13);;
printf("%d\n", 4);;
printf("%d\n", 109);;
printf("%d\n", 9 / a);;
printf("%d\n", d);;
printf("%d\n", -13 - ((-8 / f) - ((d + f) * 58)));;
printf("%d\n", a * (25 + (g + ((g + (28 - c)) / g))));;
printf("%d\n", ((g - e) / 87) + f);;
printf("%d\n", -48 - ((62 + -19) / (b - g)));;
printf("%d\n", c / 3);;
int32_t h = -65 * (b + (e / (e * -16)));
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", c);;
printf("%d\n", h - (e - (f / ((a * (d + ((a + (24 - 48)) + (11 - f)))) - 67))));;
printf("%d\n", (e - h) * ((c * (-3 - g)) - -4));;
printf("%d\n", -43);;
int32_t i = -14;
printf("%d\n", a);;
int32_t j = a;
printf("%d\n", -2);;
printf("%d\n", -43);;
int32_t k = h;
printf("%d\n", e);;
printf("%d\n", 20);;
printf("%d\n", f);;
printf("%d\n", b);;
int32_t l = g;
printf("%d\n", -61);;
printf("%d\n", -50 / -16);;
printf("%d\n", e);;
printf("%d\n", d);;
printf("%d\n", k);;
printf("%d\n", h);;
printf("%d\n", h + ((g * 6) * e));;
printf("%d\n", l + (h - (27 / -2)));;
int32_t m = -23;
printf("%d\n", h);;
printf("%d\n", f);;
printf("%d\n", l);;
printf("%d\n", -34);;
printf("%d\n", i);;
printf("%d\n", d);;
printf("%d\n", l);;
printf("%d\n", h);;
int32_t n = l;
printf("%d\n", 64);;
printf("%d\n", l);;
int32_t o = m;
int32_t p = -3 * c;
printf("%d\n", e);;
int32_t q = p;
printf("%d\n", -12 / q);;
printf("%d\n", i);;
printf("%d\n", -3);;
printf("%d\n", l);;
printf("%d\n", 4);;
printf("%d\n", f);;
printf("%d\n", 32);;
int32_t r = a;
int32_t s = i;
printf("%d\n", -14);;
int32_t t = -6;
printf("%d\n", -13);;
printf("%d\n", -7);;
int32_t u = -13 / (-20 / 10);
return 0;}