#include <stdint.h>
int main() {
int32_t a = -5 - (((26 / 10) + 23) / -49);
printf("%d\n", -54);;
printf("%d\n", -78);;
printf("%d\n", (28 * a) - a);;
printf("%d\n", ((a / -69) - 35) - 8);;
printf("%d\n", 79);;
printf("%d\n", -14);;
int32_t b = -8;
int32_t c = -35 / (34 * a);
printf("%d\n", 28 + b);;
printf("%d\n", -83);;
printf("%d\n", c);;
printf("%d\n", 65 + 6);;
printf("%d\n", c);;
printf("%d\n", 17);;
printf("%d\n", -15 * 7);;
int32_t d = ((-69 - b) * 13) + (b / -29);
printf("%d\n", (c * -30) - b);;
printf("%d\n", d);;
printf("%d\n", (30 - b) - d);;
printf("%d\n", 12);;
printf("%d\n", c - b);;
printf("%d\n", -60);;
printf("%d\n", b);;
int32_t e = ((c * 58) / 9) + -37;
printf("%d\n", (-8 / b) + ((-39 * 9) / a));;
printf("%d\n", -60 + 34);;
printf("%d\n", a);;
int32_t f = -46 - -35;
int32_t g = 15;
printf("%d\n", g);;
printf("%d\n", 22 - ((3 + g) - 1));;
printf("%d\n", 102);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", -43);;
printf("%d\n", 100 / ((((e + b) + (g * -13)) / e) - (((-15 * 3) - 87) * (-48 / 10))));;
printf("%d\n", 44);;
printf("%d\n", b);;
printf("%d\n", f);;
int32_t h = 35;
printf("%d\n", 5);;
int32_t i = -3;
printf("%d\n", f / 32);;
printf("%d\n", -6);;
printf("%d\n", f);;
printf("%d\n", i);;
printf("%d\n", 9 - (9 - f));;
printf("%d\n", (a - i) * c);;
printf("%d\n", -33 + (b * c));;
int32_t j = b;
printf("%d\n", 6);;
int32_t k = (d - f) * (b - 5);
printf("%d\n", -3);;
printf("%d\n", (79 / (h - (k / (15 - -44)))) * 2);;
int32_t l = 6;
printf("%d\n", f);;
int32_t m = -17;
printf("%d\n", j);;
return 0;}