#include <stdint.h>
int main() {
printf("%d\n", 33);;
int32_t a = -17;
printf("%d\n", a);;
int32_t b = a;
printf("%d\n", ((69 / (a * b)) / a) / (b * 35));;
printf("%d\n", a);;
printf("%d\n", 11 / ((-53 / ((77 * -20) - (-32 + b))) - b));;
printf("%d\n", b * a);;
printf("%d\n", b * a);;
printf("%d\n", b);;
int32_t c = 27;
printf("%d\n", b);;
printf("%d\n", -35);;
printf("%d\n", -42);;
int32_t d = a;
printf("%d\n", d);;
printf("%d\n", 19);;
printf("%d\n", d);;
printf("%d\n", d);;
printf("%d\n", -72);;
printf("%d\n", b + 29);;
printf("%d\n", ((b + -11) / -45) + a);;
int32_t e = -73;
int32_t f = -1 - c;
printf("%d\n", c);;
printf("%d\n", 34);;
printf("%d\n", f + -18);;
printf("%d\n", f);;
printf("%d\n", 59 + (((a - -64) - (119 + (-22 / 11))) + b));;
printf("%d\n", a);;
int32_t g = -37;
printf("%d\n", e);;
printf("%d\n", a);;
int32_t h = -34;
printf("%d\n", 6 / (41 + d));;
printf("%d\n", 64 * a);;
printf("%d\n", -30);;
printf("%d\n", -28);;
printf("%d\n", 10 - (16 + -3));;
printf("%d\n", 9);;
printf("%d\n", f);;
printf("%d\n", 37);;
printf("%d\n", 20);;
printf("%d\n", -4 * 14);;
int32_t i = 5;
printf("%d\n", 1);;
int32_t j = -34;
printf("%d\n", f);;
int32_t k = b;
printf("%d\n", 9);;
int32_t l = i;
int32_t m = a;
int32_t n = -24;
printf("%d\n", h);;
int32_t o = f;
printf("%d\n", -8 * ((b - (j * 87)) * (9 + (-8 + ((9 * (((-12 / j) / -43) / ((j * (((20 * o) * (((i * -56) - k) / c)) / 32)) + -29))) * (0 / c))))));;
printf("%d\n", 38);;
printf("%d\n", k * -52);;
return 0;}