#include <stdint.h>
int main() {
printf("%d\n", 25 * 34);;
printf("%d\n", -71);;
int32_t a = -14 - -31;
int32_t b = a;
int32_t c = 27 - -15;
printf("%d\n", ((23 + (-32 / a)) * 66) + (c / (-25 + (18 + ((((a - c) / (65 + -104)) * -34) * ((-53 - 25) * 23))))));;
printf("%d\n", 37 * (-23 - (a * -6)));;
printf("%d\n", -10);;
printf("%d\n", -2);;
printf("%d\n", 7);;
int32_t d = c;
int32_t e = c / b;
printf("%d\n", e + -73);;
printf("%d\n", b * ((((a * 36) * -32) - 5) - c));;
printf("%d\n", -17);;
printf("%d\n", c);;
printf("%d\n", a * (d - -32));;
printf("%d\n", -50);;
printf("%d\n", -54);;
printf("%d\n", 43);;
printf("%d\n", 33);;
printf("%d\n", 2);;
printf("%d\n", c);;
printf("%d\n", 54);;
printf("%d\n", d);;
printf("%d\n", 17 / -38);;
printf("%d\n", b);;
int32_t f = -28;
printf("%d\n", 10);;
printf("%d\n", c);;
printf("%d\n", e);;
printf("%d\n", -24);;
printf("%d\n", -4 / (11 - (-4 * (10 + d))));;
printf("%d\n", -25);;
printf("%d\n", 25);;
printf("%d\n", a);;
printf("%d\n", 59 * 10);;
printf("%d\n", -86);;
int32_t g = (16 - 14) / c;
printf("%d\n", g);;
printf("%d\n", ((-30 - 22) - 80) - (e + (f - 59)));;
printf("%d\n", d);;
int32_t h = 20;
int32_t i = h;
printf("%d\n", -4);;
printf("%d\n", b);;
printf("%d\n", 29);;
printf("%d\n", 32);;
printf("%d\n", c / (-4 + 56));;
printf("%d\n", h);;
printf("%d\n", a);;
printf("%d\n", f - 67);;
printf("%d\n", a / 60);;
printf("%d\n", e);;
printf("%d\n", 48);;
printf("%d\n", -21);;
int32_t j = e;
printf("%d\n", g);;
int32_t k = -6;
printf("%d\n", h);;
printf("%d\n", a);;
printf("%d\n", a / -20);;
printf("%d\n", h);;
printf("%d\n", -38);;
int32_t l = -27;
int32_t m = -38;
printf("%d\n", -2);;
int32_t n = 36 / a;
printf("%d\n", -19);;
printf("%d\n", 110);;
printf("%d\n", 27);;
int32_t o = -13;
printf("%d\n", -6);;
return 0;}