#include <stdint.h>
int main() {
printf("%d\n", 42 - 35);;
printf("%d\n", 40);;
printf("%d\n", -9);;
int32_t a = -43;
printf("%d\n", a);;
printf("%d\n", -13);;
printf("%d\n", -21);;
int32_t b = 66;
printf("%d\n", 73 + 10);;
printf("%d\n", b);;
printf("%d\n", -49 * b);;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", b);;
int32_t c = b;
printf("%d\n", -41);;
printf("%d\n", -76);;
int32_t d = c;
printf("%d\n", d / d);;
printf("%d\n", b);;
printf("%d\n", 57 / -13);;
printf("%d\n", 36);;
printf("%d\n", d);;
printf("%d\n", 12);;
printf("%d\n", 28);;
printf("%d\n", -53);;
printf("%d\n", a);;
printf("%d\n", ((-23 / -14) * a) / (-43 + -70));;
printf("%d\n", c);;
int32_t e = 4 * a;
printf("%d\n", -14 - 19);;
printf("%d\n", -4);;
printf("%d\n", 18 + 9);;
int32_t f = 9;
printf("%d\n", -5 / b);;
int32_t g = ((-36 / ((-36 - 43) - 39)) + -69) / 16;
printf("%d\n", (f * -5) / c);;
printf("%d\n", b / f);;
int32_t h = a;
printf("%d\n", 15);;
int32_t i = 49;
printf("%d\n", a);;
int32_t j = 28;
int32_t k = 38;
printf("%d\n", -29 - c);;
int32_t l = e;
printf("%d\n", -72);;
int32_t m = a;
printf("%d\n", -64 - (c / (j * ((((((-2 * (-37 - (h * f))) * -15) - ((-7 / ((19 + (-80 + j)) * -35)) + 104)) - b) - -61) * -18))));;
printf("%d\n", b);;
int32_t n = (i - h) + ((6 + -22) / 5);
int32_t o = f / (-17 / -13);
printf("%d\n", -20);;
printf("%d\n", (d + (b * (j * (12 - (58 / l))))) * e);;
printf("%d\n", ((45 - -20) * ((a + -41) - e)) / l);;
printf("%d\n", b);;
printf("%d\n", o - -38);;
printf("%d\n", f);;
int32_t p = 15;
printf("%d\n", 14);;
printf("%d\n", 27 * ((j * 5) + n));;
int32_t q = -1 / (-39 - -19);
printf("%d\n", (3 / (-32 * (c + (d + (-30 - l))))) * d);;
printf("%d\n", e);;
printf("%d\n", -8);;
printf("%d\n", -21);;
printf("%d\n", -64);;
int32_t r = m - (i - 22);
printf("%d\n", 17);;
printf("%d\n", l);;
printf("%d\n", r);;
printf("%d\n", 5);;
printf("%d\n", 1);;
int32_t s = 3;
printf("%d\n", o);;
printf("%d\n", p);;
int32_t t = 1;
printf("%d\n", 15);;
printf("%d\n", r);;
printf("%d\n", -26);;
printf("%d\n", -20 + b);;
printf("%d\n", -54);;
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", c);;
printf("%d\n", p);;
printf("%d\n", m);;
printf("%d\n", m);;
printf("%d\n", k);;
printf("%d\n", (n * (q - -84)) + 11);;
int32_t u = n + ((((2 + (g - (-16 - -3))) / (q - ((g * (82 * c)) - f))) - e) * p);
int32_t v = -2;
int32_t w = r;
printf("%d\n", -26);;
printf("%d\n", 54);;
printf("%d\n", g / c);;
printf("%d\n", 55);;
printf("%d\n", o);;
printf("%d\n", m / (n - (e + (26 / ((e / (d + f)) - q)))));;
printf("%d\n", 50);;
printf("%d\n", 74);;
printf("%d\n", b);;
printf("%d\n", 101);;
int32_t x = k;
printf("%d\n", r);;
printf("%d\n", 5);;
printf("%d\n", e);;
printf("%d\n", 4);;
printf("%d\n", 18 / 66);;
int32_t y = m;
printf("%d\n", 25);;
printf("%d\n", -65);;
printf("%d\n", g - ((-16 + i) + r));;
int32_t z = -21;
int32_t aa = 47;
printf("%d\n", r);;
printf("%d\n", 15);;
int32_t ab = 48;
return 0;}