#include <stdint.h>
int main() {
printf("%d\n", 83);;
printf("%d\n", 39);;
printf("%d\n", 24);;
printf("%d\n", 19 / 4);;
printf("%d\n", -32);;
printf("%d\n", -19 / 34);;
int32_t a = 12;
printf("%d\n", -7 * a);;
printf("%d\n", a * 44);;
printf("%d\n", -28);;
printf("%d\n", 0);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a / (((a / 35) + a) - (5 - 76)));;
int32_t b = -5 - a;
printf("%d\n", 32 * (a / -51));;
printf("%d\n", 19);;
printf("%d\n", 13);;
int32_t c = (((13 - -25) * (b - -29)) - b) + -84;
printf("%d\n", (b * 3) + ((-34 * b) - (((((62 - (b * b)) + 15) - 42) / 4) / (b * c))));;
printf("%d\n", b);;
printf("%d\n", a);;
printf("%d\n", 47 - a);;
int32_t d = -21 + (39 + ((-21 + a) - 37));
printf("%d\n", c / 35);;
printf("%d\n", 30);;
printf("%d\n", b);;
printf("%d\n", a);;
int32_t e = 13 + -25;
printf("%d\n", a);;
printf("%d\n", -41 - (e / -24));;
printf("%d\n", c - -5);;
printf("%d\n", (e + (((17 * (((e / ((-48 * ((a / a) + (-27 - -80))) / e)) + (-8 * ((b / 50) - d))) / -31)) / 21) - 5)) + 63);;
int32_t f = c;
printf("%d\n", -56);;
printf("%d\n", c / -18);;
printf("%d\n", 18 * d);;
int32_t g = 30;
printf("%d\n", -1);;
int32_t h = -95;
printf("%d\n", c);;
printf("%d\n", b - (a - c));;
printf("%d\n", 59);;
printf("%d\n", e);;
printf("%d\n", -18);;
printf("%d\n", 61);;
printf("%d\n", -71);;
printf("%d\n", c);;
printf("%d\n", 25);;
printf("%d\n", 45);;
printf("%d\n", 67);;
printf("%d\n", 16);;
printf("%d\n", h);;
int32_t i = c / -69;
int32_t j = -41;
printf("%d\n", 64);;
int32_t k = -32;
printf("%d\n", c);;
printf("%d\n", d);;
printf("%d\n", (c - b) / (10 / (13 / -2)));;
printf("%d\n", -63 - -13);;
printf("%d\n", d);;
printf("%d\n", 42);;
printf("%d\n", b);;
printf("%d\n", 44);;
printf("%d\n", d);;
printf("%d\n", h);;
printf("%d\n", g);;
printf("%d\n", (18 + -85) / 8);;
printf("%d\n", c - (-29 * 36));;
printf("%d\n", a);;
printf("%d\n", d - d);;
printf("%d\n", -45);;
printf("%d\n", -9);;
printf("%d\n", -4 - 56);;
printf("%d\n", -16);;
printf("%d\n", -38 / -15);;
int32_t l = 32;
printf("%d\n", ((c * c) + i) + k);;
int32_t m = a;
printf("%d\n", (46 - ((((f - -16) + 16) - e) - g)) - (-28 + ((-15 * 50) * (i * (d + b)))));;
printf("%d\n", l);;
printf("%d\n", 13 - 23);;
printf("%d\n", (27 + g) * 35);;
printf("%d\n", -27 - -23);;
int32_t n = (-27 + (d / e)) / (l / i);
int32_t o = f;
printf("%d\n", l);;
printf("%d\n", c);;
printf("%d\n", l);;
printf("%d\n", 0 - h);;
printf("%d\n", -82 * -10);;
printf("%d\n", h);;
printf("%d\n", j - 30);;
printf("%d\n", -20);;
printf("%d\n", 19);;
printf("%d\n", l);;
printf("%d\n", (18 / l) * ((n / h) + (51 - -22)));;
printf("%d\n", 0);;
printf("%d\n", k - (f * (f / -62)));;
printf("%d\n", -15 - k);;
printf("%d\n", -52);;
int32_t p = -92;
printf("%d\n", 27 - -29);;
int32_t q = 10;
printf("%d\n", -7);;
printf("%d\n", -7 * n);;
printf("%d\n", g + ((f + e) / c));;
printf("%d\n", (-32 + (-62 + g)) / p);;
int32_t r = c;
printf("%d\n", 31);;
printf("%d\n", -11);;
printf("%d\n", e);;
printf("%d\n", -15);;
int32_t s = 20;
printf("%d\n", o / a);;
printf("%d\n", -47);;
printf("%d\n", b);;
int32_t t = c;
printf("%d\n", 3);;
int32_t u = 9;
printf("%d\n", -41);;
printf("%d\n", 49 / 3);;
printf("%d\n", -4);;
printf("%d\n", b);;
printf("%d\n", 9);;
printf("%d\n", n - (j / p));;
printf("%d\n", i);;
printf("%d\n", ((((-45 + (-8 * c)) - (a + -10)) - (-30 / -18)) * (b - c)) / p);;
printf("%d\n", d * -59);;
printf("%d\n", t);;
printf("%d\n", j - p);;
printf("%d\n", g);;
int32_t v = -27;
return 0;}