#include <stdint.h>
int main() {
printf("%d\n", (-9 + (9 * (3 + (9 / (55 / 31))))) * (((22 - ((((10 + 49) + (34 * -21)) * -24) - ((0 - 4) / ((26 + (-6 + 5)) - (34 / -2))))) * ((31 / 26) * 41)) / 39));;
printf("%d\n", -91 - -15);;
int32_t a = -3;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", 23);;
printf("%d\n", (48 * -40) + a);;
printf("%d\n", a);;
printf("%d\n", 49);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", a * a);;
printf("%d\n", 4);;
printf("%d\n", a);;
printf("%d\n", a);;
printf("%d\n", -22);;
printf("%d\n", 4 - 12);;
printf("%d\n", a);;
printf("%d\n", 12);;
printf("%d\n", ((a - a) * a) / a);;
printf("%d\n", (0 + a) / a);;
printf("%d\n", -39);;
printf("%d\n", a / (a * a));;
printf("%d\n", 0 + (a / a));;
int32_t b = (-20 / a) + -51;
int32_t c = b / a;
int32_t d = 44;
printf("%d\n", a);;
printf("%d\n", 28);;
printf("%d\n", -2);;
printf("%d\n", 48 * 61);;
printf("%d\n", ((c * (31 + (21 / (d + ((-61 / ((78 * (33 + c)) / a)) - (d * -23)))))) - (-8 / (-115 / (b / a)))) * c);;
int32_t e = 80;
printf("%d\n", a);;
printf("%d\n", -22 + d);;
int32_t f = d;
printf("%d\n", 80 + (b / -16));;
printf("%d\n", -3);;
printf("%d\n", 90 + -6);;
printf("%d\n", 19 + -30);;
printf("%d\n", 34);;
int32_t g = b / e;
printf("%d\n", 33);;
printf("%d\n", g);;
int32_t h = b - a;
printf("%d\n", a);;
printf("%d\n", 17);;
printf("%d\n", a);;
int32_t i = b / c;
printf("%d\n", a / (((b * g) - -25) * (-45 / 13)));;
printf("%d\n", -6);;
printf("%d\n", g);;
printf("%d\n", f);;
printf("%d\n", b / (87 - -15));;
printf("%d\n", e - ((d - 2) / -69));;
int32_t j = (b * g) - a;
int32_t k = 1 + e;
printf("%d\n", i);;
printf("%d\n", 21);;
printf("%d\n", j);;
printf("%d\n", k);;
printf("%d\n", -18);;
return 0;}