#include <stdint.h>
int main() {
printf("%d\n", 1);;
printf("%d\n", 10);;
int32_t a = 66 / -17;
int32_t b = a;
printf("%d\n", -38);;
printf("%d\n", a / a);;
printf("%d\n", -33);;
printf("%d\n", (b - b) - a);;
printf("%d\n", a);;
int32_t c = b;
printf("%d\n", a);;
printf("%d\n", 38 / c);;
printf("%d\n", a);;
printf("%d\n", 0);;
printf("%d\n", 106 + 29);;
int32_t d = 14;
printf("%d\n", c);;
printf("%d\n", 79);;
int32_t e = d - (5 / 25);
printf("%d\n", e - (d + -20));;
printf("%d\n", e / (2 * 22));;
printf("%d\n", a);;
int32_t f = d;
printf("%d\n", 42);;
printf("%d\n", e);;
printf("%d\n", 2);;
printf("%d\n", -12 - -16);;
printf("%d\n", 42 + c);;
printf("%d\n", -31);;
printf("%d\n", a);;
printf("%d\n", d - (e + (f / -16)));;
int32_t g = d;
printf("%d\n", c);;
printf("%d\n", -26);;
printf("%d\n", b);;
printf("%d\n", f);;
printf("%d\n", -33 - -18);;
int32_t h = 35;
printf("%d\n", (19 * a) * -47);;
int32_t i = 58;
printf("%d\n", 5 * -28);;
printf("%d\n", -48 / ((24 * a) * (h * (-29 + b))));;
printf("%d\n", -40);;
printf("%d\n", -26);;
printf("%d\n", a);;
printf("%d\n", d / (42 - i));;
printf("%d\n", ((-2 + 56) - (16 + -45)) + 11);;
printf("%d\n", i);;
printf("%d\n", e);;
int32_t j = a;
printf("%d\n", -95);;
int32_t k = g;
printf("%d\n", d);;
printf("%d\n", e);;
int32_t l = g;
int32_t m = 13;
printf("%d\n", 29);;
printf("%d\n", -47);;
printf("%d\n", c);;
printf("%d\n", 3);;
printf("%d\n", j + (m + ((f / -40) - l)));;
printf("%d\n", 21);;
printf("%d\n", -33);;
printf("%d\n", 29);;
printf("%d\n", -31);;
printf("%d\n", j - (f / (-33 / 1)));;
printf("%d\n", 73);;
printf("%d\n", -23);;
printf("%d\n", m * i);;
printf("%d\n", -56 - m);;
printf("%d\n", 36);;
printf("%d\n", 30);;
int32_t n = i;
printf("%d\n", -26);;
printf("%d\n", g - (44 / h));;
int32_t o = h * c;
int32_t p = 17;
printf("%d\n", h);;
printf("%d\n", -12);;
printf("%d\n", 34 * c);;
printf("%d\n", e);;
printf("%d\n", (k * 28) / e);;
int32_t q = l;
printf("%d\n", g);;
printf("%d\n", 0);;
printf("%d\n", (96 * i) + (((-42 / j) + 0) + 27));;
printf("%d\n", 55);;
printf("%d\n", q);;
printf("%d\n", e);;
printf("%d\n", e);;
printf("%d\n", m + (((b + ((8 - a) + ((-62 + (h / (q - (q / d)))) - (k - i)))) - (-65 - o)) + b));;
printf("%d\n", 5);;
printf("%d\n", e);;
printf("%d\n", -24);;
int32_t r = d * (a - -69);
int32_t s = 36 / (h + (d - m));
printf("%d\n", 31);;
int32_t t = (l + j) / r;
int32_t u = -4;
printf("%d\n", (k * -48) / -27);;
printf("%d\n", 41);;
int32_t v = -8;
printf("%d\n", 7);;
printf("%d\n", 22);;
int32_t w = (o - 30) + (c * f);
printf("%d\n", -28);;
int32_t x = -11;
printf("%d\n", -7);;
printf("%d\n", p - (w - k));;
printf("%d\n", j);;
printf("%d\n", b);;
int32_t y = -18;
printf("%d\n", (a / x) / 6);;
printf("%d\n", x);;
printf("%d\n", 43 + g);;
printf("%d\n", -36);;
printf("%d\n", (g / g) + -36);;
printf("%d\n", -1 / ((13 - 14) - (d * (e * 1))));;
printf("%d\n", 21 * c);;
printf("%d\n", 13);;
printf("%d\n", p + v);;
printf("%d\n", a);;
printf("%d\n", 62);;
printf("%d\n", 31);;
printf("%d\n", -6);;
int32_t z = j * (-10 - ((-1 - 29) * (((8 / -43) + v) - l)));
int32_t aa = (m - (78 * ((15 + (v - ((i * -24) * 4))) - (((b / 47) * -24) * v)))) + r;
printf("%d\n", b);;
printf("%d\n", 65);;
printf("%d\n", ((u - (t - 71)) * 1) + 15);;
printf("%d\n", -3);;
int32_t ab = (b / (12 - 29)) + (60 - 9);
printf("%d\n", b);;
int32_t ac = (((a - 27) + -40) * i) * 74;
int32_t ad = -23 + f;
printf("%d\n", (-22 * s) - 5);;
printf("%d\n", ((55 / 11) / (o + 10)) - 92);;
int32_t ae = y;
printf("%d\n", g / ((-53 + 42) + s));;
int32_t af = c;
printf("%d\n", ((-29 + -14) / (-88 - (ae - 30))) + (6 * (-35 - q)));;
printf("%d\n", e);;
printf("%d\n", 36);;
printf("%d\n", s - r);;
printf("%d\n", v + (73 - (((a + 20) - u) + -36)));;
printf("%d\n", 23);;
printf("%d\n", 12);;
printf("%d\n", -34 * 2);;
printf("%d\n", 31);;
int32_t ag = t - (((p - c) / v) - ((w / r) / -24));
printf("%d\n", h / (-29 * 23));;
printf("%d\n", -33 / (ad * -13));;
printf("%d\n", 6);;
printf("%d\n", 122);;
printf("%d\n", -9);;
printf("%d\n", -75);;
printf("%d\n", 36);;
printf("%d\n", -27);;
printf("%d\n", j);;
printf("%d\n", m);;
printf("%d\n", c);;
int32_t ah = ae;
int32_t ai = -3;
printf("%d\n", h * ae);;
printf("%d\n", r);;
int32_t aj = ab;
int32_t ak = x;
int32_t al = -25;
int32_t am = -65 - o;
printf("%d\n", 39);;
printf("%d\n", -4 / ad);;
printf("%d\n", -59);;
printf("%d\n", ak);;
return 0;}