#include <stdint.h>
int main() {
int32_t a = -25;
int32_t b = 2;
printf("%d\n", -13);;
printf("%d\n", -18);;
printf("%d\n", b);;
printf("%d\n", b);;
printf("%d\n", -10);;
printf("%d\n", a + (b + a));;
printf("%d\n", b);;
int32_t c = b;
int32_t d = 69;
int32_t e = -21;
printf("%d\n", 67 * (((c / e) + d) * (-57 + (a * -15))));;
printf("%d\n", e / (5 + a));;
printf("%d\n", c);;
printf("%d\n", e);;
int32_t f = e;
printf("%d\n", 17 * 4);;
printf("%d\n", d);;
printf("%d\n", -53);;
printf("%d\n", e * (((22 + c) - 24) + ((43 / 33) - 59)));;
printf("%d\n", 56);;
printf("%d\n", -20);;
printf("%d\n", e);;
int32_t g = b;
printf("%d\n", f);;
printf("%d\n", ((((-9 / -19) / -3) - 69) - d) + 27);;
printf("%d\n", ((-20 + a) * 12) + a);;
printf("%d\n", b);;
printf("%d\n", -3);;
printf("%d\n", c + (c - (((-8 * d) + (g / a)) * f)));;
printf("%d\n", -12);;
printf("%d\n", a + -1);;
printf("%d\n", 52);;
printf("%d\n", f);;
printf("%d\n", e);;
printf("%d\n", 27 + (d / e));;
printf("%d\n", e);;
printf("%d\n", b);;
printf("%d\n", c);;
int32_t h = 100;
printf("%d\n", a);;
printf("%d\n", -6 + g);;
printf("%d\n", b * 14);;
printf("%d\n", 107);;
printf("%d\n", -16);;
printf("%d\n", -34);;
int32_t i = e;
int32_t j = c;
printf("%d\n", d - -12);;
return 0;}